// Generated by `wit-bindgen` 0.60.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod tegmentum {
        pub mod i18n_linebreak {
            /// Shared types. Split into its own interface so the `linebreak` and
            /// `capabilities` interfaces can `use` the same definitions.
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod types {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() =
                    super::super::super::super::__link_custom_section_describing_imports;

                use super::super::super::super::_rt;
                /// BCP 47 locale tag: "en", "ja-JP", …. The empty string denotes
                /// the CLDR root locale. Accepted for forward compatibility with
                /// per-locale tailorings; Phase 5 applies the UAX #14 default
                /// rules regardless of the tag.
                pub type Locale = _rt::String;
                /// Distinguishes a mandatory break (paragraph separator, CR, LF,
                /// NEL) from a discretionary one (space, hyphen, ZWJ, …). See
                /// UAX #14 § 6 for the rule numbers behind each classification.
                #[derive(Clone, Copy)]
                pub enum BreakKind {
                    /// A required break introduced by BK / CR / LF / NL. A
                    /// conformant layout engine MUST insert a line break here.
                    Mandatory,
                    /// A discretionary break — the layout engine is free to
                    /// insert a line break at this position, but is not required
                    /// to.
                    Allowed,
                }
                impl ::core::fmt::Debug for BreakKind {
                    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                        match self {
                            BreakKind::Mandatory => f.debug_tuple("BreakKind::Mandatory").finish(),
                            BreakKind::Allowed => f.debug_tuple("BreakKind::Allowed").finish(),
                        }
                    }
                }
                /// One break-opportunity record.
                ///
                /// `offset` is the UTF-8 byte offset at which the layout engine
                /// may (or must) insert the break. The last emitted opportunity
                /// always sits at `len(input)` and carries `kind = allowed`
                /// unless the input ends with a mandatory break, in which case
                /// the last opportunity's kind reflects the terminator.
                #[repr(C)]
                #[derive(Clone, Copy)]
                pub struct BreakOpportunity {
                    /// UTF-8 byte offset of the break opportunity.
                    pub offset: u32,
                    /// Whether the break is mandatory or discretionary.
                    pub kind: BreakKind,
                }
                impl ::core::fmt::Debug for BreakOpportunity {
                    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                        f.debug_struct("BreakOpportunity")
                            .field("offset", &self.offset)
                            .field("kind", &self.kind)
                            .finish()
                    }
                }
                /// CJK strictness tailoring (UAX #14 § 6.1). CSS `line-break`
                /// authors: `loose` matches `line-break: loose`, `strict`
                /// matches `line-break: strict`, `normal` is the CLDR default.
                #[repr(u8)]
                #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
                pub enum LineBreakStrictness {
                    /// Loose — expand the set of allowed break opportunities
                    /// (small-kana, hyphens, iteration marks).
                    Loose,
                    /// Normal — the CLDR default.
                    Normal,
                    /// Strict — contract the set of allowed break opportunities.
                    Strict,
                }
                impl ::core::fmt::Debug for LineBreakStrictness {
                    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                        match self {
                            LineBreakStrictness::Loose => {
                                f.debug_tuple("LineBreakStrictness::Loose").finish()
                            }
                            LineBreakStrictness::Normal => {
                                f.debug_tuple("LineBreakStrictness::Normal").finish()
                            }
                            LineBreakStrictness::Strict => {
                                f.debug_tuple("LineBreakStrictness::Strict").finish()
                            }
                        }
                    }
                }

                impl LineBreakStrictness {
                    #[doc(hidden)]
                    pub unsafe fn _lift(val: u8) -> LineBreakStrictness {
                        if !cfg!(debug_assertions) {
                            return unsafe { ::core::mem::transmute(val) };
                        }

                        match val {
                            0 => LineBreakStrictness::Loose,
                            1 => LineBreakStrictness::Normal,
                            2 => LineBreakStrictness::Strict,

                            _ => panic!("invalid enum discriminant"),
                        }
                    }
                }

                #[doc(hidden)]

                macro_rules! __export_tegmentum_i18n_linebreak_types_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _: () = {};
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_tegmentum_i18n_linebreak_types_0_1_0_cabi;
            }

            /// The core line-break surface.
            ///
            /// Every function takes an input string plus (for the strictness
            /// variant) a strictness tag, and returns the list of break
            /// opportunities in UTF-8-byte-offset-sorted order.
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod linebreak {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() =
                    super::super::super::super::__link_custom_section_describing_imports;

                use super::super::super::super::_rt;
                pub type Locale =
                    super::super::super::super::exports::tegmentum::i18n_linebreak::types::Locale;
                pub type BreakOpportunity = super::super::super::super::exports::tegmentum::i18n_linebreak::types::BreakOpportunity;
                pub type LineBreakStrictness = super::super::super::super::exports::tegmentum::i18n_linebreak::types::LineBreakStrictness;
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_find_breaks_cabi<T_: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) -> *mut u8 {
                    unsafe {
                        #[cfg(target_arch = "wasm32")]
                        _rt::run_ctors_once();
                        let result1 = {
                            let len0 = arg1;
                            let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                            T_::find_breaks(_rt::string_lift(bytes0))
                        };
                        let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                        let vec5 = result1;
                        let len5 = vec5.len();
                        let layout5 =
                            _rt::alloc::Layout::from_size_align(vec5.len() * 8, 4).unwrap();
                        let (result5, _cleanup5) = wit_bindgen_rt::Cleanup::new(layout5);
                        if let Some(cleanup) = _cleanup5 {
                            cleanup.forget();
                        }
                        for (i, e) in vec5.into_iter().enumerate() {
                            let base = result5.add(i * 8);
                            {
                                let super::super::super::super::exports::tegmentum::i18n_linebreak::types::BreakOpportunity{ offset:offset3, kind:kind3, } = e;
                                *base.add(0).cast::<i32>() = _rt::as_i32(offset3);
                                use super::super::super::super::exports::tegmentum::i18n_linebreak::types::BreakKind as V4;
                                match kind3 {
                                    V4::Mandatory => {
                                        *base.add(4).cast::<u8>() = (0i32) as u8;
                                    }
                                    V4::Allowed => {
                                        *base.add(4).cast::<u8>() = (1i32) as u8;
                                    }
                                }
                            }
                        }
                        *ptr2
                            .add(::core::mem::size_of::<*const u8>())
                            .cast::<usize>() = len5;
                        *ptr2.add(0).cast::<*mut u8>() = result5;
                        ptr2
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_find_breaks<T_: Guest>(arg0: *mut u8) {
                    unsafe {
                        let l0 = *arg0.add(0).cast::<*mut u8>();
                        let l1 = *arg0
                            .add(::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let base2 = l0;
                        let len2 = l1;
                        _rt::cabi_dealloc(base2, len2 * 8, 4);
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_find_breaks_with_strictness_cabi<T_: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: i32,
                ) -> *mut u8 {
                    unsafe {
                        #[cfg(target_arch = "wasm32")]
                        _rt::run_ctors_once();
                        let result1 = {
                            let len0 = arg1;
                            let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                            T_::find_breaks_with_strictness(_rt::string_lift(bytes0), super::super::super::super::exports::tegmentum::i18n_linebreak::types::LineBreakStrictness::_lift(arg2 as u8))
                        };
                        let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                        let vec5 = result1;
                        let len5 = vec5.len();
                        let layout5 =
                            _rt::alloc::Layout::from_size_align(vec5.len() * 8, 4).unwrap();
                        let (result5, _cleanup5) = wit_bindgen_rt::Cleanup::new(layout5);
                        if let Some(cleanup) = _cleanup5 {
                            cleanup.forget();
                        }
                        for (i, e) in vec5.into_iter().enumerate() {
                            let base = result5.add(i * 8);
                            {
                                let super::super::super::super::exports::tegmentum::i18n_linebreak::types::BreakOpportunity{ offset:offset3, kind:kind3, } = e;
                                *base.add(0).cast::<i32>() = _rt::as_i32(offset3);
                                use super::super::super::super::exports::tegmentum::i18n_linebreak::types::BreakKind as V4;
                                match kind3 {
                                    V4::Mandatory => {
                                        *base.add(4).cast::<u8>() = (0i32) as u8;
                                    }
                                    V4::Allowed => {
                                        *base.add(4).cast::<u8>() = (1i32) as u8;
                                    }
                                }
                            }
                        }
                        *ptr2
                            .add(::core::mem::size_of::<*const u8>())
                            .cast::<usize>() = len5;
                        *ptr2.add(0).cast::<*mut u8>() = result5;
                        ptr2
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_find_breaks_with_strictness<T_: Guest>(arg0: *mut u8) {
                    unsafe {
                        let l0 = *arg0.add(0).cast::<*mut u8>();
                        let l1 = *arg0
                            .add(::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let base2 = l0;
                        let len2 = l1;
                        _rt::cabi_dealloc(base2, len2 * 8, 4);
                    }
                }
                pub trait Guest {
                    /// Enumerate every break opportunity in `text` under the CLDR
                    /// default (normal) strictness.
                    ///
                    /// The returned list carries one record per opportunity in
                    /// strictly-increasing offset order. Empty input returns the
                    /// empty list.
                    #[allow(async_fn_in_trait)]
                    fn find_breaks(text: _rt::String) -> _rt::Vec<BreakOpportunity>;
                    /// As [`find-breaks`], but the caller selects a CJK strictness
                    /// tailoring per UAX #14 § 6.1.
                    #[allow(async_fn_in_trait)]
                    fn find_breaks_with_strictness(
                        text: _rt::String,
                        strictness: LineBreakStrictness,
                    ) -> _rt::Vec<BreakOpportunity>;
                }
                #[doc(hidden)]

                macro_rules! __export_tegmentum_i18n_linebreak_linebreak_0_1_0_cabi{
      ($ty:ident with_types_in $($path_to_types:tt)*) => (const _: () = {

        #[unsafe(export_name = "tegmentum:i18n-linebreak/linebreak@0.1.0#find-breaks")]
        unsafe extern "C" fn export_find_breaks(arg0: *mut u8,arg1: usize,) -> *mut u8 {
          unsafe { $($path_to_types)*::_export_find_breaks_cabi::<$ty>(arg0, arg1) }
        }
        #[unsafe(export_name = "cabi_post_tegmentum:i18n-linebreak/linebreak@0.1.0#find-breaks")]
        unsafe extern "C" fn _post_return_find_breaks(arg0: *mut u8,) {
          unsafe { $($path_to_types)*::__post_return_find_breaks::<$ty>(arg0) }
        }
        #[unsafe(export_name = "tegmentum:i18n-linebreak/linebreak@0.1.0#find-breaks-with-strictness")]
        unsafe extern "C" fn export_find_breaks_with_strictness(arg0: *mut u8,arg1: usize,arg2: i32,) -> *mut u8 {
          unsafe { $($path_to_types)*::_export_find_breaks_with_strictness_cabi::<$ty>(arg0, arg1, arg2) }
        }
        #[unsafe(export_name = "cabi_post_tegmentum:i18n-linebreak/linebreak@0.1.0#find-breaks-with-strictness")]
        unsafe extern "C" fn _post_return_find_breaks_with_strictness(arg0: *mut u8,) {
          unsafe { $($path_to_types)*::__post_return_find_breaks_with_strictness::<$ty>(arg0) }
        }
      };);
    }
                #[doc(hidden)]
                pub(crate) use __export_tegmentum_i18n_linebreak_linebreak_0_1_0_cabi;

                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<u8>; 2 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 2 * ::core::mem::size_of::<*const u8>()],
                );
            }

            /// Introspection: which locales does the linked component actually
            /// cover?
            ///
            /// Phase 5's follow-up ships the locale-neutral default only; the
            /// returned list carries the root-locale marker `""` and nothing
            /// else. Locale-specific tailorings (Japanese `ja`, Chinese `zh-Hans`,
            /// Korean `ko`) are documented deferrals — the WIT surface is
            /// ready but the built-in engine falls through to the default rules
            /// for every input.
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod capabilities {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() =
                    super::super::super::super::__link_custom_section_describing_imports;

                use super::super::super::super::_rt;
                pub type Locale =
                    super::super::super::super::exports::tegmentum::i18n_linebreak::types::Locale;
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_supported_locales_cabi<T_: Guest>() -> *mut u8 {
                    unsafe {
                        #[cfg(target_arch = "wasm32")]
                        _rt::run_ctors_once();
                        let result0 = { T_::supported_locales() };
                        let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                        let vec3 = result0;
                        let len3 = vec3.len();
                        let layout3 = _rt::alloc::Layout::from_size_align(
                            vec3.len() * (2 * ::core::mem::size_of::<*const u8>()),
                            ::core::mem::size_of::<*const u8>(),
                        )
                        .unwrap();
                        let (result3, _cleanup3) = wit_bindgen_rt::Cleanup::new(layout3);
                        if let Some(cleanup) = _cleanup3 {
                            cleanup.forget();
                        }
                        for (i, e) in vec3.into_iter().enumerate() {
                            let base = result3.add(i * (2 * ::core::mem::size_of::<*const u8>()));
                            {
                                let vec2 = (e.into_bytes()).into_boxed_slice();
                                let ptr2 = vec2.as_ptr().cast::<u8>();
                                let len2 = vec2.len();
                                ::core::mem::forget(vec2);
                                *base
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<usize>() = len2;
                                *base.add(0).cast::<*mut u8>() = ptr2.cast_mut();
                            }
                        }
                        *ptr1
                            .add(::core::mem::size_of::<*const u8>())
                            .cast::<usize>() = len3;
                        *ptr1.add(0).cast::<*mut u8>() = result3;
                        ptr1
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_supported_locales<T_: Guest>(arg0: *mut u8) {
                    unsafe {
                        let l0 = *arg0.add(0).cast::<*mut u8>();
                        let l1 = *arg0
                            .add(::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let base4 = l0;
                        let len4 = l1;
                        for i in 0..len4 {
                            let base = base4.add(i * (2 * ::core::mem::size_of::<*const u8>()));
                            {
                                let l2 = *base.add(0).cast::<*mut u8>();
                                let l3 = *base
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                _rt::cabi_dealloc(l2, l3, 1);
                            }
                        }
                        _rt::cabi_dealloc(
                            base4,
                            len4 * (2 * ::core::mem::size_of::<*const u8>()),
                            ::core::mem::size_of::<*const u8>(),
                        );
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_supports_cabi<T_: Guest>(arg0: *mut u8, arg1: usize) -> i32 {
                    unsafe {
                        #[cfg(target_arch = "wasm32")]
                        _rt::run_ctors_once();
                        let result1 = {
                            let len0 = arg1;
                            let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                            T_::supports(_rt::string_lift(bytes0))
                        };
                        match result1 {
                            true => 1,
                            false => 0,
                        }
                    }
                }
                pub trait Guest {
                    /// Every BCP 47 tag this component's linked packs cover. Phase 5
                    /// ships the root-locale marker only.
                    #[allow(async_fn_in_trait)]
                    fn supported_locales() -> _rt::Vec<Locale>;
                    /// True iff a query in the given locale would use a locale-
                    /// specific pack. Phase 5 always falls through to the default;
                    /// returns `true` for every input for forward compatibility.
                    #[allow(async_fn_in_trait)]
                    fn supports(loc: Locale) -> bool;
                }
                #[doc(hidden)]

                macro_rules! __export_tegmentum_i18n_linebreak_capabilities_0_1_0_cabi{
  ($ty:ident with_types_in $($path_to_types:tt)*) => (const _: () = {

    #[unsafe(export_name = "tegmentum:i18n-linebreak/capabilities@0.1.0#supported-locales")]
    unsafe extern "C" fn export_supported_locales() -> *mut u8 {
      unsafe { $($path_to_types)*::_export_supported_locales_cabi::<$ty>() }
    }
    #[unsafe(export_name = "cabi_post_tegmentum:i18n-linebreak/capabilities@0.1.0#supported-locales")]
    unsafe extern "C" fn _post_return_supported_locales(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_supported_locales::<$ty>(arg0) }
    }
    #[unsafe(export_name = "tegmentum:i18n-linebreak/capabilities@0.1.0#supports")]
    unsafe extern "C" fn export_supports(arg0: *mut u8,arg1: usize,) -> i32 {
      unsafe { $($path_to_types)*::_export_supports_cabi::<$ty>(arg0, arg1) }
    }
  };);
}
                #[doc(hidden)]
                pub(crate) use __export_tegmentum_i18n_linebreak_capabilities_0_1_0_cabi;

                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<u8>; 2 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 2 * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
mod _rt {
    #![allow(dead_code, unused_imports, clippy::all)]
    pub use alloc_crate::string::String;

    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub use alloc_crate::vec::Vec;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            unsafe { String::from_utf8_unchecked(bytes) }
        }
    }

    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }

    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }

    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }

    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }

    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }

    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }

    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }

    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }

    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }

    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }

    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    pub use alloc_crate::alloc;
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        unsafe {
            let layout = alloc::Layout::from_size_align_unchecked(size, align);
            alloc::dealloc(ptr, layout);
        }
    }
    extern crate alloc as alloc_crate;
}

/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]

macro_rules! __export_linebreak_world_impl {
  ($ty:ident) => (self::export!($ty with_types_in self););
  ($ty:ident with_types_in $($path_to_types_root:tt)*) => (
  $($path_to_types_root)*::exports::tegmentum::i18n_linebreak::types::__export_tegmentum_i18n_linebreak_types_0_1_0_cabi!($ty with_types_in $($path_to_types_root)*::exports::tegmentum::i18n_linebreak::types);
  $($path_to_types_root)*::exports::tegmentum::i18n_linebreak::linebreak::__export_tegmentum_i18n_linebreak_linebreak_0_1_0_cabi!($ty with_types_in $($path_to_types_root)*::exports::tegmentum::i18n_linebreak::linebreak);
  $($path_to_types_root)*::exports::tegmentum::i18n_linebreak::capabilities::__export_tegmentum_i18n_linebreak_capabilities_0_1_0_cabi!($ty with_types_in $($path_to_types_root)*::exports::tegmentum::i18n_linebreak::capabilities);
  )
}
#[doc(inline)]
pub(crate) use __export_linebreak_world_impl as export;

#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.60.0:tegmentum:i18n-linebreak@0.1.0:linebreak-world:encoded world")]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 858] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xd4\x05\x01A\x02\x01\
A\x0a\x01B\x0a\x01s\x04\0\x06locale\x03\0\0\x01q\x02\x09mandatory\0\0\x07allowed\
\0\0\x04\0\x0abreak-kind\x03\0\x02\x01r\x02\x06offsety\x04kind\x03\x04\0\x11brea\
k-opportunity\x03\0\x04\x01m\x03\x05loose\x06normal\x06strict\x04\0\x15line-brea\
k-strictness\x03\0\x06\x01q\x01\x0einvalid-locale\x01s\0\x04\0\x0flinebreak-erro\
r\x03\0\x08\x04\0$tegmentum:i18n-linebreak/types@0.1.0\x05\0\x02\x03\0\0\x06loca\
le\x02\x03\0\0\x11break-opportunity\x02\x03\0\0\x15line-break-strictness\x02\x03\
\0\0\x0flinebreak-error\x01B\x0d\x02\x03\x02\x01\x01\x04\0\x06locale\x03\0\0\x02\
\x03\x02\x01\x02\x04\0\x11break-opportunity\x03\0\x02\x02\x03\x02\x01\x03\x04\0\x15\
line-break-strictness\x03\0\x04\x02\x03\x02\x01\x04\x04\0\x0flinebreak-error\x03\
\0\x06\x01p\x03\x01@\x01\x04texts\0\x08\x04\0\x0bfind-breaks\x01\x09\x01@\x02\x04\
texts\x0astrictness\x05\0\x08\x04\0\x1bfind-breaks-with-strictness\x01\x0a\x04\0\
(tegmentum:i18n-linebreak/linebreak@0.1.0\x05\x05\x01B\x07\x02\x03\x02\x01\x01\x04\
\0\x06locale\x03\0\0\x01p\x01\x01@\0\0\x02\x04\0\x11supported-locales\x01\x03\x01\
@\x01\x03loc\x01\0\x7f\x04\0\x08supports\x01\x04\x04\0+tegmentum:i18n-linebreak/\
capabilities@0.1.0\x05\x06\x04\0.tegmentum:i18n-linebreak/linebreak-world@0.1.0\x04\
\0\x0b\x15\x01\0\x0flinebreak-world\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\
\x0dwit-component\x070.254.0\x10wit-bindgen-rust\x060.60.0";

#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
