// Generated by `wit-bindgen` 0.60.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod tegmentum {
        pub mod i18n_segment {
            /// Shared types. Split into its own interface so the `segment` and
            /// `capabilities` interfaces can `use` the same definitions.
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod types {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() =
                    super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                /// BCP 47 locale tag: "en", "de", "fr", "ja-JP". The empty
                /// string denotes the CLDR root locale.
                pub type Locale = _rt::String;
                /// One word-level segmentation record.
                ///
                /// `start` and `end` are byte offsets into the input (both in
                /// `0..=len(input)`, with `start < end` unless the input is
                /// empty). `is-word-like` is true for segments that a caller
                /// would render as "a word" (letters, digits, joiners); false
                /// for punctuation runs and whitespace between words.
                #[repr(C)]
                #[derive(Clone, Copy)]
                pub struct WordSegment {
                    /// The inclusive UTF-8 byte offset where the segment starts.
                    pub start: u32,
                    /// The exclusive UTF-8 byte offset where the segment ends.
                    pub end: u32,
                    /// True for word-like segments (letters, digits, joiners);
                    /// false for punctuation-only or whitespace-only runs.
                    pub is_word_like: bool,
                }
                impl ::core::fmt::Debug for WordSegment {
                    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                        f.debug_struct("WordSegment")
                            .field("start", &self.start)
                            .field("end", &self.end)
                            .field("is-word-like", &self.is_word_like)
                            .finish()
                    }
                }
                #[doc(hidden)]
                macro_rules! __export_tegmentum_i18n_segment_types_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _: () = {};
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_tegmentum_i18n_segment_types_0_1_0_cabi;
            }
            /// The core segmentation surface.
            ///
            /// Every function takes an input string plus (for word / sentence)
            /// a locale tag, and returns a list of byte-offset boundaries or
            /// (word) segment records.
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod segment {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() =
                    super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type Locale =
                    super::super::super::super::exports::tegmentum::i18n_segment::types::Locale;
                pub type WordSegment = super::super::super::super::exports::tegmentum::i18n_segment::types::WordSegment;
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_segment_graphemes_cabi<T_: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) -> *mut u8 {
                    unsafe {
                        #[cfg(target_arch = "wasm32")]
                        _rt::run_ctors_once();
                        let result1 = {
                            let len0 = arg1;
                            let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                            T_::segment_graphemes(_rt::string_lift(bytes0))
                        };
                        let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                        let vec3 = <_ as Into<_rt::Vec<_>>>::into(result1).into_boxed_slice();
                        let ptr3 = vec3.as_ptr().cast::<u8>();
                        let len3 = vec3.len();
                        ::core::mem::forget(vec3);
                        *ptr2
                            .add(::core::mem::size_of::<*const u8>())
                            .cast::<usize>() = len3;
                        *ptr2.add(0).cast::<*mut u8>() = ptr3.cast_mut();
                        ptr2
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_segment_graphemes<T_: Guest>(arg0: *mut u8) {
                    unsafe {
                        let l0 = *arg0.add(0).cast::<*mut u8>();
                        let l1 = *arg0
                            .add(::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let base2 = l0;
                        let len2 = l1;
                        _rt::cabi_dealloc(base2, len2 * 4, 4);
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_segment_words_cabi<T_: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                ) -> *mut u8 {
                    unsafe {
                        #[cfg(target_arch = "wasm32")]
                        _rt::run_ctors_once();
                        let result2 = {
                            let len0 = arg1;
                            let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                            let len1 = arg3;
                            let bytes1 = _rt::Vec::from_raw_parts(arg2.cast(), len1, len1);
                            T_::segment_words(_rt::string_lift(bytes0), _rt::string_lift(bytes1))
                        };
                        let ptr3 = (&raw mut _RET_AREA.0).cast::<u8>();
                        let vec5 = result2;
                        let len5 = vec5.len();
                        let layout5 =
                            _rt::alloc::Layout::from_size_align(vec5.len() * 12, 4).unwrap();
                        let (result5, _cleanup5) = wit_bindgen_rt::Cleanup::new(layout5);
                        if let Some(cleanup) = _cleanup5 {
                            cleanup.forget();
                        }
                        for (i, e) in vec5.into_iter().enumerate() {
                            let base = result5.add(i * 12);
                            {
                                let super::super::super::super::exports::tegmentum::i18n_segment::types::WordSegment {
                                    start: start4,
                                    end: end4,
                                    is_word_like: is_word_like4,
                                } = e;
                                *base.add(0).cast::<i32>() = _rt::as_i32(start4);
                                *base.add(4).cast::<i32>() = _rt::as_i32(end4);
                                *base.add(8).cast::<u8>() = (match is_word_like4 {
                                    true => 1,
                                    false => 0,
                                })
                                    as u8;
                            }
                        }
                        *ptr3
                            .add(::core::mem::size_of::<*const u8>())
                            .cast::<usize>() = len5;
                        *ptr3.add(0).cast::<*mut u8>() = result5;
                        ptr3
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_segment_words<T_: Guest>(arg0: *mut u8) {
                    unsafe {
                        let l0 = *arg0.add(0).cast::<*mut u8>();
                        let l1 = *arg0
                            .add(::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let base2 = l0;
                        let len2 = l1;
                        _rt::cabi_dealloc(base2, len2 * 12, 4);
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_segment_sentences_cabi<T_: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                ) -> *mut u8 {
                    unsafe {
                        #[cfg(target_arch = "wasm32")]
                        _rt::run_ctors_once();
                        let result2 = {
                            let len0 = arg1;
                            let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                            let len1 = arg3;
                            let bytes1 = _rt::Vec::from_raw_parts(arg2.cast(), len1, len1);
                            T_::segment_sentences(
                                _rt::string_lift(bytes0),
                                _rt::string_lift(bytes1),
                            )
                        };
                        let ptr3 = (&raw mut _RET_AREA.0).cast::<u8>();
                        let vec4 = <_ as Into<_rt::Vec<_>>>::into(result2).into_boxed_slice();
                        let ptr4 = vec4.as_ptr().cast::<u8>();
                        let len4 = vec4.len();
                        ::core::mem::forget(vec4);
                        *ptr3
                            .add(::core::mem::size_of::<*const u8>())
                            .cast::<usize>() = len4;
                        *ptr3.add(0).cast::<*mut u8>() = ptr4.cast_mut();
                        ptr3
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_segment_sentences<T_: Guest>(arg0: *mut u8) {
                    unsafe {
                        let l0 = *arg0.add(0).cast::<*mut u8>();
                        let l1 = *arg0
                            .add(::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let base2 = l0;
                        let len2 = l1;
                        _rt::cabi_dealloc(base2, len2 * 4, 4);
                    }
                }
                pub trait Guest {
                    /// Grapheme-cluster boundaries per UAX #29 § 3.
                    ///
                    /// Returns a strictly-increasing list of UTF-8 byte offsets. The
                    /// first entry is always `0` and the last is always the input's
                    /// byte length; the interstitial entries are cluster boundaries.
                    /// Two consecutive entries `boundaries[i]` and `boundaries[i +
                    /// 1]` delimit one grapheme.
                    ///
                    /// The function is locale-neutral — UAX #29 grapheme rules are
                    /// language-independent.
                    #[allow(async_fn_in_trait)]
                    fn segment_graphemes(text: _rt::String) -> _rt::Vec<u32>;
                    /// Word segments per UAX #29 § 4.
                    ///
                    /// Returns a list of `word-segment` records covering the whole
                    /// input contiguously; the `start` of the first record is `0`
                    /// and the `end` of the last is `len(text)`. Callers who want
                    /// only word-like segments filter on `is-word-like`.
                    ///
                    /// The `locale` argument is accepted for forward compatibility
                    /// with per-locale tailorings; Phase 5 applies the UAX #29
                    /// default rules regardless of the tag.
                    #[allow(async_fn_in_trait)]
                    fn segment_words(text: _rt::String, locale: Locale) -> _rt::Vec<WordSegment>;
                    /// Sentence boundaries per UAX #29 § 5.
                    ///
                    /// Returns a strictly-increasing list of UTF-8 byte offsets in
                    /// the same shape as `segment-graphemes`: leading `0`, trailing
                    /// `len(text)`, one boundary between each pair of sentences.
                    ///
                    /// The `locale` argument is accepted for forward compatibility
                    /// with per-locale tailorings; Phase 5 applies the UAX #29
                    /// default rules regardless of the tag.
                    #[allow(async_fn_in_trait)]
                    fn segment_sentences(text: _rt::String, locale: Locale) -> _rt::Vec<u32>;
                }
                #[doc(hidden)]
                macro_rules! __export_tegmentum_i18n_segment_segment_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "tegmentum:i18n-segment/segment@0.1.0#segment-graphemes")] unsafe
                        extern "C" fn export_segment_graphemes(arg0 : * mut u8, arg1 :
                        usize,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_segment_graphemes_cabi::<$ty > (arg0, arg1) } } #[unsafe
                        (export_name =
                        "cabi_post_tegmentum:i18n-segment/segment@0.1.0#segment-graphemes")]
                        unsafe extern "C" fn _post_return_segment_graphemes(arg0 : * mut
                        u8,) { unsafe { $($path_to_types)*::
                        __post_return_segment_graphemes::<$ty > (arg0) } } #[unsafe
                        (export_name =
                        "tegmentum:i18n-segment/segment@0.1.0#segment-words")] unsafe
                        extern "C" fn export_segment_words(arg0 : * mut u8, arg1 : usize,
                        arg2 : * mut u8, arg3 : usize,) -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_segment_words_cabi::<$ty > (arg0,
                        arg1, arg2, arg3) } } #[unsafe (export_name =
                        "cabi_post_tegmentum:i18n-segment/segment@0.1.0#segment-words")]
                        unsafe extern "C" fn _post_return_segment_words(arg0 : * mut u8,)
                        { unsafe { $($path_to_types)*:: __post_return_segment_words::<$ty
                        > (arg0) } } #[unsafe (export_name =
                        "tegmentum:i18n-segment/segment@0.1.0#segment-sentences")] unsafe
                        extern "C" fn export_segment_sentences(arg0 : * mut u8, arg1 :
                        usize, arg2 : * mut u8, arg3 : usize,) -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_segment_sentences_cabi::<$ty >
                        (arg0, arg1, arg2, arg3) } } #[unsafe (export_name =
                        "cabi_post_tegmentum:i18n-segment/segment@0.1.0#segment-sentences")]
                        unsafe extern "C" fn _post_return_segment_sentences(arg0 : * mut
                        u8,) { unsafe { $($path_to_types)*::
                        __post_return_segment_sentences::<$ty > (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_tegmentum_i18n_segment_segment_0_1_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<u8>; 2 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 2 * ::core::mem::size_of::<*const u8>()],
                );
            }
            /// Introspection: which locales does the linked component actually
            /// cover?
            ///
            /// Phase 5 ships a single locale-neutral default pack; the returned
            /// list carries the root-locale marker `""` and nothing else. Future
            /// phases populating per-locale tailorings will grow this list.
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod capabilities {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() =
                    super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type Locale =
                    super::super::super::super::exports::tegmentum::i18n_segment::types::Locale;
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_supported_locales_cabi<T_: Guest>() -> *mut u8 {
                    unsafe {
                        #[cfg(target_arch = "wasm32")]
                        _rt::run_ctors_once();
                        let result0 = { T_::supported_locales() };
                        let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                        let vec3 = result0;
                        let len3 = vec3.len();
                        let layout3 = _rt::alloc::Layout::from_size_align(
                            vec3.len() * (2 * ::core::mem::size_of::<*const u8>()),
                            ::core::mem::size_of::<*const u8>(),
                        )
                        .unwrap();
                        let (result3, _cleanup3) = wit_bindgen_rt::Cleanup::new(layout3);
                        if let Some(cleanup) = _cleanup3 {
                            cleanup.forget();
                        }
                        for (i, e) in vec3.into_iter().enumerate() {
                            let base = result3.add(i * (2 * ::core::mem::size_of::<*const u8>()));
                            {
                                let vec2 = (e.into_bytes()).into_boxed_slice();
                                let ptr2 = vec2.as_ptr().cast::<u8>();
                                let len2 = vec2.len();
                                ::core::mem::forget(vec2);
                                *base
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<usize>() = len2;
                                *base.add(0).cast::<*mut u8>() = ptr2.cast_mut();
                            }
                        }
                        *ptr1
                            .add(::core::mem::size_of::<*const u8>())
                            .cast::<usize>() = len3;
                        *ptr1.add(0).cast::<*mut u8>() = result3;
                        ptr1
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_supported_locales<T_: Guest>(arg0: *mut u8) {
                    unsafe {
                        let l0 = *arg0.add(0).cast::<*mut u8>();
                        let l1 = *arg0
                            .add(::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let base4 = l0;
                        let len4 = l1;
                        for i in 0..len4 {
                            let base = base4.add(i * (2 * ::core::mem::size_of::<*const u8>()));
                            {
                                let l2 = *base.add(0).cast::<*mut u8>();
                                let l3 = *base
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                _rt::cabi_dealloc(l2, l3, 1);
                            }
                        }
                        _rt::cabi_dealloc(
                            base4,
                            len4 * (2 * ::core::mem::size_of::<*const u8>()),
                            ::core::mem::size_of::<*const u8>(),
                        );
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_supports_cabi<T_: Guest>(arg0: *mut u8, arg1: usize) -> i32 {
                    unsafe {
                        #[cfg(target_arch = "wasm32")]
                        _rt::run_ctors_once();
                        let result1 = {
                            let len0 = arg1;
                            let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                            T_::supports(_rt::string_lift(bytes0))
                        };
                        match result1 {
                            true => 1,
                            false => 0,
                        }
                    }
                }
                pub trait Guest {
                    /// Every BCP 47 tag this component's linked packs cover. Phase 5
                    /// ships the root-locale marker only.
                    #[allow(async_fn_in_trait)]
                    fn supported_locales() -> _rt::Vec<Locale>;
                    /// True iff a query in the given locale would use a locale-
                    /// specific pack (rather than falling through to the default).
                    /// Phase 5 always uses the default; this function returns `true`
                    /// for every input for forward compatibility with future
                    /// tailorings.
                    #[allow(async_fn_in_trait)]
                    fn supports(loc: Locale) -> bool;
                }
                #[doc(hidden)]
                macro_rules! __export_tegmentum_i18n_segment_capabilities_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "tegmentum:i18n-segment/capabilities@0.1.0#supported-locales")]
                        unsafe extern "C" fn export_supported_locales() -> * mut u8 {
                        unsafe { $($path_to_types)*::
                        _export_supported_locales_cabi::<$ty > () } } #[unsafe
                        (export_name =
                        "cabi_post_tegmentum:i18n-segment/capabilities@0.1.0#supported-locales")]
                        unsafe extern "C" fn _post_return_supported_locales(arg0 : * mut
                        u8,) { unsafe { $($path_to_types)*::
                        __post_return_supported_locales::<$ty > (arg0) } } #[unsafe
                        (export_name =
                        "tegmentum:i18n-segment/capabilities@0.1.0#supports")] unsafe
                        extern "C" fn export_supports(arg0 : * mut u8, arg1 : usize,) ->
                        i32 { unsafe { $($path_to_types)*:: _export_supports_cabi::<$ty >
                        (arg0, arg1) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_tegmentum_i18n_segment_capabilities_0_1_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<u8>; 2 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 2 * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, unused_imports, clippy::all)]
    pub use alloc_crate::string::String;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub use alloc_crate::vec::Vec;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            unsafe { String::from_utf8_unchecked(bytes) }
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        unsafe {
            let layout = alloc::Layout::from_size_align_unchecked(size, align);
            alloc::dealloc(ptr, layout);
        }
    }
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    pub use alloc_crate::alloc;
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_segment_world_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::tegmentum::i18n_segment::types::__export_tegmentum_i18n_segment_types_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::tegmentum::i18n_segment::types);
        $($path_to_types_root)*::
        exports::tegmentum::i18n_segment::segment::__export_tegmentum_i18n_segment_segment_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*::
        exports::tegmentum::i18n_segment::segment); $($path_to_types_root)*::
        exports::tegmentum::i18n_segment::capabilities::__export_tegmentum_i18n_segment_capabilities_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*::
        exports::tegmentum::i18n_segment::capabilities);
    };
}
#[doc(inline)]
pub(crate) use __export_segment_world_impl as export;
#[rustfmt::skip]
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.60.0:tegmentum:i18n-segment@0.1.0:segment-world:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 718] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xca\x04\x01A\x02\x01\
A\x09\x01B\x06\x01s\x04\0\x06locale\x03\0\0\x01r\x03\x05starty\x03endy\x0cis-wor\
d-like\x7f\x04\0\x0cword-segment\x03\0\x02\x01q\x01\x0einvalid-locale\x01s\0\x04\
\0\x0dsegment-error\x03\0\x04\x04\0\"tegmentum:i18n-segment/types@0.1.0\x05\0\x02\
\x03\0\0\x06locale\x02\x03\0\0\x0cword-segment\x02\x03\0\0\x0dsegment-error\x01B\
\x0e\x02\x03\x02\x01\x01\x04\0\x06locale\x03\0\0\x02\x03\x02\x01\x02\x04\0\x0cwo\
rd-segment\x03\0\x02\x02\x03\x02\x01\x03\x04\0\x0dsegment-error\x03\0\x04\x01py\x01\
@\x01\x04texts\0\x06\x04\0\x11segment-graphemes\x01\x07\x01p\x03\x01@\x02\x04tex\
ts\x06locale\x01\0\x08\x04\0\x0dsegment-words\x01\x09\x01@\x02\x04texts\x06local\
e\x01\0\x06\x04\0\x11segment-sentences\x01\x0a\x04\0$tegmentum:i18n-segment/segm\
ent@0.1.0\x05\x04\x01B\x07\x02\x03\x02\x01\x01\x04\0\x06locale\x03\0\0\x01p\x01\x01\
@\0\0\x02\x04\0\x11supported-locales\x01\x03\x01@\x01\x03loc\x01\0\x7f\x04\0\x08\
supports\x01\x04\x04\0)tegmentum:i18n-segment/capabilities@0.1.0\x05\x05\x04\0*t\
egmentum:i18n-segment/segment-world@0.1.0\x04\0\x0b\x13\x01\0\x0dsegment-world\x03\
\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.254.0\x10wit-\
bindgen-rust\x060.60.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
