//! Wasmtime smoke test for the reference
//! `stringcheese:icu-collation@0.1.0` component.
//!
//! Verifies WIT-i18n Phase 2's deferred "componentised WASM build"
//! bit (`docs/design/wit-i18n.md` § 8.2). The test drives the
//! component the same way any external caller would: builds it
//! under `wasm32-wasip1 --features wit-component`, componentises
//! it via `wasm-tools`, then loads the componentised `.wasm` into
//! an in-process wasmtime `Engine` and calls each of the WIT
//! exports (`compare`, `sort-key`, `get-capabilities`, `supports`)
//! through typed bindings generated by
//! `wasmtime::component::bindgen!` from the shipped WIT file.
//! Assertions are on the returned Rust values.
//!
//! # Prerequisites
//!
//! Requires two tools on `$PATH`:
//!
//! * `cargo` with the `wasm32-wasip1` target installed
//! * `wasm-tools` (Bytecode Alliance) — used only for
//!   `component new` to produce the component encoding from the
//!   plain wasm module.
//!
//! Plus one file on disk — the WASI preview1 → preview2 reactor
//! adapter — discoverable via the search order documented in
//! [`find_wasi_adapter`]. The adapter version must match the
//! wasmtime crate version (both 26.x on CI); a version mismatch
//! surfaces as an import-mismatch panic at `Linker::instantiate`
//! time.
//!
//! When any of these prerequisites is missing the test soft-skips
//! with a diagnostic — matching the "conformance runner"
//! convention used by `stringcheese-tokenizer-hf`'s real-vocab
//! tests and `stringcheese-icu-case-component`'s smoke. This
//! keeps host `cargo test` green on developer machines that
//! haven't installed the wasm toolchain; CI installs both tools
//! and downloads the version-matched adapter explicitly (see the
//! `wasm-i18n-collation-component` job).
//!
//! # Why the wasmtime crate instead of `wasmtime run --invoke`
//!
//! Same rationale as `stringcheese-icu-case-component`'s smoke:
//! wasmtime 20+ removed `--invoke` for components (only core
//! modules retain it). The rewrite embeds wasmtime as a dev-dep
//! and calls the exports through the typed bindings the
//! `bindgen!` macro produces from
//! `component/wit/collation/stringcheese-icu-collation.wit`.

#![cfg(not(target_family = "wasm"))]
#![allow(unsafe_code)]

use std::path::PathBuf;
use std::process::Command;
use std::sync::OnceLock;

use wasmtime::component::{Component, Linker, ResourceTable};
use wasmtime::{Engine, Store};
use wasmtime_wasi::{WasiCtx, WasiCtxBuilder, WasiView};

// Typed bindings generated from the shipped WIT contract. The
// macro mirrors the `collation-world` world the guest crate
// exports, but from the host side — the generated
// `CollationWorld` struct is what we instantiate against a
// linker below, and its `stringcheese_icu_collation_*()`
// accessors return typed handles to the exported interfaces. The
// macro expansion emits several items without doc comments;
// wrapping in a module lets us scope a single
// `#[allow(missing_docs)]` around the generated code.
#[allow(missing_docs, clippy::pedantic, clippy::nursery)]
mod bindgen {
    wasmtime::component::bindgen!({
        world: "collation-world",
        path: "../../component/wit/collation",
    });
}

use bindgen::CollationWorld;
use bindgen::exports::stringcheese::icu_collation::types::CollationError as WitCollationError;
use bindgen::exports::stringcheese::icu_collation::types::CollationStrength as WitStrength;
use bindgen::exports::stringcheese::icu_collation::types::Ordering as WitOrdering;

/// Host state carried in the `Store<T>`. Holds the WASI preview2
/// context and a `ResourceTable` for any WASI resources
/// instantiated during a call. The collation component never
/// touches either — it performs no I/O — but a `WasiView` impl
/// is still required so the linker can wire the imported
/// `wasi:*` interfaces exposed by the wasip1 → wasip2 adapter.
struct HostState {
    table: ResourceTable,
    wasi: WasiCtx,
}

impl WasiView for HostState {
    fn ctx(&mut self) -> &mut WasiCtx {
        &mut self.wasi
    }
    fn table(&mut self) -> &mut ResourceTable {
        &mut self.table
    }
}

/// One end-to-end build-and-load: shell out to `cargo build` +
/// `wasm-tools component new` once, load the resulting `.wasm`
/// into a wasmtime `Engine`, and cache the immutable
/// engine/component/linker on the shared `OnceLock` so every test
/// instantiates cheaply.
struct SmokeHarness {
    engine: Engine,
    component: Component,
    linker: Linker<HostState>,
}

/// The smoke tests run concurrently under `cargo test`'s default
/// thread pool. Each calls `SmokeHarness::build_or_skip`; without
/// a guard the threads would race on the same
/// `target/wasm32-wasip1/release/` directory and `wasm-tools`
/// output path, producing spurious failures when one test's
/// componentise step reads a wasm the other is still writing.
/// This `OnceLock<Option<PathBuf>>` serialises the build-once,
/// componentise-once step across every caller — subsequent
/// invocations get back the cached component path (or the cached
/// skip decision) without re-invoking cargo / wasm-tools.
static SHARED_COMPONENT: OnceLock<Option<PathBuf>> = OnceLock::new();

impl SmokeHarness {
    fn build_or_skip() -> Option<Self> {
        let component_wasm = SHARED_COMPONENT
            .get_or_init(Self::build_shared_once)
            .clone()?;

        let engine = Engine::default();
        let component = match Component::from_file(&engine, &component_wasm) {
            Ok(c) => c,
            Err(e) => {
                eprintln!(
                    "SKIP: wasmtime failed to load component at {}: {e}",
                    component_wasm.display()
                );
                return None;
            }
        };
        let mut linker: Linker<HostState> = Linker::new(&engine);
        if let Err(e) = wasmtime_wasi::add_to_linker_sync(&mut linker) {
            eprintln!("SKIP: could not add WASI to linker: {e}");
            return None;
        }
        Some(Self {
            engine,
            component,
            linker,
        })
    }

    fn build_shared_once() -> Option<PathBuf> {
        if !has_tool("cargo") {
            eprintln!("SKIP: cargo not on PATH");
            return None;
        }
        if !has_tool("wasm-tools") {
            eprintln!(
                "SKIP: wasm-tools not on PATH — install from https://github.com/bytecodealliance/wasm-tools"
            );
            return None;
        }
        if !target_installed("wasm32-wasip1") {
            eprintln!(
                "SKIP: wasm32-wasip1 target not installed — `rustup target add wasm32-wasip1`"
            );
            return None;
        }

        let workspace_root = workspace_root();
        let build = Command::new("cargo")
            .current_dir(&workspace_root)
            .args([
                "build",
                "-p",
                "stringcheese-icu-collation-component",
                "--target",
                "wasm32-wasip1",
                "--features",
                "wit-component",
                "--release",
            ])
            .status()
            .expect("cargo build must launch");
        assert!(
            build.success(),
            "cargo build for wasm32-wasip1 must succeed",
        );

        let module_wasm = workspace_root
            .join("target/wasm32-wasip1/release/stringcheese_icu_collation_component.wasm");
        assert!(
            module_wasm.exists(),
            "expected wasm at {} after cargo build",
            module_wasm.display(),
        );

        let Some(adapter) = find_wasi_adapter() else {
            eprintln!(
                "SKIP: no wasi_snapshot_preview1.reactor.wasm adapter found on the search path"
            );
            return None;
        };

        // Componentize.
        let component_wasm = std::env::temp_dir().join("stringcheese_icu_collation_component.wasm");
        let componentize = Command::new("wasm-tools")
            .args([
                "component",
                "new",
                module_wasm.to_str().expect("path is utf8"),
                "--adapt",
                adapter.to_str().expect("adapter path is utf8"),
                "-o",
                component_wasm.to_str().expect("output path is utf8"),
            ])
            .status()
            .expect("wasm-tools must launch");
        assert!(
            componentize.success(),
            "wasm-tools component new must succeed",
        );
        assert!(
            component_wasm.exists(),
            "expected component at {}",
            component_wasm.display(),
        );
        Some(component_wasm)
    }

    /// Instantiate the component in a fresh `Store`. Each test
    /// owns its own store; instantiation is cheap once the
    /// component is compiled and the linker is populated.
    fn instantiate(&self) -> (Store<HostState>, CollationWorld) {
        let mut store = Store::new(
            &self.engine,
            HostState {
                table: ResourceTable::new(),
                wasi: WasiCtxBuilder::new().build(),
            },
        );
        let bindings = CollationWorld::instantiate(&mut store, &self.component, &self.linker)
            .expect("component must instantiate against the wasmtime-wasi linker");
        (store, bindings)
    }
}

fn has_tool(name: &str) -> bool {
    Command::new(name)
        .arg("--version")
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status()
        .is_ok_and(|s| s.success())
}

fn target_installed(triple: &str) -> bool {
    let out = Command::new("rustup")
        .args(["target", "list", "--installed"])
        .output();
    match out {
        Ok(o) if o.status.success() => String::from_utf8_lossy(&o.stdout)
            .lines()
            .any(|l| l.trim() == triple),
        _ => true,
    }
}

fn workspace_root() -> PathBuf {
    // CARGO_MANIFEST_DIR is
    // `crates/stringcheese-icu-collation-component`; walk up two
    // levels to reach the workspace root.
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    manifest
        .parent()
        .and_then(|p| p.parent())
        .expect("workspace root is two levels above crate manifest")
        .to_path_buf()
}

fn find_wasi_adapter() -> Option<PathBuf> {
    // Search order mirrors `stringcheese-icu-case-component`'s.
    //   1. `STRINGCHEESE_WASI_ADAPTER` environment variable — the
    //      CI job sets this to the adapter it downloads into
    //      `$RUNNER_TEMP`.
    //   2. `~/.cache/stringcheese-tokenizer-component/wasi_snapshot_preview1.reactor.wasm`
    //      — a shared developer cache (reused across every
    //      component crate so the one-time download does not
    //      need to be repeated).
    //   3. Any `wasi_snapshot_preview1.reactor.wasm` under
    //      `~/.cargo/registry/src/*/cargo-component/`.
    if let Ok(p) = std::env::var("STRINGCHEESE_WASI_ADAPTER") {
        let path = PathBuf::from(p);
        if path.exists() {
            return Some(path);
        }
    }
    let home = std::env::var_os("HOME").map(PathBuf::from)?;
    let cache =
        home.join(".cache/stringcheese-tokenizer-component/wasi_snapshot_preview1.reactor.wasm");
    if cache.exists() {
        return Some(cache);
    }
    walk_for_adapter(&home.join(".cargo/registry/src")).next()
}

fn walk_for_adapter(root: &std::path::Path) -> impl Iterator<Item = PathBuf> {
    let mut out = Vec::new();
    if let Ok(entries) = std::fs::read_dir(root) {
        for entry in entries.flatten() {
            let path = entry.path();
            let candidate = path.join("cargo-component/wasi_snapshot_preview1.reactor.wasm");
            if candidate.exists() {
                out.push(candidate);
            }
        }
    }
    out.into_iter()
}

/// Format the WIT-side `collation-error` variant for a compact
/// panic message when a `Result` returned by an export
/// unexpectedly carries an error. The generated
/// `WitCollationError` type has no stable `Display` impl; the
/// per-arm rendering here keeps the failure message readable
/// when a regression flips a happy-path call into the error
/// tail.
fn describe_err(e: &WitCollationError) -> String {
    match e {
        WitCollationError::InvalidLocale(s) => format!("invalid-locale({s:?})"),
        WitCollationError::LocaleUnavailable(s) => format!("locale-unavailable({s:?})"),
        WitCollationError::UnsupportedStrength(s) => format!("unsupported-strength({s:?})"),
    }
}

/// Helper — the WIT `type locale = string` alias is rendered as
/// an owned `String` by `wasmtime::component::bindgen!` (aliased
/// primitive types cross the ABI boundary as their concrete Rust
/// type, not `&str`), so every call-site that names a locale
/// needs an owned `String`. Centralising the small allocation
/// keeps the individual tests readable.
fn loc(tag: &str) -> String {
    tag.to_string()
}

#[test]
fn wasmtime_smoke_compare_apple_less_than_banana_primary() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let collation = bindings.stringcheese_icu_collation_collation();
    let ord = collation
        .call_compare(
            &mut store,
            "apple",
            "banana",
            &loc("en"),
            WitStrength::Primary,
        )
        .expect("compare trap-free")
        .unwrap_or_else(|e| panic!("compare returned error: {}", describe_err(&e)));
    assert!(
        matches!(ord, WitOrdering::Less),
        "apple < banana at primary should be Less, got {ord:?}"
    );
}

#[test]
fn wasmtime_smoke_compare_case_insensitive_at_primary() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let collation = bindings.stringcheese_icu_collation_collation();
    let ord = collation
        .call_compare(
            &mut store,
            "APPLE",
            "apple",
            &loc("en"),
            WitStrength::Primary,
        )
        .expect("compare trap-free")
        .unwrap_or_else(|e| panic!("compare returned error: {}", describe_err(&e)));
    assert!(
        matches!(ord, WitOrdering::Equal),
        "APPLE == apple at primary should be Equal, got {ord:?}"
    );
}

#[test]
fn wasmtime_smoke_compare_german_phonebook_bar_equals_baer() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let collation = bindings.stringcheese_icu_collation_collation();
    // Bär → Baer under DE phonebook (ä → ae expansion); at
    // tertiary the two compare Equal.
    let ord = collation
        .call_compare(&mut store, "Bär", "Baer", &loc("de"), WitStrength::Tertiary)
        .expect("compare trap-free")
        .unwrap_or_else(|e| panic!("compare returned error: {}", describe_err(&e)));
    assert!(
        matches!(ord, WitOrdering::Equal),
        "Bär == Baer under DE phonebook at tertiary should be Equal, got {ord:?}"
    );
}

#[test]
fn wasmtime_smoke_compare_german_phonebook_sharp_s_expands() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let collation = bindings.stringcheese_icu_collation_collation();
    // ß → ss under DE phonebook: Straße == Strasse at tertiary.
    let ord = collation
        .call_compare(
            &mut store,
            "Straße",
            "Strasse",
            &loc("de"),
            WitStrength::Tertiary,
        )
        .expect("compare trap-free")
        .unwrap_or_else(|e| panic!("compare returned error: {}", describe_err(&e)));
    assert!(
        matches!(ord, WitOrdering::Equal),
        "Straße == Strasse under DE phonebook at tertiary should be Equal, got {ord:?}"
    );
}

#[test]
fn wasmtime_smoke_sort_key_monotonic_agrees_with_compare() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let collation = bindings.stringcheese_icu_collation_collation();
    // A small set of DE inputs where sort-key ordering should
    // agree with compare at tertiary — same predicate the
    // native `sort_key_compares_consistently_with_compare` test
    // covers.
    let strings = ["apple", "Baer", "Bär", "Muller", "Munk", "Straße"];
    for pair in strings.windows(2) {
        let a = pair[0];
        let b = pair[1];
        let ka = collation
            .call_sort_key(&mut store, a, &loc("de"), WitStrength::Tertiary)
            .expect("sort-key trap-free")
            .unwrap_or_else(|e| panic!("sort-key returned error: {}", describe_err(&e)));
        let kb = collation
            .call_sort_key(&mut store, b, &loc("de"), WitStrength::Tertiary)
            .expect("sort-key trap-free")
            .unwrap_or_else(|e| panic!("sort-key returned error: {}", describe_err(&e)));
        let key_ord = ka.cmp(&kb);
        let cmp_ord = collation
            .call_compare(&mut store, a, b, &loc("de"), WitStrength::Tertiary)
            .expect("compare trap-free")
            .unwrap_or_else(|e| panic!("compare returned error: {}", describe_err(&e)));
        let cmp_ord_std = match cmp_ord {
            WitOrdering::Less => std::cmp::Ordering::Less,
            WitOrdering::Equal => std::cmp::Ordering::Equal,
            WitOrdering::Greater => std::cmp::Ordering::Greater,
        };
        assert_eq!(
            key_ord, cmp_ord_std,
            "sort-key vs compare disagreed for ({a:?}, {b:?}) at tertiary",
        );
    }
}

#[test]
fn wasmtime_smoke_supported_locales_lists_bundled_tags() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let caps = bindings.stringcheese_icu_collation_capabilities();
    let record = caps
        .call_get_capabilities(&mut store)
        .expect("get-capabilities trap-free");
    assert_eq!(
        record.supported_locales,
        vec![
            "en".to_string(),
            "de".to_string(),
            "fr".to_string(),
            "tr".to_string(),
            "ru".to_string(),
            "zh".to_string(),
        ],
    );
    assert!(
        matches!(record.max_strength, WitStrength::Identical),
        "max strength should be Identical, got {:?}",
        record.max_strength,
    );
    assert_eq!(record.cldr_version, "44.1");
}

// -----------------------------------------------------------------------
// Phase 6: per-locale smoke tests for the four new packs
// (fr, tr, ru, zh). Two smokes per locale.
// -----------------------------------------------------------------------

#[test]
fn wasmtime_smoke_compare_french_primary_ordering() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let collation = bindings.stringcheese_icu_collation_collation();
    let ord = collation
        .call_compare(
            &mut store,
            "apple",
            "banana",
            &loc("fr"),
            WitStrength::Primary,
        )
        .expect("compare trap-free")
        .unwrap_or_else(|e| panic!("compare returned error: {}", describe_err(&e)));
    assert!(
        matches!(ord, WitOrdering::Less),
        "apple < banana at primary under fr should be Less, got {ord:?}"
    );
}

#[test]
fn wasmtime_smoke_compare_french_supports_falls_back_to_root() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let caps = bindings.stringcheese_icu_collation_capabilities();
    // fr-CA is not registered directly, but falls back to fr.
    let ok = caps
        .call_supports(&mut store, &loc("fr-CA"))
        .expect("supports trap-free");
    assert!(ok, "fr-CA should resolve via BCP 47 fallback to fr");
}

#[test]
fn wasmtime_smoke_compare_turkish_ascii_primary() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let collation = bindings.stringcheese_icu_collation_collation();
    // Standard ASCII primary ordering under the tr locale — the
    // primary-distinct dotless-ı ordering is a documented Phase 6
    // deferral so `ı` and `i` compare primary-equal for now.
    let ord = collation
        .call_compare(&mut store, "a", "b", &loc("tr"), WitStrength::Primary)
        .expect("compare trap-free")
        .unwrap_or_else(|e| panic!("compare returned error: {}", describe_err(&e)));
    assert!(
        matches!(ord, WitOrdering::Less),
        "a < b at primary under tr should be Less, got {ord:?}"
    );
}

#[test]
fn wasmtime_smoke_compare_turkish_sharp_s_expansion_shared() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let collation = bindings.stringcheese_icu_collation_collation();
    // The tr pack ships the shared ß → ss expansion so a Turkish
    // text quoting a German loanword collates uniformly.
    let ord = collation
        .call_compare(
            &mut store,
            "Straße",
            "Strasse",
            &loc("tr"),
            WitStrength::Tertiary,
        )
        .expect("compare trap-free")
        .unwrap_or_else(|e| panic!("compare returned error: {}", describe_err(&e)));
    assert!(
        matches!(ord, WitOrdering::Equal),
        "Straße == Strasse under tr at tertiary should be Equal, got {ord:?}"
    );
}

#[test]
fn wasmtime_smoke_compare_russian_cyrillic_primary() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let collation = bindings.stringcheese_icu_collation_collation();
    // Cyrillic а < б at primary.
    let ord = collation
        .call_compare(&mut store, "а", "б", &loc("ru"), WitStrength::Primary)
        .expect("compare trap-free")
        .unwrap_or_else(|e| panic!("compare returned error: {}", describe_err(&e)));
    assert!(
        matches!(ord, WitOrdering::Less),
        "Cyrillic а < б at primary under ru should be Less, got {ord:?}"
    );
}

#[test]
fn wasmtime_smoke_compare_russian_word_primary() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let collation = bindings.stringcheese_icu_collation_collation();
    // Cyrillic word compare — Москва vs Санкт primary ordering.
    let ord = collation
        .call_compare(
            &mut store,
            "Москва",
            "Санкт",
            &loc("ru"),
            WitStrength::Primary,
        )
        .expect("compare trap-free")
        .unwrap_or_else(|e| panic!("compare returned error: {}", describe_err(&e)));
    assert!(
        matches!(ord, WitOrdering::Less),
        "Москва < Санкт at primary under ru should be Less, got {ord:?}"
    );
}

#[test]
fn wasmtime_smoke_compare_chinese_ascii_primary() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let collation = bindings.stringcheese_icu_collation_collation();
    // ASCII input under zh locale — the pinyin / stroke ordering is
    // a documented Phase 6 deferral so Han input falls back to
    // codepoint order and ASCII input follows UCA primary.
    let ord = collation
        .call_compare(
            &mut store,
            "apple",
            "banana",
            &loc("zh"),
            WitStrength::Primary,
        )
        .expect("compare trap-free")
        .unwrap_or_else(|e| panic!("compare returned error: {}", describe_err(&e)));
    assert!(
        matches!(ord, WitOrdering::Less),
        "apple < banana at primary under zh should be Less, got {ord:?}"
    );
}

#[test]
fn wasmtime_smoke_compare_chinese_han_primary() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let collation = bindings.stringcheese_icu_collation_collation();
    // Han input under zh locale falls back to codepoint order — 一
    // (U+4E00) < 二 (U+4E8C).
    let ord = collation
        .call_compare(&mut store, "一", "二", &loc("zh"), WitStrength::Primary)
        .expect("compare trap-free")
        .unwrap_or_else(|e| panic!("compare returned error: {}", describe_err(&e)));
    assert!(
        matches!(ord, WitOrdering::Less),
        "一 (U+4E00) < 二 (U+4E8C) at primary under zh should be Less, got {ord:?}"
    );
}

#[test]
fn wasmtime_smoke_supports_falls_through_bcp47_chain() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let caps = bindings.stringcheese_icu_collation_capabilities();
    // `de-CH` is not registered directly, but falls back to `de`.
    let ok = caps
        .call_supports(&mut store, &loc("de-CH"))
        .expect("supports trap-free");
    assert!(ok, "de-CH should resolve via BCP 47 fallback to de");
    // `xx` is not in the bundled pack set.
    let missing = caps
        .call_supports(&mut store, &loc("xx"))
        .expect("supports trap-free");
    assert!(!missing, "xx is not in the bundled pack set");
}
