// Generated by `wit-bindgen` 0.60.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod stringcheese {
        pub mod icu_collation {
            /// Shared types. Split into its own interface so the `collation`
            /// and `capabilities` interfaces can `use` the same definitions.
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod types {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() =
                    super::super::super::super::__link_custom_section_describing_imports;

                use super::super::super::super::_rt;
                /// BCP 47 locale tag: "en", "de", "pt-BR", "zh-Hant-HK".
                /// The empty string denotes the CLDR root locale — no
                /// tailoring (DUCET-only comparison).
                pub type Locale = _rt::String;
                /// Errors surfaced by the collation interface. UCA is total on
                /// valid Unicode input; failure modes are structural.
                #[derive(Clone)]
                pub enum CollationError {
                    /// The locale tag was not a well-formed BCP 47 tag.
                    /// Payload is the offending string.
                    InvalidLocale(_rt::String),
                    /// No pack was loaded for the requested locale and no
                    /// fallback in the CLDR chain resolved. Payload is the
                    /// tag that could not be resolved.
                    LocaleUnavailable(_rt::String),
                    /// The caller asked for a strength this component does
                    /// not implement. Payload is the strength name.
                    UnsupportedStrength(_rt::String),
                }
                impl ::core::fmt::Debug for CollationError {
                    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                        match self {
                            CollationError::InvalidLocale(e) => f
                                .debug_tuple("CollationError::InvalidLocale")
                                .field(e)
                                .finish(),
                            CollationError::LocaleUnavailable(e) => f
                                .debug_tuple("CollationError::LocaleUnavailable")
                                .field(e)
                                .finish(),
                            CollationError::UnsupportedStrength(e) => f
                                .debug_tuple("CollationError::UnsupportedStrength")
                                .field(e)
                                .finish(),
                        }
                    }
                }
                impl ::core::fmt::Display for CollationError {
                    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                        write!(f, "{:?}", self)
                    }
                }

                impl ::core::error::Error for CollationError {}
                /// The UCA strength level at which two strings are compared.
                /// See UTS #10 § 1.1 for the primary/secondary/tertiary/
                /// quaternary/identical breakdown.
                #[repr(u8)]
                #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
                pub enum CollationStrength {
                    /// Base characters only. `a = A = á = ä`.
                    Primary,
                    /// Base characters + diacritics. `a = A`, `a < á`.
                    Secondary,
                    /// Base characters + diacritics + case. `a < A < á`.
                    Tertiary,
                    /// Add variable-weight (punctuation) awareness.
                    Quaternary,
                    /// Full code-point tiebreak — bytewise equal iff equal.
                    Identical,
                }
                impl ::core::fmt::Debug for CollationStrength {
                    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                        match self {
                            CollationStrength::Primary => {
                                f.debug_tuple("CollationStrength::Primary").finish()
                            }
                            CollationStrength::Secondary => {
                                f.debug_tuple("CollationStrength::Secondary").finish()
                            }
                            CollationStrength::Tertiary => {
                                f.debug_tuple("CollationStrength::Tertiary").finish()
                            }
                            CollationStrength::Quaternary => {
                                f.debug_tuple("CollationStrength::Quaternary").finish()
                            }
                            CollationStrength::Identical => {
                                f.debug_tuple("CollationStrength::Identical").finish()
                            }
                        }
                    }
                }

                impl CollationStrength {
                    #[doc(hidden)]
                    pub unsafe fn _lift(val: u8) -> CollationStrength {
                        if !cfg!(debug_assertions) {
                            return unsafe { ::core::mem::transmute(val) };
                        }

                        match val {
                            0 => CollationStrength::Primary,
                            1 => CollationStrength::Secondary,
                            2 => CollationStrength::Tertiary,
                            3 => CollationStrength::Quaternary,
                            4 => CollationStrength::Identical,

                            _ => panic!("invalid enum discriminant"),
                        }
                    }
                }

                /// Wire encoding of `core::cmp::Ordering` for the WIT boundary.
                #[repr(u8)]
                #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
                pub enum Ordering {
                    /// The first operand sorts before the second.
                    Less,
                    /// The two operands compare equal at the requested strength.
                    Equal,
                    /// The first operand sorts after the second.
                    Greater,
                }
                impl ::core::fmt::Debug for Ordering {
                    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                        match self {
                            Ordering::Less => f.debug_tuple("Ordering::Less").finish(),
                            Ordering::Equal => f.debug_tuple("Ordering::Equal").finish(),
                            Ordering::Greater => f.debug_tuple("Ordering::Greater").finish(),
                        }
                    }
                }

                impl Ordering {
                    #[doc(hidden)]
                    pub unsafe fn _lift(val: u8) -> Ordering {
                        if !cfg!(debug_assertions) {
                            return unsafe { ::core::mem::transmute(val) };
                        }

                        match val {
                            0 => Ordering::Less,
                            1 => Ordering::Equal,
                            2 => Ordering::Greater,

                            _ => panic!("invalid enum discriminant"),
                        }
                    }
                }

                /// Introspection record returned by
                /// [`get-capabilities`](capabilities.get-capabilities).
                #[derive(Clone)]
                pub struct CapabilitiesRecord {
                    /// The BCP 47 locale tags this component's linked packs cover.
                    pub supported_locales: _rt::Vec<Locale>,
                    /// The maximum strength the component's algorithm reaches.
                    /// A pack that declines to implement quaternary / identical
                    /// distinctions still returns them; callers use this field
                    /// to warn if they need a deeper strength than the algorithm
                    /// promises.
                    pub max_strength: CollationStrength,
                    /// The CLDR version the shipped packs were generated from.
                    /// Empty when packs disagree or when no pack is loaded.
                    pub cldr_version: _rt::String,
                }
                impl ::core::fmt::Debug for CapabilitiesRecord {
                    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                        f.debug_struct("CapabilitiesRecord")
                            .field("supported-locales", &self.supported_locales)
                            .field("max-strength", &self.max_strength)
                            .field("cldr-version", &self.cldr_version)
                            .finish()
                    }
                }
                #[doc(hidden)]

                macro_rules! __export_stringcheese_icu_collation_types_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _: () = {};
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_stringcheese_icu_collation_types_0_1_0_cabi;
            }

            /// The core collation surface. Passing locale `""` requests the
            /// CLDR root locale (no tailoring, DUCET-only).
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod collation {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() =
                    super::super::super::super::__link_custom_section_describing_imports;

                use super::super::super::super::_rt;
                pub type Locale =
                    super::super::super::super::exports::stringcheese::icu_collation::types::Locale;
                pub type CollationError = super::super::super::super::exports::stringcheese::icu_collation::types::CollationError;
                pub type CollationStrength = super::super::super::super::exports::stringcheese::icu_collation::types::CollationStrength;
                pub type Ordering = super::super::super::super::exports::stringcheese::icu_collation::types::Ordering;
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_compare_cabi<T_: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                    arg4: *mut u8,
                    arg5: usize,
                    arg6: i32,
                ) -> *mut u8 {
                    unsafe {
                        #[cfg(target_arch = "wasm32")]
                        _rt::run_ctors_once();
                        let result3 = {
                            let len0 = arg1;
                            let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                            let len1 = arg3;
                            let bytes1 = _rt::Vec::from_raw_parts(arg2.cast(), len1, len1);
                            let len2 = arg5;
                            let bytes2 = _rt::Vec::from_raw_parts(arg4.cast(), len2, len2);
                            T_::compare(_rt::string_lift(bytes0), _rt::string_lift(bytes1), _rt::string_lift(bytes2), super::super::super::super::exports::stringcheese::icu_collation::types::CollationStrength::_lift(arg6 as u8))
                        };
                        let ptr4 = (&raw mut _RET_AREA.0).cast::<u8>();
                        match result3 {
                            Ok(e) => {
                                *ptr4.add(0).cast::<u8>() = (0i32) as u8;
                                *ptr4.add(::core::mem::size_of::<*const u8>()).cast::<u8>() =
                                    (e.clone() as i32) as u8;
                            }
                            Err(e) => {
                                *ptr4.add(0).cast::<u8>() = (1i32) as u8;
                                use super::super::super::super::exports::stringcheese::icu_collation::types::CollationError as V8;
                                match e {
                                    V8::InvalidLocale(e) => {
                                        *ptr4
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<u8>() = (0i32) as u8;
                                        let vec5 = (e.into_bytes()).into_boxed_slice();
                                        let ptr5 = vec5.as_ptr().cast::<u8>();
                                        let len5 = vec5.len();
                                        ::core::mem::forget(vec5);
                                        *ptr4
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>() = len5;
                                        *ptr4
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>() = ptr5.cast_mut();
                                    }
                                    V8::LocaleUnavailable(e) => {
                                        *ptr4
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<u8>() = (1i32) as u8;
                                        let vec6 = (e.into_bytes()).into_boxed_slice();
                                        let ptr6 = vec6.as_ptr().cast::<u8>();
                                        let len6 = vec6.len();
                                        ::core::mem::forget(vec6);
                                        *ptr4
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>() = len6;
                                        *ptr4
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>() = ptr6.cast_mut();
                                    }
                                    V8::UnsupportedStrength(e) => {
                                        *ptr4
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<u8>() = (2i32) as u8;
                                        let vec7 = (e.into_bytes()).into_boxed_slice();
                                        let ptr7 = vec7.as_ptr().cast::<u8>();
                                        let len7 = vec7.len();
                                        ::core::mem::forget(vec7);
                                        *ptr4
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>() = len7;
                                        *ptr4
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>() = ptr7.cast_mut();
                                    }
                                }
                            }
                        };
                        ptr4
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_compare<T_: Guest>(arg0: *mut u8) {
                    unsafe {
                        let l0 = i32::from(*arg0.add(0).cast::<u8>());
                        match l0 {
                            0 => (),
                            _ => {
                                let l1 = i32::from(
                                    *arg0.add(::core::mem::size_of::<*const u8>()).cast::<u8>(),
                                );
                                match l1 {
                                    0 => {
                                        let l2 = *arg0
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l3 = *arg0
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        _rt::cabi_dealloc(l2, l3, 1);
                                    }
                                    1 => {
                                        let l4 = *arg0
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l5 = *arg0
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        _rt::cabi_dealloc(l4, l5, 1);
                                    }
                                    _ => {
                                        let l6 = *arg0
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l7 = *arg0
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        _rt::cabi_dealloc(l6, l7, 1);
                                    }
                                }
                            }
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_sort_key_cabi<T_: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                    arg4: i32,
                ) -> *mut u8 {
                    unsafe {
                        #[cfg(target_arch = "wasm32")]
                        _rt::run_ctors_once();
                        let result2 = {
                            let len0 = arg1;
                            let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                            let len1 = arg3;
                            let bytes1 = _rt::Vec::from_raw_parts(arg2.cast(), len1, len1);
                            T_::sort_key(_rt::string_lift(bytes0), _rt::string_lift(bytes1), super::super::super::super::exports::stringcheese::icu_collation::types::CollationStrength::_lift(arg4 as u8))
                        };
                        let ptr3 = (&raw mut _RET_AREA.0).cast::<u8>();
                        match result2 {
                            Ok(e) => {
                                *ptr3.add(0).cast::<u8>() = (0i32) as u8;
                                let vec4 = <_ as Into<_rt::Vec<_>>>::into(e).into_boxed_slice();
                                let ptr4 = vec4.as_ptr().cast::<u8>();
                                let len4 = vec4.len();
                                ::core::mem::forget(vec4);
                                *ptr3
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>() = len4;
                                *ptr3
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>() = ptr4.cast_mut();
                            }
                            Err(e) => {
                                *ptr3.add(0).cast::<u8>() = (1i32) as u8;
                                use super::super::super::super::exports::stringcheese::icu_collation::types::CollationError as V8;
                                match e {
                                    V8::InvalidLocale(e) => {
                                        *ptr3
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<u8>() = (0i32) as u8;
                                        let vec5 = (e.into_bytes()).into_boxed_slice();
                                        let ptr5 = vec5.as_ptr().cast::<u8>();
                                        let len5 = vec5.len();
                                        ::core::mem::forget(vec5);
                                        *ptr3
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>() = len5;
                                        *ptr3
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>() = ptr5.cast_mut();
                                    }
                                    V8::LocaleUnavailable(e) => {
                                        *ptr3
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<u8>() = (1i32) as u8;
                                        let vec6 = (e.into_bytes()).into_boxed_slice();
                                        let ptr6 = vec6.as_ptr().cast::<u8>();
                                        let len6 = vec6.len();
                                        ::core::mem::forget(vec6);
                                        *ptr3
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>() = len6;
                                        *ptr3
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>() = ptr6.cast_mut();
                                    }
                                    V8::UnsupportedStrength(e) => {
                                        *ptr3
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<u8>() = (2i32) as u8;
                                        let vec7 = (e.into_bytes()).into_boxed_slice();
                                        let ptr7 = vec7.as_ptr().cast::<u8>();
                                        let len7 = vec7.len();
                                        ::core::mem::forget(vec7);
                                        *ptr3
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>() = len7;
                                        *ptr3
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>() = ptr7.cast_mut();
                                    }
                                }
                            }
                        };
                        ptr3
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_sort_key<T_: Guest>(arg0: *mut u8) {
                    unsafe {
                        let l0 = i32::from(*arg0.add(0).cast::<u8>());
                        match l0 {
                            0 => {
                                let l1 = *arg0
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l2 = *arg0
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let base3 = l1;
                                let len3 = l2;
                                _rt::cabi_dealloc(base3, len3 * 1, 1);
                            }
                            _ => {
                                let l4 = i32::from(
                                    *arg0.add(::core::mem::size_of::<*const u8>()).cast::<u8>(),
                                );
                                match l4 {
                                    0 => {
                                        let l5 = *arg0
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l6 = *arg0
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        _rt::cabi_dealloc(l5, l6, 1);
                                    }
                                    1 => {
                                        let l7 = *arg0
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l8 = *arg0
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        _rt::cabi_dealloc(l7, l8, 1);
                                    }
                                    _ => {
                                        let l9 = *arg0
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l10 = *arg0
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        _rt::cabi_dealloc(l9, l10, 1);
                                    }
                                }
                            }
                        }
                    }
                }
                pub trait Guest {
                    /// Compare `a` and `b` under the given locale and strength.
                    ///
                    /// Returns an [`ordering`] value suitable for feeding into a
                    /// `sort-by` predicate. The comparison is total for the
                    /// requested strength — two strings that compare equal at
                    /// primary strength may compare unequal at secondary or
                    /// tertiary.
                    #[allow(async_fn_in_trait)]
                    fn compare(
                        a: _rt::String,
                        b: _rt::String,
                        locale: Locale,
                        strength: CollationStrength,
                    ) -> Result<Ordering, CollationError>;
                    /// Produce a bytewise-comparable sort key for `text` under the
                    /// given locale and strength.
                    ///
                    /// Two keys compare byte-for-byte in the same order the two
                    /// input strings would compare through [`compare`]. Callers
                    /// use sort keys when they want to sort a set of strings once
                    /// and look them up by comparison many times — a `compare`
                    /// call per lookup pays the tailoring-expansion cost each
                    /// time; a sort-key does it once at key-generation time.
                    #[allow(async_fn_in_trait)]
                    fn sort_key(
                        text: _rt::String,
                        locale: Locale,
                        strength: CollationStrength,
                    ) -> Result<_rt::Vec<u8>, CollationError>;
                }
                #[doc(hidden)]

                macro_rules! __export_stringcheese_icu_collation_collation_0_1_0_cabi{
      ($ty:ident with_types_in $($path_to_types:tt)*) => (const _: () = {

        #[unsafe(export_name = "stringcheese:icu-collation/collation@0.1.0#compare")]
        unsafe extern "C" fn export_compare(arg0: *mut u8,arg1: usize,arg2: *mut u8,arg3: usize,arg4: *mut u8,arg5: usize,arg6: i32,) -> *mut u8 {
          unsafe { $($path_to_types)*::_export_compare_cabi::<$ty>(arg0, arg1, arg2, arg3, arg4, arg5, arg6) }
        }
        #[unsafe(export_name = "cabi_post_stringcheese:icu-collation/collation@0.1.0#compare")]
        unsafe extern "C" fn _post_return_compare(arg0: *mut u8,) {
          unsafe { $($path_to_types)*::__post_return_compare::<$ty>(arg0) }
        }
        #[unsafe(export_name = "stringcheese:icu-collation/collation@0.1.0#sort-key")]
        unsafe extern "C" fn export_sort_key(arg0: *mut u8,arg1: usize,arg2: *mut u8,arg3: usize,arg4: i32,) -> *mut u8 {
          unsafe { $($path_to_types)*::_export_sort_key_cabi::<$ty>(arg0, arg1, arg2, arg3, arg4) }
        }
        #[unsafe(export_name = "cabi_post_stringcheese:icu-collation/collation@0.1.0#sort-key")]
        unsafe extern "C" fn _post_return_sort_key(arg0: *mut u8,) {
          unsafe { $($path_to_types)*::__post_return_sort_key::<$ty>(arg0) }
        }
      };);
    }
                #[doc(hidden)]
                pub(crate) use __export_stringcheese_icu_collation_collation_0_1_0_cabi;

                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<u8>; 4 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 4 * ::core::mem::size_of::<*const u8>()],
                );
            }

            /// Introspection: which tailorings does the linked component
            /// actually cover?
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod capabilities {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() =
                    super::super::super::super::__link_custom_section_describing_imports;

                use super::super::super::super::_rt;
                pub type CapabilitiesRecord = super::super::super::super::exports::stringcheese::icu_collation::types::CapabilitiesRecord;
                pub type Locale =
                    super::super::super::super::exports::stringcheese::icu_collation::types::Locale;
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_get_capabilities_cabi<T_: Guest>() -> *mut u8 {
                    unsafe {
                        #[cfg(target_arch = "wasm32")]
                        _rt::run_ctors_once();
                        let result0 = { T_::get_capabilities() };
                        let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                        let super::super::super::super::exports::stringcheese::icu_collation::types::CapabilitiesRecord{ supported_locales:supported_locales2, max_strength:max_strength2, cldr_version:cldr_version2, } = result0;
                        let vec4 = supported_locales2;
                        let len4 = vec4.len();
                        let layout4 = _rt::alloc::Layout::from_size_align(
                            vec4.len() * (2 * ::core::mem::size_of::<*const u8>()),
                            ::core::mem::size_of::<*const u8>(),
                        )
                        .unwrap();
                        let (result4, _cleanup4) = wit_bindgen_rt::Cleanup::new(layout4);
                        if let Some(cleanup) = _cleanup4 {
                            cleanup.forget();
                        }
                        for (i, e) in vec4.into_iter().enumerate() {
                            let base = result4.add(i * (2 * ::core::mem::size_of::<*const u8>()));
                            {
                                let vec3 = (e.into_bytes()).into_boxed_slice();
                                let ptr3 = vec3.as_ptr().cast::<u8>();
                                let len3 = vec3.len();
                                ::core::mem::forget(vec3);
                                *base
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<usize>() = len3;
                                *base.add(0).cast::<*mut u8>() = ptr3.cast_mut();
                            }
                        }
                        *ptr1
                            .add(::core::mem::size_of::<*const u8>())
                            .cast::<usize>() = len4;
                        *ptr1.add(0).cast::<*mut u8>() = result4;
                        *ptr1
                            .add(2 * ::core::mem::size_of::<*const u8>())
                            .cast::<u8>() = (max_strength2.clone() as i32) as u8;
                        let vec5 = (cldr_version2.into_bytes()).into_boxed_slice();
                        let ptr5 = vec5.as_ptr().cast::<u8>();
                        let len5 = vec5.len();
                        ::core::mem::forget(vec5);
                        *ptr1
                            .add(4 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>() = len5;
                        *ptr1
                            .add(3 * ::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>() = ptr5.cast_mut();
                        ptr1
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_get_capabilities<T_: Guest>(arg0: *mut u8) {
                    unsafe {
                        let l0 = *arg0.add(0).cast::<*mut u8>();
                        let l1 = *arg0
                            .add(::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let base4 = l0;
                        let len4 = l1;
                        for i in 0..len4 {
                            let base = base4.add(i * (2 * ::core::mem::size_of::<*const u8>()));
                            {
                                let l2 = *base.add(0).cast::<*mut u8>();
                                let l3 = *base
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                _rt::cabi_dealloc(l2, l3, 1);
                            }
                        }
                        _rt::cabi_dealloc(
                            base4,
                            len4 * (2 * ::core::mem::size_of::<*const u8>()),
                            ::core::mem::size_of::<*const u8>(),
                        );
                        let l5 = *arg0
                            .add(3 * ::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>();
                        let l6 = *arg0
                            .add(4 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        _rt::cabi_dealloc(l5, l6, 1);
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_supports_cabi<T_: Guest>(arg0: *mut u8, arg1: usize) -> i32 {
                    unsafe {
                        #[cfg(target_arch = "wasm32")]
                        _rt::run_ctors_once();
                        let result1 = {
                            let len0 = arg1;
                            let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                            T_::supports(_rt::string_lift(bytes0))
                        };
                        match result1 {
                            true => 1,
                            false => 0,
                        }
                    }
                }
                pub trait Guest {
                    /// The introspection record for the loaded packs.
                    #[allow(async_fn_in_trait)]
                    fn get_capabilities() -> CapabilitiesRecord;
                    /// True iff a query in the given locale would use a pack
                    /// (rather than falling through to root DUCET).
                    #[allow(async_fn_in_trait)]
                    fn supports(loc: Locale) -> bool;
                }
                #[doc(hidden)]

                macro_rules! __export_stringcheese_icu_collation_capabilities_0_1_0_cabi{
  ($ty:ident with_types_in $($path_to_types:tt)*) => (const _: () = {

    #[unsafe(export_name = "stringcheese:icu-collation/capabilities@0.1.0#get-capabilities")]
    unsafe extern "C" fn export_get_capabilities() -> *mut u8 {
      unsafe { $($path_to_types)*::_export_get_capabilities_cabi::<$ty>() }
    }
    #[unsafe(export_name = "cabi_post_stringcheese:icu-collation/capabilities@0.1.0#get-capabilities")]
    unsafe extern "C" fn _post_return_get_capabilities(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_get_capabilities::<$ty>(arg0) }
    }
    #[unsafe(export_name = "stringcheese:icu-collation/capabilities@0.1.0#supports")]
    unsafe extern "C" fn export_supports(arg0: *mut u8,arg1: usize,) -> i32 {
      unsafe { $($path_to_types)*::_export_supports_cabi::<$ty>(arg0, arg1) }
    }
  };);
}
                #[doc(hidden)]
                pub(crate) use __export_stringcheese_icu_collation_capabilities_0_1_0_cabi;

                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<u8>; 5 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 5 * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
mod _rt {
    #![allow(dead_code, unused_imports, clippy::all)]
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;

    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            unsafe { String::from_utf8_unchecked(bytes) }
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        unsafe {
            let layout = alloc::Layout::from_size_align_unchecked(size, align);
            alloc::dealloc(ptr, layout);
        }
    }
    pub use alloc_crate::alloc;
    extern crate alloc as alloc_crate;
}

/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]

macro_rules! __export_collation_world_impl {
  ($ty:ident) => (self::export!($ty with_types_in self););
  ($ty:ident with_types_in $($path_to_types_root:tt)*) => (
  $($path_to_types_root)*::exports::stringcheese::icu_collation::types::__export_stringcheese_icu_collation_types_0_1_0_cabi!($ty with_types_in $($path_to_types_root)*::exports::stringcheese::icu_collation::types);
  $($path_to_types_root)*::exports::stringcheese::icu_collation::collation::__export_stringcheese_icu_collation_collation_0_1_0_cabi!($ty with_types_in $($path_to_types_root)*::exports::stringcheese::icu_collation::collation);
  $($path_to_types_root)*::exports::stringcheese::icu_collation::capabilities::__export_stringcheese_icu_collation_capabilities_0_1_0_cabi!($ty with_types_in $($path_to_types_root)*::exports::stringcheese::icu_collation::capabilities);
  )
}
#[doc(inline)]
pub(crate) use __export_collation_world_impl as export;

#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.60.0:stringcheese:icu-collation@0.1.0:collation-world:encoded world")]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1009] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xeb\x06\x01A\x02\x01\
A\x0b\x01B\x0b\x01s\x04\0\x06locale\x03\0\0\x01q\x03\x0einvalid-locale\x01s\0\x12\
locale-unavailable\x01s\0\x14unsupported-strength\x01s\0\x04\0\x0fcollation-erro\
r\x03\0\x02\x01m\x05\x07primary\x09secondary\x08tertiary\x0aquaternary\x09identi\
cal\x04\0\x12collation-strength\x03\0\x04\x01m\x03\x04less\x05equal\x07greater\x04\
\0\x08ordering\x03\0\x06\x01p\x01\x01r\x03\x11supported-locales\x08\x0cmax-stren\
gth\x05\x0ccldr-versions\x04\0\x13capabilities-record\x03\0\x09\x04\0&stringchee\
se:icu-collation/types@0.1.0\x05\0\x02\x03\0\0\x06locale\x02\x03\0\0\x0fcollatio\
n-error\x02\x03\0\0\x12collation-strength\x02\x03\0\0\x08ordering\x01B\x0f\x02\x03\
\x02\x01\x01\x04\0\x06locale\x03\0\0\x02\x03\x02\x01\x02\x04\0\x0fcollation-erro\
r\x03\0\x02\x02\x03\x02\x01\x03\x04\0\x12collation-strength\x03\0\x04\x02\x03\x02\
\x01\x04\x04\0\x08ordering\x03\0\x06\x01j\x01\x07\x01\x03\x01@\x04\x01as\x01bs\x06\
locale\x01\x08strength\x05\0\x08\x04\0\x07compare\x01\x09\x01p}\x01j\x01\x0a\x01\
\x03\x01@\x03\x04texts\x06locale\x01\x08strength\x05\0\x0b\x04\0\x08sort-key\x01\
\x0c\x04\0*stringcheese:icu-collation/collation@0.1.0\x05\x05\x02\x03\0\0\x13cap\
abilities-record\x01B\x08\x02\x03\x02\x01\x06\x04\0\x13capabilities-record\x03\0\
\0\x02\x03\x02\x01\x01\x04\0\x06locale\x03\0\x02\x01@\0\0\x01\x04\0\x10get-capab\
ilities\x01\x04\x01@\x01\x03loc\x03\0\x7f\x04\0\x08supports\x01\x05\x04\0-string\
cheese:icu-collation/capabilities@0.1.0\x05\x07\x04\00stringcheese:icu-collation\
/collation-world@0.1.0\x04\0\x0b\x15\x01\0\x0fcollation-world\x03\0\0\0G\x09prod\
ucers\x01\x0cprocessed-by\x02\x0dwit-component\x070.254.0\x10wit-bindgen-rust\x06\
0.60.0";

#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
