//! Wasmtime smoke test for the reference `tegmentum:tokenizer@0.1.0`
//! component.
//!
//! Verifies Phase 7's "reference `tokenizer-provider` component built
//! from the character-BPE seed echoes correct encodings across the
//! boundary under wasmtime" acceptance criterion. The test drives the
//! component the same way any external caller would: builds it under
//! `wasm32-wasip1 --features wit-component`, componentizes it via
//! `wasm-tools`, then loads the componentised `.wasm` into an
//! in-process wasmtime `Engine` and calls each of the four WIT exports
//! (`get-capabilities`, `encode`, `decode`, `count`) through typed
//! bindings generated by `wasmtime::component::bindgen!` from the
//! shipped WIT file. Assertions are on the returned Rust values, not
//! parsed from a CLI wave-string.
//!
//! # Prerequisites
//!
//! Requires two tools on `$PATH`:
//!
//! * `cargo` with the `wasm32-wasip1` target installed
//! * `wasm-tools` (Bytecode Alliance) — used only for `component new`
//!   to produce the component encoding from the plain wasm module.
//!
//! Plus one file on disk — the WASI preview1 → preview2 reactor
//! adapter — discoverable via the search order documented in
//! [`find_wasi_adapter`]. The adapter version must match the wasmtime
//! crate version (both 26.x on CI); a version mismatch surfaces as an
//! import-mismatch panic at `Linker::instantiate` time.
//!
//! When any of these prerequisites is missing the test soft-skips
//! with a diagnostic — matching the "conformance runner" convention
//! used by `stringcheese-tokenizer-hf`'s real-vocab tests. This keeps
//! host `cargo test` green on developer machines that haven't
//! installed the wasm toolchain; CI installs both tools and downloads
//! the version-matched adapter explicitly (see the
//! `wasm-tokenizer-component` job).
//!
//! # Why the wasmtime crate instead of `wasmtime run --invoke`
//!
//! The original Phase 7 landing shelled out to `wasmtime run --invoke`.
//! That path stopped working when wasmtime 20+ removed `--invoke` for
//! components (only core modules retain it). The rewrite here embeds
//! wasmtime as a dev-dep and calls the exports through the typed
//! bindings the `bindgen!` macro produces from
//! `component/wit/tokenizer/stringcheese-tokenizer.wit`. Trade-offs:
//!
//! * Adds a substantial transitive-dep tail (cranelift, regalloc2,
//!   target-lexicon, wasmparser, wat, ...) on the *dev-dep* graph
//!   only. The runtime dep graph is unchanged — a downstream Rust
//!   consumer linking this crate as an `rlib` (or the WIT component
//!   as a wasm binary) never pulls any of it in.
//! * Feature-trimmed to `runtime` + `cranelift` + `component-model` +
//!   `std` (see `Cargo.toml`) so the compile cost stays bounded — no
//!   pooling allocator, no async fibers, no rayon parallel
//!   compilation, no coredump / debug-builtins / profiling / gc /
//!   threads / wat / addr2line / demangle. Sync-only linker paths are
//!   what these tests need.
//! * `wasmtime-wasi` supplies the preview2 host implementations that
//!   the wasip1→wasip2 adapter's `wasi:*` imports resolve into. The
//!   reference tokenizer performs no I/O of its own, but the imports
//!   have to be satisfied for `Linker::instantiate` to succeed.

#![cfg(not(target_family = "wasm"))]
#![allow(unsafe_code)]

use std::path::PathBuf;
use std::process::Command;
use std::sync::OnceLock;

use wasmtime::component::{Component, Linker, ResourceTable};
use wasmtime::{Engine, Store};
use wasmtime_wasi::{WasiCtx, WasiCtxBuilder, WasiView};

// Typed bindings generated from the shipped WIT contract. The macro
// mirrors the same `tokenizer-provider` world the guest crate exports,
// but from the *host* side — the generated `TokenizerProvider` struct
// is what we instantiate against a linker below, and its
// `tegmentum_tokenizer_tokenizer()` accessor returns typed handles to
// the four exports the tests exercise. The macro expansion emits
// several items without doc comments; wrapping in a module lets us
// scope a single `#[allow(missing_docs)]` around the generated code
// without loosening the crate-wide lint level.
#[allow(missing_docs, clippy::pedantic, clippy::nursery)]
mod bindgen {
    wasmtime::component::bindgen!({
        world: "tokenizer-provider",
        path: "../../component/wit/tokenizer",
    });
}

use bindgen::TokenizerProvider;
use bindgen::exports::tegmentum::tokenizer::tokenizer::TokenizerError as WitTokenizerError;

/// Host state carried in the `Store<T>`. Holds the WASI preview2
/// context and a `ResourceTable` for any WASI resources instantiated
/// during a call. The reference tokenizer never touches either — the
/// component performs no I/O — but a `WasiView` impl is still required
/// so the linker can wire the imported `wasi:*` interfaces.
struct HostState {
    table: ResourceTable,
    wasi: WasiCtx,
}

impl WasiView for HostState {
    fn ctx(&mut self) -> &mut WasiCtx {
        &mut self.wasi
    }
    fn table(&mut self) -> &mut ResourceTable {
        &mut self.table
    }
}

/// One end-to-end build-and-load: shell out to `cargo build` +
/// `wasm-tools component new` once, load the resulting `.wasm` into a
/// wasmtime `Engine`, and cache the immutable engine/component/linker
/// on the shared `OnceLock` so every test instantiates cheaply.
struct SmokeHarness {
    engine: Engine,
    component: Component,
    linker: Linker<HostState>,
}

/// The four smoke tests run concurrently under `cargo test`'s
/// default thread pool. Each calls `SmokeHarness::build_or_skip`;
/// without a guard the four threads would race on the same
/// `target/wasm32-wasip1/release/` directory and `wasm-tools`
/// output path, producing spurious failures when one test's
/// componentize step reads a wasm the other is still writing.
/// This `OnceLock<Option<PathBuf>>` serialises the build-once,
/// componentize-once step across every caller — subsequent
/// invocations get back the cached component path (or the cached
/// skip decision) without re-invoking cargo / wasm-tools.
static SHARED_COMPONENT: OnceLock<Option<PathBuf>> = OnceLock::new();

impl SmokeHarness {
    fn build_or_skip() -> Option<Self> {
        let component_wasm = SHARED_COMPONENT
            .get_or_init(Self::build_shared_once)
            .clone()?;

        // Wasmtime construction is per-caller. `Engine` is cheap
        // (JIT compilation of the component is amortised over the
        // subsequent `instantiate` calls); building fresh each call
        // rather than caching a static `Engine` avoids the `Sync`
        // constraint the shared cache would impose.
        let engine = Engine::default();
        let component = match Component::from_file(&engine, &component_wasm) {
            Ok(c) => c,
            Err(e) => {
                eprintln!(
                    "SKIP: wasmtime failed to load component at {}: {e}",
                    component_wasm.display()
                );
                return None;
            }
        };
        let mut linker: Linker<HostState> = Linker::new(&engine);
        if let Err(e) = wasmtime_wasi::add_to_linker_sync(&mut linker) {
            eprintln!("SKIP: could not add WASI to linker: {e}");
            return None;
        }
        Some(Self {
            engine,
            component,
            linker,
        })
    }

    fn build_shared_once() -> Option<PathBuf> {
        // Every one of these tools is optional at test-run time; a
        // missing tool soft-skips rather than failing. Matches the
        // shape of `stringcheese-tokenizer-hf`'s real-vocab
        // conformance runner.
        if !has_tool("cargo") {
            eprintln!("SKIP: cargo not on PATH");
            return None;
        }
        if !has_tool("wasm-tools") {
            eprintln!(
                "SKIP: wasm-tools not on PATH — install from https://github.com/bytecodealliance/wasm-tools"
            );
            return None;
        }
        if !target_installed("wasm32-wasip1") {
            eprintln!(
                "SKIP: wasm32-wasip1 target not installed — `rustup target add wasm32-wasip1`"
            );
            return None;
        }

        // Build the wasm module. `--release` keeps the produced
        // artifact aligned with the CI job's build recipe; the size
        // gate downstream measures the release output.
        let workspace_root = workspace_root();
        let build = Command::new("cargo")
            .current_dir(&workspace_root)
            .args([
                "build",
                "-p",
                "stringcheese-tokenizer-component",
                "--target",
                "wasm32-wasip1",
                "--features",
                "wit-component",
                "--release",
            ])
            .status()
            .expect("cargo build must launch");
        assert!(
            build.success(),
            "cargo build for wasm32-wasip1 must succeed"
        );

        let module_wasm = workspace_root
            .join("target/wasm32-wasip1/release/stringcheese_tokenizer_component.wasm");
        assert!(
            module_wasm.exists(),
            "expected wasm at {} after cargo build",
            module_wasm.display()
        );

        // Locate the WASI preview1 → preview2 adapter. On the CI path
        // the workflow places the adapter under `$RUNNER_TEMP/adapter.wasm`;
        // on developer machines the test soft-skips when nothing is
        // found. The adapter version must match the wasmtime crate
        // version — a mismatch surfaces as an import-mismatch at
        // `Linker::instantiate` time.
        let Some(adapter) = find_wasi_adapter() else {
            eprintln!(
                "SKIP: no wasi_snapshot_preview1.reactor.wasm adapter found on the search path"
            );
            return None;
        };

        // Componentize.
        let component_wasm = std::env::temp_dir().join("stringcheese_tokenizer_component.wasm");
        let componentize = Command::new("wasm-tools")
            .args([
                "component",
                "new",
                module_wasm.to_str().expect("path is utf8"),
                "--adapt",
                adapter.to_str().expect("adapter path is utf8"),
                "-o",
                component_wasm.to_str().expect("output path is utf8"),
            ])
            .status()
            .expect("wasm-tools must launch");
        assert!(
            componentize.success(),
            "wasm-tools component new must succeed"
        );
        assert!(
            component_wasm.exists(),
            "expected component at {}",
            component_wasm.display()
        );
        Some(component_wasm)
    }

    /// Instantiate the component in a fresh `Store`. Each test owns
    /// its own store; instantiation is cheap once the component is
    /// compiled and the linker is populated.
    fn instantiate(&self) -> (Store<HostState>, TokenizerProvider) {
        let mut store = Store::new(
            &self.engine,
            HostState {
                table: ResourceTable::new(),
                wasi: WasiCtxBuilder::new().build(),
            },
        );
        let bindings = TokenizerProvider::instantiate(&mut store, &self.component, &self.linker)
            .expect("component must instantiate against the wasmtime-wasi linker");
        (store, bindings)
    }
}

fn has_tool(name: &str) -> bool {
    Command::new(name)
        .arg("--version")
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status()
        .is_ok_and(|s| s.success())
}

fn target_installed(triple: &str) -> bool {
    let out = Command::new("rustup")
        .args(["target", "list", "--installed"])
        .output();
    match out {
        Ok(o) if o.status.success() => String::from_utf8_lossy(&o.stdout)
            .lines()
            .any(|l| l.trim() == triple),
        _ => {
            // `rustup` unavailable — assume the target is present so
            // the caller sees the real failure (build) rather than an
            // erroneous skip.
            true
        }
    }
}

fn workspace_root() -> PathBuf {
    // CARGO_MANIFEST_DIR is `crates/stringcheese-tokenizer-component`;
    // walk up two levels to reach the workspace root.
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    manifest
        .parent()
        .and_then(|p| p.parent())
        .expect("workspace root is two levels above crate manifest")
        .to_path_buf()
}

fn find_wasi_adapter() -> Option<PathBuf> {
    // Search order:
    //   1. `STRINGCHEESE_WASI_ADAPTER` environment variable — the
    //      CI job sets this to the adapter it downloads into
    //      `$RUNNER_TEMP`.
    //   2. `~/.cache/stringcheese-tokenizer-component/wasi_snapshot_preview1.reactor.wasm`
    //      — a developer convenience path so a one-time download
    //      does not need to be repeated per test run.
    //   3. Any `wasi_snapshot_preview1.reactor.wasm` under
    //      `~/.cargo/registry/`. cargo-component ships one at
    //      known relative paths after `cargo install cargo-component`.
    if let Ok(p) = std::env::var("STRINGCHEESE_WASI_ADAPTER") {
        let path = PathBuf::from(p);
        if path.exists() {
            return Some(path);
        }
    }
    let home = std::env::var_os("HOME").map(PathBuf::from)?;
    let cache =
        home.join(".cache/stringcheese-tokenizer-component/wasi_snapshot_preview1.reactor.wasm");
    if cache.exists() {
        return Some(cache);
    }
    // Last resort: search cargo-component's install root.
    walk_for_adapter(&home.join(".cargo/registry/src")).next()
}

fn walk_for_adapter(root: &std::path::Path) -> impl Iterator<Item = PathBuf> {
    // Non-recursive one-level scan; cargo-component's adapter lives
    // at a known depth. Kept intentionally shallow to bound test
    // startup cost.
    let mut out = Vec::new();
    if let Ok(entries) = std::fs::read_dir(root) {
        for entry in entries.flatten() {
            let path = entry.path();
            let candidate = path.join("cargo-component/wasi_snapshot_preview1.reactor.wasm");
            if candidate.exists() {
                out.push(candidate);
            }
        }
    }
    out.into_iter()
}

/// Format the WIT-side `tokenizer-error` variant for a compact
/// panic message when a `Result` returned by an export unexpectedly
/// carries an error. The `WitTokenizerError` type is generated from
/// the WIT `variant` and does not have a stable `Display` impl; the
/// per-arm rendering here keeps the failure message readable even
/// when a regression flips a happy-path call into the error tail.
fn describe_err(e: &WitTokenizerError) -> String {
    match e {
        WitTokenizerError::InvalidUtf8 => "invalid-utf8".to_string(),
        WitTokenizerError::UnknownToken(s) => format!("unknown-token({s:?})"),
        WitTokenizerError::DisallowedSpecialToken(s) => format!("disallowed-special-token({s:?})"),
        WitTokenizerError::VocabularyMismatch => "vocabulary-mismatch".to_string(),
        WitTokenizerError::Other(s) => format!("other({s:?})"),
    }
}

#[test]
fn wasmtime_smoke_encode_returns_expected_ids() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let tok = bindings.tegmentum_tokenizer_tokenizer();
    let encoding = tok
        .call_encode(&mut store, "hello")
        .expect("encode trap-free")
        .unwrap_or_else(|e| panic!("encode('hello') returned error: {}", describe_err(&e)));
    // The character-BPE reference vocab merges "hello" to id 260;
    // the returned encoding carries a single 0..5 offset and no
    // special-mask entries (the reference tokenizer emits an empty
    // mask when no special token fires, matching the trait crate's
    // "empty when not tracked" convention).
    assert_eq!(encoding.ids, vec![260], "encoded id sequence");
    assert_eq!(encoding.offsets.len(), 1, "one offset entry per id");
    assert_eq!(encoding.offsets[0].start, 0, "offset start");
    assert_eq!(encoding.offsets[0].end, 5, "offset end covers 'hello'");
}

#[test]
fn wasmtime_smoke_decode_round_trips_hello() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let tok = bindings.tegmentum_tokenizer_tokenizer();
    let decoded = tok
        .call_decode(&mut store, &[260])
        .expect("decode trap-free")
        .unwrap_or_else(|e| panic!("decode([260]) returned error: {}", describe_err(&e)));
    assert_eq!(decoded, "hello");
}

#[test]
fn wasmtime_smoke_count_matches_encode() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let tok = bindings.tegmentum_tokenizer_tokenizer();
    let n = tok
        .call_count(&mut store, "hello")
        .expect("count trap-free")
        .unwrap_or_else(|e| panic!("count('hello') returned error: {}", describe_err(&e)));
    assert_eq!(n, 1, "'hello' collapses to a single merged id");
}

#[test]
fn wasmtime_smoke_get_capabilities_reports_reference_shape() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let tok = bindings.tegmentum_tokenizer_tokenizer();
    let caps = tok
        .call_get_capabilities(&mut store)
        .expect("get-capabilities trap-free");
    assert_eq!(caps.model_type, "bpe", "model-type field");
    assert_eq!(
        caps.variant_id, "reference-character-bpe",
        "variant-id field"
    );
    assert_eq!(
        caps.vocab_size, 261,
        "vocab-size includes byte alphabet + 5 merged pieces"
    );
    assert!(!caps.has_byte_fallback, "reference has no byte-fallback");
    assert!(caps.has_special_tokens, "reference registers <|endoftext|>");
}
