// Generated by `wit-bindgen` 0.60.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod stringcheese {
        pub mod icu_case {
            /// Shared types. Split into its own interface so the `mapping` and
            /// `capabilities` interfaces can `use` the same definitions.
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod types {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() =
                    super::super::super::super::__link_custom_section_describing_imports;

                use super::super::super::super::_rt;
                /// BCP 47 locale tag: "en", "pt-BR", "zh-Hant-HK", "az-Cyrl-AZ".
                /// The empty string denotes the CLDR root locale — no tailoring.
                pub type Locale = _rt::String;
                /// Errors surfaced by the case-mapping interface. Case mapping is
                /// total on valid Unicode input; failure modes are structural.
                #[derive(Clone)]
                pub enum CaseError {
                    /// The locale tag was not a well-formed BCP 47 tag. Payload
                    /// is the offending string.
                    InvalidLocale(_rt::String),
                    /// No pack was loaded for the requested locale and no
                    /// fallback in the CLDR chain resolved. Payload is the tag
                    /// that could not be resolved.
                    LocaleUnavailable(_rt::String),
                    /// The caller asked for a title-casing mode this component
                    /// does not implement. Payload is the mode name.
                    UnsupportedTitleMode(_rt::String),
                }
                impl ::core::fmt::Debug for CaseError {
                    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                        match self {
                            CaseError::InvalidLocale(e) => {
                                f.debug_tuple("CaseError::InvalidLocale").field(e).finish()
                            }
                            CaseError::LocaleUnavailable(e) => f
                                .debug_tuple("CaseError::LocaleUnavailable")
                                .field(e)
                                .finish(),
                            CaseError::UnsupportedTitleMode(e) => f
                                .debug_tuple("CaseError::UnsupportedTitleMode")
                                .field(e)
                                .finish(),
                        }
                    }
                }
                impl ::core::fmt::Display for CaseError {
                    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                        write!(f, "{:?}", self)
                    }
                }

                impl ::core::error::Error for CaseError {}
                /// How aggressively to fold case. See UAX #21 § 1.3.
                #[repr(u8)]
                #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
                pub enum FoldMode {
                    /// Common + Simple — 1:1 code-point mapping only. `ß` folds
                    /// to `ß`; the caller is responsible for expansion at query
                    /// time if needed.
                    Simple,
                    /// Common + Full — may expand (`ß → ss`).
                    Full,
                    /// Full + Turkic tailorings — folds `I → ı` and `İ → i` in
                    /// a locale-neutral context.
                    FullTurkic,
                }
                impl ::core::fmt::Debug for FoldMode {
                    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                        match self {
                            FoldMode::Simple => f.debug_tuple("FoldMode::Simple").finish(),
                            FoldMode::Full => f.debug_tuple("FoldMode::Full").finish(),
                            FoldMode::FullTurkic => f.debug_tuple("FoldMode::FullTurkic").finish(),
                        }
                    }
                }

                impl FoldMode {
                    #[doc(hidden)]
                    pub unsafe fn _lift(val: u8) -> FoldMode {
                        if !cfg!(debug_assertions) {
                            return unsafe { ::core::mem::transmute(val) };
                        }

                        match val {
                            0 => FoldMode::Simple,
                            1 => FoldMode::Full,
                            2 => FoldMode::FullTurkic,

                            _ => panic!("invalid enum discriminant"),
                        }
                    }
                }

                /// Which boundary rule `to-title` uses to identify the "start of
                /// a title word".
                #[repr(u8)]
                #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
                pub enum TitleBoundary {
                    /// UAX #29 grapheme breaks: stateless, imperfect but cheap.
                    Graphemes,
                    /// UAX #29 word breaks: correct for most Latin.
                    Words,
                    /// Only sentence-initial words are candidates.
                    Sentences,
                }
                impl ::core::fmt::Debug for TitleBoundary {
                    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                        match self {
                            TitleBoundary::Graphemes => {
                                f.debug_tuple("TitleBoundary::Graphemes").finish()
                            }
                            TitleBoundary::Words => f.debug_tuple("TitleBoundary::Words").finish(),
                            TitleBoundary::Sentences => {
                                f.debug_tuple("TitleBoundary::Sentences").finish()
                            }
                        }
                    }
                }

                impl TitleBoundary {
                    #[doc(hidden)]
                    pub unsafe fn _lift(val: u8) -> TitleBoundary {
                        if !cfg!(debug_assertions) {
                            return unsafe { ::core::mem::transmute(val) };
                        }

                        match val {
                            0 => TitleBoundary::Graphemes,
                            1 => TitleBoundary::Words,
                            2 => TitleBoundary::Sentences,

                            _ => panic!("invalid enum discriminant"),
                        }
                    }
                }

                /// Options record for `to-title`.
                #[repr(C)]
                #[derive(Clone, Copy)]
                pub struct TitleOptions {
                    /// Which boundary rule to use.
                    pub boundary: TitleBoundary,
                    /// When true, lowercase all non-initial characters in each
                    /// title word (`AbC → Abc`). When false, preserve the
                    /// non-initial characters as-is.
                    pub lowercase_tail: bool,
                }
                impl ::core::fmt::Debug for TitleOptions {
                    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                        f.debug_struct("TitleOptions")
                            .field("boundary", &self.boundary)
                            .field("lowercase-tail", &self.lowercase_tail)
                            .finish()
                    }
                }
                #[doc(hidden)]

                macro_rules! __export_stringcheese_icu_case_types_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _: () = {};
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_stringcheese_icu_case_types_0_1_0_cabi;
            }

            /// The core case-mapping surface. Passing locale `""` requests the
            /// CLDR root locale (no tailoring).
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod mapping {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() =
                    super::super::super::super::__link_custom_section_describing_imports;

                use super::super::super::super::_rt;
                pub type Locale =
                    super::super::super::super::exports::stringcheese::icu_case::types::Locale;
                pub type CaseError =
                    super::super::super::super::exports::stringcheese::icu_case::types::CaseError;
                pub type FoldMode =
                    super::super::super::super::exports::stringcheese::icu_case::types::FoldMode;
                pub type TitleOptions = super::super::super::super::exports::stringcheese::icu_case::types::TitleOptions;
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_to_lower_cabi<T_: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                ) -> *mut u8 {
                    unsafe {
                        #[cfg(target_arch = "wasm32")]
                        _rt::run_ctors_once();
                        let result2 = {
                            let len0 = arg1;
                            let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                            let len1 = arg3;
                            let bytes1 = _rt::Vec::from_raw_parts(arg2.cast(), len1, len1);
                            T_::to_lower(_rt::string_lift(bytes0), _rt::string_lift(bytes1))
                        };
                        let ptr3 = (&raw mut _RET_AREA.0).cast::<u8>();
                        match result2 {
                            Ok(e) => {
                                *ptr3.add(0).cast::<u8>() = (0i32) as u8;
                                let vec4 = (e.into_bytes()).into_boxed_slice();
                                let ptr4 = vec4.as_ptr().cast::<u8>();
                                let len4 = vec4.len();
                                ::core::mem::forget(vec4);
                                *ptr3
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>() = len4;
                                *ptr3
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>() = ptr4.cast_mut();
                            }
                            Err(e) => {
                                *ptr3.add(0).cast::<u8>() = (1i32) as u8;
                                use super::super::super::super::exports::stringcheese::icu_case::types::CaseError as V8;
                                match e {
                                    V8::InvalidLocale(e) => {
                                        *ptr3
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<u8>() = (0i32) as u8;
                                        let vec5 = (e.into_bytes()).into_boxed_slice();
                                        let ptr5 = vec5.as_ptr().cast::<u8>();
                                        let len5 = vec5.len();
                                        ::core::mem::forget(vec5);
                                        *ptr3
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>() = len5;
                                        *ptr3
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>() = ptr5.cast_mut();
                                    }
                                    V8::LocaleUnavailable(e) => {
                                        *ptr3
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<u8>() = (1i32) as u8;
                                        let vec6 = (e.into_bytes()).into_boxed_slice();
                                        let ptr6 = vec6.as_ptr().cast::<u8>();
                                        let len6 = vec6.len();
                                        ::core::mem::forget(vec6);
                                        *ptr3
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>() = len6;
                                        *ptr3
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>() = ptr6.cast_mut();
                                    }
                                    V8::UnsupportedTitleMode(e) => {
                                        *ptr3
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<u8>() = (2i32) as u8;
                                        let vec7 = (e.into_bytes()).into_boxed_slice();
                                        let ptr7 = vec7.as_ptr().cast::<u8>();
                                        let len7 = vec7.len();
                                        ::core::mem::forget(vec7);
                                        *ptr3
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>() = len7;
                                        *ptr3
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>() = ptr7.cast_mut();
                                    }
                                }
                            }
                        };
                        ptr3
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_to_lower<T_: Guest>(arg0: *mut u8) {
                    unsafe {
                        let l0 = i32::from(*arg0.add(0).cast::<u8>());
                        match l0 {
                            0 => {
                                let l1 = *arg0
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l2 = *arg0
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                _rt::cabi_dealloc(l1, l2, 1);
                            }
                            _ => {
                                let l3 = i32::from(
                                    *arg0.add(::core::mem::size_of::<*const u8>()).cast::<u8>(),
                                );
                                match l3 {
                                    0 => {
                                        let l4 = *arg0
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l5 = *arg0
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        _rt::cabi_dealloc(l4, l5, 1);
                                    }
                                    1 => {
                                        let l6 = *arg0
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l7 = *arg0
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        _rt::cabi_dealloc(l6, l7, 1);
                                    }
                                    _ => {
                                        let l8 = *arg0
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l9 = *arg0
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        _rt::cabi_dealloc(l8, l9, 1);
                                    }
                                }
                            }
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_to_upper_cabi<T_: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                ) -> *mut u8 {
                    unsafe {
                        #[cfg(target_arch = "wasm32")]
                        _rt::run_ctors_once();
                        let result2 = {
                            let len0 = arg1;
                            let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                            let len1 = arg3;
                            let bytes1 = _rt::Vec::from_raw_parts(arg2.cast(), len1, len1);
                            T_::to_upper(_rt::string_lift(bytes0), _rt::string_lift(bytes1))
                        };
                        let ptr3 = (&raw mut _RET_AREA.0).cast::<u8>();
                        match result2 {
                            Ok(e) => {
                                *ptr3.add(0).cast::<u8>() = (0i32) as u8;
                                let vec4 = (e.into_bytes()).into_boxed_slice();
                                let ptr4 = vec4.as_ptr().cast::<u8>();
                                let len4 = vec4.len();
                                ::core::mem::forget(vec4);
                                *ptr3
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>() = len4;
                                *ptr3
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>() = ptr4.cast_mut();
                            }
                            Err(e) => {
                                *ptr3.add(0).cast::<u8>() = (1i32) as u8;
                                use super::super::super::super::exports::stringcheese::icu_case::types::CaseError as V8;
                                match e {
                                    V8::InvalidLocale(e) => {
                                        *ptr3
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<u8>() = (0i32) as u8;
                                        let vec5 = (e.into_bytes()).into_boxed_slice();
                                        let ptr5 = vec5.as_ptr().cast::<u8>();
                                        let len5 = vec5.len();
                                        ::core::mem::forget(vec5);
                                        *ptr3
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>() = len5;
                                        *ptr3
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>() = ptr5.cast_mut();
                                    }
                                    V8::LocaleUnavailable(e) => {
                                        *ptr3
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<u8>() = (1i32) as u8;
                                        let vec6 = (e.into_bytes()).into_boxed_slice();
                                        let ptr6 = vec6.as_ptr().cast::<u8>();
                                        let len6 = vec6.len();
                                        ::core::mem::forget(vec6);
                                        *ptr3
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>() = len6;
                                        *ptr3
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>() = ptr6.cast_mut();
                                    }
                                    V8::UnsupportedTitleMode(e) => {
                                        *ptr3
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<u8>() = (2i32) as u8;
                                        let vec7 = (e.into_bytes()).into_boxed_slice();
                                        let ptr7 = vec7.as_ptr().cast::<u8>();
                                        let len7 = vec7.len();
                                        ::core::mem::forget(vec7);
                                        *ptr3
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>() = len7;
                                        *ptr3
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>() = ptr7.cast_mut();
                                    }
                                }
                            }
                        };
                        ptr3
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_to_upper<T_: Guest>(arg0: *mut u8) {
                    unsafe {
                        let l0 = i32::from(*arg0.add(0).cast::<u8>());
                        match l0 {
                            0 => {
                                let l1 = *arg0
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l2 = *arg0
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                _rt::cabi_dealloc(l1, l2, 1);
                            }
                            _ => {
                                let l3 = i32::from(
                                    *arg0.add(::core::mem::size_of::<*const u8>()).cast::<u8>(),
                                );
                                match l3 {
                                    0 => {
                                        let l4 = *arg0
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l5 = *arg0
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        _rt::cabi_dealloc(l4, l5, 1);
                                    }
                                    1 => {
                                        let l6 = *arg0
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l7 = *arg0
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        _rt::cabi_dealloc(l6, l7, 1);
                                    }
                                    _ => {
                                        let l8 = *arg0
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l9 = *arg0
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        _rt::cabi_dealloc(l8, l9, 1);
                                    }
                                }
                            }
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_to_title_cabi<T_: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                    arg4: i32,
                    arg5: i32,
                ) -> *mut u8 {
                    unsafe {
                        #[cfg(target_arch = "wasm32")]
                        _rt::run_ctors_once();
                        let result2 = {
                            let len0 = arg1;
                            let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                            let len1 = arg3;
                            let bytes1 = _rt::Vec::from_raw_parts(arg2.cast(), len1, len1);
                            T_::to_title(_rt::string_lift(bytes0), _rt::string_lift(bytes1), super::super::super::super::exports::stringcheese::icu_case::types::TitleOptions{
        boundary: super::super::super::super::exports::stringcheese::icu_case::types::TitleBoundary::_lift(arg4 as u8),
        lowercase_tail: _rt::bool_lift(arg5 as u8),
      })
                        };
                        let ptr3 = (&raw mut _RET_AREA.0).cast::<u8>();
                        match result2 {
                            Ok(e) => {
                                *ptr3.add(0).cast::<u8>() = (0i32) as u8;
                                let vec4 = (e.into_bytes()).into_boxed_slice();
                                let ptr4 = vec4.as_ptr().cast::<u8>();
                                let len4 = vec4.len();
                                ::core::mem::forget(vec4);
                                *ptr3
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>() = len4;
                                *ptr3
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>() = ptr4.cast_mut();
                            }
                            Err(e) => {
                                *ptr3.add(0).cast::<u8>() = (1i32) as u8;
                                use super::super::super::super::exports::stringcheese::icu_case::types::CaseError as V8;
                                match e {
                                    V8::InvalidLocale(e) => {
                                        *ptr3
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<u8>() = (0i32) as u8;
                                        let vec5 = (e.into_bytes()).into_boxed_slice();
                                        let ptr5 = vec5.as_ptr().cast::<u8>();
                                        let len5 = vec5.len();
                                        ::core::mem::forget(vec5);
                                        *ptr3
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>() = len5;
                                        *ptr3
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>() = ptr5.cast_mut();
                                    }
                                    V8::LocaleUnavailable(e) => {
                                        *ptr3
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<u8>() = (1i32) as u8;
                                        let vec6 = (e.into_bytes()).into_boxed_slice();
                                        let ptr6 = vec6.as_ptr().cast::<u8>();
                                        let len6 = vec6.len();
                                        ::core::mem::forget(vec6);
                                        *ptr3
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>() = len6;
                                        *ptr3
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>() = ptr6.cast_mut();
                                    }
                                    V8::UnsupportedTitleMode(e) => {
                                        *ptr3
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<u8>() = (2i32) as u8;
                                        let vec7 = (e.into_bytes()).into_boxed_slice();
                                        let ptr7 = vec7.as_ptr().cast::<u8>();
                                        let len7 = vec7.len();
                                        ::core::mem::forget(vec7);
                                        *ptr3
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>() = len7;
                                        *ptr3
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>() = ptr7.cast_mut();
                                    }
                                }
                            }
                        };
                        ptr3
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_to_title<T_: Guest>(arg0: *mut u8) {
                    unsafe {
                        let l0 = i32::from(*arg0.add(0).cast::<u8>());
                        match l0 {
                            0 => {
                                let l1 = *arg0
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l2 = *arg0
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                _rt::cabi_dealloc(l1, l2, 1);
                            }
                            _ => {
                                let l3 = i32::from(
                                    *arg0.add(::core::mem::size_of::<*const u8>()).cast::<u8>(),
                                );
                                match l3 {
                                    0 => {
                                        let l4 = *arg0
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l5 = *arg0
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        _rt::cabi_dealloc(l4, l5, 1);
                                    }
                                    1 => {
                                        let l6 = *arg0
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l7 = *arg0
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        _rt::cabi_dealloc(l6, l7, 1);
                                    }
                                    _ => {
                                        let l8 = *arg0
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l9 = *arg0
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        _rt::cabi_dealloc(l8, l9, 1);
                                    }
                                }
                            }
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_fold_cabi<T_: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: i32,
                ) -> *mut u8 {
                    unsafe {
                        #[cfg(target_arch = "wasm32")]
                        _rt::run_ctors_once();
                        let result1 = {
                            let len0 = arg1;
                            let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                            T_::fold(_rt::string_lift(bytes0), super::super::super::super::exports::stringcheese::icu_case::types::FoldMode::_lift(arg2 as u8))
                        };
                        let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                        let vec3 = (result1.into_bytes()).into_boxed_slice();
                        let ptr3 = vec3.as_ptr().cast::<u8>();
                        let len3 = vec3.len();
                        ::core::mem::forget(vec3);
                        *ptr2
                            .add(::core::mem::size_of::<*const u8>())
                            .cast::<usize>() = len3;
                        *ptr2.add(0).cast::<*mut u8>() = ptr3.cast_mut();
                        ptr2
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_fold<T_: Guest>(arg0: *mut u8) {
                    unsafe {
                        let l0 = *arg0.add(0).cast::<*mut u8>();
                        let l1 = *arg0
                            .add(::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        _rt::cabi_dealloc(l0, l1, 1);
                    }
                }
                pub trait Guest {
                    /// Lowercase `input` under the given locale.
                    #[allow(async_fn_in_trait)]
                    fn to_lower(
                        input: _rt::String,
                        locale: Locale,
                    ) -> Result<_rt::String, CaseError>;
                    /// Uppercase `input` under the given locale.
                    #[allow(async_fn_in_trait)]
                    fn to_upper(
                        input: _rt::String,
                        locale: Locale,
                    ) -> Result<_rt::String, CaseError>;
                    /// Titlecase `input` under the given locale and options.
                    #[allow(async_fn_in_trait)]
                    fn to_title(
                        input: _rt::String,
                        locale: Locale,
                        options: TitleOptions,
                    ) -> Result<_rt::String, CaseError>;
                    /// Locale-*independent* case folding for case-insensitive matching.
                    /// Deterministic across packs.
                    #[allow(async_fn_in_trait)]
                    fn fold(input: _rt::String, mode: FoldMode) -> _rt::String;
                }
                #[doc(hidden)]

                macro_rules! __export_stringcheese_icu_case_mapping_0_1_0_cabi{
  ($ty:ident with_types_in $($path_to_types:tt)*) => (const _: () = {

    #[unsafe(export_name = "stringcheese:icu-case/mapping@0.1.0#to-lower")]
    unsafe extern "C" fn export_to_lower(arg0: *mut u8,arg1: usize,arg2: *mut u8,arg3: usize,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_to_lower_cabi::<$ty>(arg0, arg1, arg2, arg3) }
    }
    #[unsafe(export_name = "cabi_post_stringcheese:icu-case/mapping@0.1.0#to-lower")]
    unsafe extern "C" fn _post_return_to_lower(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_to_lower::<$ty>(arg0) }
    }
    #[unsafe(export_name = "stringcheese:icu-case/mapping@0.1.0#to-upper")]
    unsafe extern "C" fn export_to_upper(arg0: *mut u8,arg1: usize,arg2: *mut u8,arg3: usize,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_to_upper_cabi::<$ty>(arg0, arg1, arg2, arg3) }
    }
    #[unsafe(export_name = "cabi_post_stringcheese:icu-case/mapping@0.1.0#to-upper")]
    unsafe extern "C" fn _post_return_to_upper(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_to_upper::<$ty>(arg0) }
    }
    #[unsafe(export_name = "stringcheese:icu-case/mapping@0.1.0#to-title")]
    unsafe extern "C" fn export_to_title(arg0: *mut u8,arg1: usize,arg2: *mut u8,arg3: usize,arg4: i32,arg5: i32,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_to_title_cabi::<$ty>(arg0, arg1, arg2, arg3, arg4, arg5) }
    }
    #[unsafe(export_name = "cabi_post_stringcheese:icu-case/mapping@0.1.0#to-title")]
    unsafe extern "C" fn _post_return_to_title(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_to_title::<$ty>(arg0) }
    }
    #[unsafe(export_name = "stringcheese:icu-case/mapping@0.1.0#fold")]
    unsafe extern "C" fn export_fold(arg0: *mut u8,arg1: usize,arg2: i32,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_fold_cabi::<$ty>(arg0, arg1, arg2) }
    }
    #[unsafe(export_name = "cabi_post_stringcheese:icu-case/mapping@0.1.0#fold")]
    unsafe extern "C" fn _post_return_fold(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_fold::<$ty>(arg0) }
    }
  };);
}
                #[doc(hidden)]
                pub(crate) use __export_stringcheese_icu_case_mapping_0_1_0_cabi;

                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<u8>; 4 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 4 * ::core::mem::size_of::<*const u8>()],
                );
            }

            /// Introspection: which tailorings does the linked component actually
            /// cover? Callers use this to warn end-users that their locale falls
            /// back to root behaviour.
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod capabilities {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() =
                    super::super::super::super::__link_custom_section_describing_imports;

                use super::super::super::super::_rt;
                pub type Locale =
                    super::super::super::super::exports::stringcheese::icu_case::types::Locale;
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_supported_locales_cabi<T_: Guest>() -> *mut u8 {
                    unsafe {
                        #[cfg(target_arch = "wasm32")]
                        _rt::run_ctors_once();
                        let result0 = { T_::supported_locales() };
                        let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                        let vec3 = result0;
                        let len3 = vec3.len();
                        let layout3 = _rt::alloc::Layout::from_size_align(
                            vec3.len() * (2 * ::core::mem::size_of::<*const u8>()),
                            ::core::mem::size_of::<*const u8>(),
                        )
                        .unwrap();
                        let (result3, _cleanup3) = wit_bindgen_rt::Cleanup::new(layout3);
                        if let Some(cleanup) = _cleanup3 {
                            cleanup.forget();
                        }
                        for (i, e) in vec3.into_iter().enumerate() {
                            let base = result3.add(i * (2 * ::core::mem::size_of::<*const u8>()));
                            {
                                let vec2 = (e.into_bytes()).into_boxed_slice();
                                let ptr2 = vec2.as_ptr().cast::<u8>();
                                let len2 = vec2.len();
                                ::core::mem::forget(vec2);
                                *base
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<usize>() = len2;
                                *base.add(0).cast::<*mut u8>() = ptr2.cast_mut();
                            }
                        }
                        *ptr1
                            .add(::core::mem::size_of::<*const u8>())
                            .cast::<usize>() = len3;
                        *ptr1.add(0).cast::<*mut u8>() = result3;
                        ptr1
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_supported_locales<T_: Guest>(arg0: *mut u8) {
                    unsafe {
                        let l0 = *arg0.add(0).cast::<*mut u8>();
                        let l1 = *arg0
                            .add(::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let base4 = l0;
                        let len4 = l1;
                        for i in 0..len4 {
                            let base = base4.add(i * (2 * ::core::mem::size_of::<*const u8>()));
                            {
                                let l2 = *base.add(0).cast::<*mut u8>();
                                let l3 = *base
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                _rt::cabi_dealloc(l2, l3, 1);
                            }
                        }
                        _rt::cabi_dealloc(
                            base4,
                            len4 * (2 * ::core::mem::size_of::<*const u8>()),
                            ::core::mem::size_of::<*const u8>(),
                        );
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_supports_cabi<T_: Guest>(arg0: *mut u8, arg1: usize) -> i32 {
                    unsafe {
                        #[cfg(target_arch = "wasm32")]
                        _rt::run_ctors_once();
                        let result1 = {
                            let len0 = arg1;
                            let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                            T_::supports(_rt::string_lift(bytes0))
                        };
                        match result1 {
                            true => 1,
                            false => 0,
                        }
                    }
                }
                pub trait Guest {
                    /// Every BCP 47 tag this component's linked packs cover.
                    #[allow(async_fn_in_trait)]
                    fn supported_locales() -> _rt::Vec<Locale>;
                    /// True iff a query in the given locale would use a pack (rather
                    /// than falling through to root).
                    #[allow(async_fn_in_trait)]
                    fn supports(loc: Locale) -> bool;
                }
                #[doc(hidden)]

                macro_rules! __export_stringcheese_icu_case_capabilities_0_1_0_cabi{
  ($ty:ident with_types_in $($path_to_types:tt)*) => (const _: () = {

    #[unsafe(export_name = "stringcheese:icu-case/capabilities@0.1.0#supported-locales")]
    unsafe extern "C" fn export_supported_locales() -> *mut u8 {
      unsafe { $($path_to_types)*::_export_supported_locales_cabi::<$ty>() }
    }
    #[unsafe(export_name = "cabi_post_stringcheese:icu-case/capabilities@0.1.0#supported-locales")]
    unsafe extern "C" fn _post_return_supported_locales(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_supported_locales::<$ty>(arg0) }
    }
    #[unsafe(export_name = "stringcheese:icu-case/capabilities@0.1.0#supports")]
    unsafe extern "C" fn export_supports(arg0: *mut u8,arg1: usize,) -> i32 {
      unsafe { $($path_to_types)*::_export_supports_cabi::<$ty>(arg0, arg1) }
    }
  };);
}
                #[doc(hidden)]
                pub(crate) use __export_stringcheese_icu_case_capabilities_0_1_0_cabi;

                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<u8>; 2 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 2 * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
mod _rt {
    #![allow(dead_code, unused_imports, clippy::all)]
    pub use alloc_crate::string::String;

    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub use alloc_crate::vec::Vec;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            unsafe { String::from_utf8_unchecked(bytes) }
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        unsafe {
            let layout = alloc::Layout::from_size_align_unchecked(size, align);
            alloc::dealloc(ptr, layout);
        }
    }
    pub unsafe fn bool_lift(val: u8) -> bool {
        if cfg!(debug_assertions) {
            match val {
                0 => false,
                1 => true,
                _ => panic!("invalid bool discriminant"),
            }
        } else {
            val != 0
        }
    }
    pub use alloc_crate::alloc;
    extern crate alloc as alloc_crate;
}

/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]

macro_rules! __export_case_impl {
  ($ty:ident) => (self::export!($ty with_types_in self););
  ($ty:ident with_types_in $($path_to_types_root:tt)*) => (
  $($path_to_types_root)*::exports::stringcheese::icu_case::types::__export_stringcheese_icu_case_types_0_1_0_cabi!($ty with_types_in $($path_to_types_root)*::exports::stringcheese::icu_case::types);
  $($path_to_types_root)*::exports::stringcheese::icu_case::mapping::__export_stringcheese_icu_case_mapping_0_1_0_cabi!($ty with_types_in $($path_to_types_root)*::exports::stringcheese::icu_case::mapping);
  $($path_to_types_root)*::exports::stringcheese::icu_case::capabilities::__export_stringcheese_icu_case_capabilities_0_1_0_cabi!($ty with_types_in $($path_to_types_root)*::exports::stringcheese::icu_case::capabilities);
  )
}
#[doc(inline)]
pub(crate) use __export_case_impl as export;

#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.60.0:stringcheese:icu-case@0.1.0:case:encoded world")]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 867] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xe8\x05\x01A\x02\x01\
A\x0a\x01B\x0a\x01s\x04\0\x06locale\x03\0\0\x01q\x03\x0einvalid-locale\x01s\0\x12\
locale-unavailable\x01s\0\x16unsupported-title-mode\x01s\0\x04\0\x0acase-error\x03\
\0\x02\x01m\x03\x06simple\x04full\x0bfull-turkic\x04\0\x09fold-mode\x03\0\x04\x01\
m\x03\x09graphemes\x05words\x09sentences\x04\0\x0etitle-boundary\x03\0\x06\x01r\x02\
\x08boundary\x07\x0elowercase-tail\x7f\x04\0\x0dtitle-options\x03\0\x08\x04\0!st\
ringcheese:icu-case/types@0.1.0\x05\0\x02\x03\0\0\x06locale\x02\x03\0\0\x0acase-\
error\x02\x03\0\0\x09fold-mode\x02\x03\0\0\x0dtitle-options\x01B\x10\x02\x03\x02\
\x01\x01\x04\0\x06locale\x03\0\0\x02\x03\x02\x01\x02\x04\0\x0acase-error\x03\0\x02\
\x02\x03\x02\x01\x03\x04\0\x09fold-mode\x03\0\x04\x02\x03\x02\x01\x04\x04\0\x0dt\
itle-options\x03\0\x06\x01j\x01s\x01\x03\x01@\x02\x05inputs\x06locale\x01\0\x08\x04\
\0\x08to-lower\x01\x09\x04\0\x08to-upper\x01\x09\x01@\x03\x05inputs\x06locale\x01\
\x07options\x07\0\x08\x04\0\x08to-title\x01\x0a\x01@\x02\x05inputs\x04mode\x05\0\
s\x04\0\x04fold\x01\x0b\x04\0#stringcheese:icu-case/mapping@0.1.0\x05\x05\x01B\x07\
\x02\x03\x02\x01\x01\x04\0\x06locale\x03\0\0\x01p\x01\x01@\0\0\x02\x04\0\x11supp\
orted-locales\x01\x03\x01@\x01\x03loc\x01\0\x7f\x04\0\x08supports\x01\x04\x04\0(\
stringcheese:icu-case/capabilities@0.1.0\x05\x06\x04\0\x20stringcheese:icu-case/\
case@0.1.0\x04\0\x0b\x0a\x01\0\x04case\x03\0\0\0G\x09producers\x01\x0cprocessed-\
by\x02\x0dwit-component\x070.254.0\x10wit-bindgen-rust\x060.60.0";

#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
