//! Wasmtime smoke test for the reference
//! `tegmentum:i18n-segment@0.1.0` component.
//!
//! Verifies WIT-i18n Phase 5's componentised WASM build
//! (`docs/design/wit-i18n.md` § 8.5). The test drives the
//! component the same way any external caller would: builds it
//! under `wasm32-wasip1 --features wit-component`, componentises
//! it via `wasm-tools`, then loads the componentised `.wasm` into
//! an in-process wasmtime `Engine` and calls each of the WIT
//! exports through typed bindings generated by
//! `wasmtime::component::bindgen!` from the shipped WIT file.
//!
//! # Prerequisites
//!
//! Requires `cargo` with `wasm32-wasip1` installed plus
//! `wasm-tools` on `$PATH`, and one WASI preview1 → preview2
//! adapter file discoverable via [`find_wasi_adapter`]. Missing
//! prerequisites soft-skip the test.

#![cfg(not(target_family = "wasm"))]
#![allow(unsafe_code)]

use std::path::PathBuf;
use std::process::Command;
use std::sync::OnceLock;

use wasmtime::component::{Component, Linker, ResourceTable};
use wasmtime::{Engine, Store};
use wasmtime_wasi::{WasiCtx, WasiCtxBuilder, WasiCtxView, WasiView};

// Typed bindings generated from the shipped WIT contract. The
// macro mirrors the `segment-world` world the guest crate
// exports, but from the host side — the generated
// `SegmentWorld` struct is what we instantiate against a linker
// below, and its `tegmentum_i18n_segment_*()` accessors return
// typed handles to the exported interfaces. Wrapping in a module
// lets us scope a single `#[allow(missing_docs)]` around the
// generated code.
#[allow(missing_docs, clippy::pedantic, clippy::nursery)]
mod bindgen {
    wasmtime::component::bindgen!({
        world: "segment-world",
        path: "../../component/wit/segment",
    });
}

use bindgen::SegmentWorld;
use bindgen::exports::tegmentum::i18n_segment::types::WordSegment as WitWordSegment;

/// Host state carried in the `Store<T>`. Holds the WASI preview2
/// context and a `ResourceTable` for any WASI resources
/// instantiated during a call. The segment component never
/// touches either — it performs no I/O — but a `WasiView` impl
/// is still required so the linker can wire the imported
/// `wasi:*` interfaces exposed by the wasip1 → wasip2 adapter.
struct HostState {
    table: ResourceTable,
    wasi: WasiCtx,
}

impl WasiView for HostState {
    fn ctx(&mut self) -> WasiCtxView<'_> {
        WasiCtxView {
            ctx: &mut self.wasi,
            table: &mut self.table,
        }
    }
}

/// One end-to-end build-and-load: shell out to `cargo build` +
/// `wasm-tools component new` once, load the resulting `.wasm`
/// into a wasmtime `Engine`, and cache the immutable
/// engine/component/linker on the shared `OnceLock` so every test
/// instantiates cheaply.
struct SmokeHarness {
    engine: Engine,
    component: Component,
    linker: Linker<HostState>,
}

/// See the collation-component smoke test for the shared-once
/// concurrency rationale.
static SHARED_COMPONENT: OnceLock<Option<PathBuf>> = OnceLock::new();

impl SmokeHarness {
    fn build_or_skip() -> Option<Self> {
        let component_wasm = SHARED_COMPONENT
            .get_or_init(Self::build_shared_once)
            .clone()?;

        let engine = Engine::default();
        let component = match Component::from_file(&engine, &component_wasm) {
            Ok(c) => c,
            Err(e) => {
                eprintln!(
                    "SKIP: wasmtime failed to load component at {}: {e}",
                    component_wasm.display()
                );
                return None;
            }
        };
        let mut linker: Linker<HostState> = Linker::new(&engine);
        if let Err(e) = wasmtime_wasi::p2::add_to_linker_sync(&mut linker) {
            eprintln!("SKIP: could not add WASI to linker: {e}");
            return None;
        }
        Some(Self {
            engine,
            component,
            linker,
        })
    }

    fn build_shared_once() -> Option<PathBuf> {
        if !has_tool("cargo") {
            eprintln!("SKIP: cargo not on PATH");
            return None;
        }
        if !has_tool("wasm-tools") {
            eprintln!(
                "SKIP: wasm-tools not on PATH — install from https://github.com/bytecodealliance/wasm-tools"
            );
            return None;
        }
        if !target_installed("wasm32-wasip1") {
            eprintln!(
                "SKIP: wasm32-wasip1 target not installed — `rustup target add wasm32-wasip1`"
            );
            return None;
        }

        let workspace_root = workspace_root();
        let build = Command::new("cargo")
            .current_dir(&workspace_root)
            .args([
                "build",
                "-p",
                "stringcheese-icu-segment-component",
                "--target",
                "wasm32-wasip1",
                "--features",
                "wit-component",
                "--release",
            ])
            .status()
            .expect("cargo build must launch");
        assert!(
            build.success(),
            "cargo build for wasm32-wasip1 must succeed",
        );

        let module_wasm = workspace_root
            .join("target/wasm32-wasip1/release/stringcheese_icu_segment_component.wasm");
        assert!(
            module_wasm.exists(),
            "expected wasm at {} after cargo build",
            module_wasm.display(),
        );

        let Some(adapter) = find_wasi_adapter() else {
            eprintln!(
                "SKIP: no wasi_snapshot_preview1.reactor.wasm adapter found on the search path"
            );
            return None;
        };

        let component_wasm = std::env::temp_dir().join("stringcheese_icu_segment_component.wasm");
        let componentize = Command::new("wasm-tools")
            .args([
                "component",
                "new",
                module_wasm.to_str().expect("path is utf8"),
                "--adapt",
                adapter.to_str().expect("adapter path is utf8"),
                "-o",
                component_wasm.to_str().expect("output path is utf8"),
            ])
            .status()
            .expect("wasm-tools must launch");
        assert!(
            componentize.success(),
            "wasm-tools component new must succeed",
        );
        assert!(
            component_wasm.exists(),
            "expected component at {}",
            component_wasm.display(),
        );
        Some(component_wasm)
    }

    fn instantiate(&self) -> (Store<HostState>, SegmentWorld) {
        let mut store = Store::new(
            &self.engine,
            HostState {
                table: ResourceTable::new(),
                wasi: WasiCtxBuilder::new().build(),
            },
        );
        let bindings = SegmentWorld::instantiate(&mut store, &self.component, &self.linker)
            .expect("component must instantiate against the wasmtime-wasi linker");
        (store, bindings)
    }
}

fn has_tool(name: &str) -> bool {
    Command::new(name)
        .arg("--version")
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status()
        .is_ok_and(|s| s.success())
}

fn target_installed(triple: &str) -> bool {
    let out = Command::new("rustup")
        .args(["target", "list", "--installed"])
        .output();
    match out {
        Ok(o) if o.status.success() => String::from_utf8_lossy(&o.stdout)
            .lines()
            .any(|l| l.trim() == triple),
        _ => true,
    }
}

fn workspace_root() -> PathBuf {
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    manifest
        .parent()
        .and_then(|p| p.parent())
        .expect("workspace root is two levels above crate manifest")
        .to_path_buf()
}

fn find_wasi_adapter() -> Option<PathBuf> {
    if let Ok(p) = std::env::var("STRINGCHEESE_WASI_ADAPTER") {
        let path = PathBuf::from(p);
        if path.exists() {
            return Some(path);
        }
    }
    let home = std::env::var_os("HOME").map(PathBuf::from)?;
    let cache =
        home.join(".cache/stringcheese-tokenizer-component/wasi_snapshot_preview1.reactor.wasm");
    if cache.exists() {
        return Some(cache);
    }
    walk_for_adapter(&home.join(".cargo/registry/src")).next()
}

fn walk_for_adapter(root: &std::path::Path) -> impl Iterator<Item = PathBuf> {
    let mut out = Vec::new();
    if let Ok(entries) = std::fs::read_dir(root) {
        for entry in entries.flatten() {
            let path = entry.path();
            let candidate = path.join("cargo-component/wasi_snapshot_preview1.reactor.wasm");
            if candidate.exists() {
                out.push(candidate);
            }
        }
    }
    out.into_iter()
}

/// Helper — the WIT `type locale = string` alias is rendered as
/// an owned `String` by `wasmtime::component::bindgen!`.
fn loc(tag: &str) -> String {
    tag.to_string()
}

// -----------------------------------------------------------------------
// Grapheme boundary smoke tests.
// -----------------------------------------------------------------------

#[test]
fn wasmtime_smoke_segment_graphemes_ascii_letters() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let segment = bindings.tegmentum_i18n_segment_segment();
    let bs = segment
        .call_segment_graphemes(&mut store, "abc")
        .expect("segment-graphemes trap-free");
    // Three ASCII letters => 4 boundaries at 0,1,2,3.
    assert_eq!(bs, vec![0, 1, 2, 3]);
}

#[test]
fn wasmtime_smoke_segment_graphemes_empty_returns_single_zero() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let segment = bindings.tegmentum_i18n_segment_segment();
    let bs = segment
        .call_segment_graphemes(&mut store, "")
        .expect("segment-graphemes trap-free");
    assert_eq!(bs, vec![0]);
}

#[test]
fn wasmtime_smoke_segment_graphemes_crlf_stays_together() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let segment = bindings.tegmentum_i18n_segment_segment();
    // GB3: CR × LF is a single grapheme.
    let bs = segment
        .call_segment_graphemes(&mut store, "a\r\nb")
        .expect("segment-graphemes trap-free");
    assert_eq!(bs, vec![0, 1, 3, 4]);
}

#[test]
fn wasmtime_smoke_segment_graphemes_family_emoji_is_one_grapheme() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let segment = bindings.tegmentum_i18n_segment_segment();
    // Man + ZWJ + Woman + ZWJ + Girl = one grapheme under UAX #29
    // GB11 (\p{ExtPict} Extend* ZWJ × \p{ExtPict}).
    let s = "\u{1F468}\u{200D}\u{1F469}\u{200D}\u{1F467}";
    let bs = segment
        .call_segment_graphemes(&mut store, s)
        .expect("segment-graphemes trap-free");
    assert_eq!(bs, vec![0, u32::try_from(s.len()).unwrap()]);
}

// -----------------------------------------------------------------------
// Word boundary smoke tests.
// -----------------------------------------------------------------------

#[test]
fn wasmtime_smoke_segment_words_ascii_with_punctuation() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let segment = bindings.tegmentum_i18n_segment_segment();
    // "hello, world" — two word-like segments ("hello" @ 0..5,
    // "world" @ 7..12) plus non-word segments between them
    // (comma + space). The exact non-word split depends on UAX
    // #29 default rules; we assert the word-like segments only.
    let out = segment
        .call_segment_words(&mut store, "hello, world", &loc(""))
        .expect("segment-words trap-free");
    let word_like: Vec<&WitWordSegment> = out.iter().filter(|s| s.is_word_like).collect();
    assert_eq!(word_like.len(), 2, "expected 2 word-like segments: {out:?}");
    assert_eq!(word_like[0].start, 0);
    assert_eq!(word_like[0].end, 5);
    assert_eq!(word_like[1].start, 7);
    assert_eq!(word_like[1].end, 12);
    // Every segment covers the input contiguously.
    assert_eq!(out.first().map(|s| s.start), Some(0));
    assert_eq!(out.last().map(|s| s.end), Some(12));
}

// -----------------------------------------------------------------------
// Sentence boundary smoke tests.
// -----------------------------------------------------------------------

#[test]
fn wasmtime_smoke_segment_sentences_two_sentences() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let segment = bindings.tegmentum_i18n_segment_segment();
    let bs = segment
        .call_segment_sentences(&mut store, "Hi. Bye.", &loc(""))
        .expect("segment-sentences trap-free");
    // Leading 0, trailing 8 (byte length), plus at least one
    // interior boundary between the two sentences.
    assert_eq!(bs.first(), Some(&0));
    assert_eq!(bs.last(), Some(&8));
    assert!(bs.len() >= 3, "expected >=3 boundaries: {bs:?}");
}

// -----------------------------------------------------------------------
// Capabilities smoke tests.
// -----------------------------------------------------------------------

#[test]
fn wasmtime_smoke_supported_locales_lists_root_marker() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let caps = bindings.tegmentum_i18n_segment_capabilities();
    let locales = caps
        .call_supported_locales(&mut store)
        .expect("supported-locales trap-free");
    // Phase 5 ships the root-locale marker only.
    assert_eq!(locales, vec![String::new()]);
}

#[test]
fn wasmtime_smoke_supports_returns_true_for_every_locale() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let caps = bindings.tegmentum_i18n_segment_capabilities();
    // Phase 5 always falls through to the default rules; the
    // algorithm crate's `supports` returns true for every input
    // for forward compatibility.
    for tag in ["", "en", "ja", "fr-CA", "xx"] {
        let ok = caps
            .call_supports(&mut store, &loc(tag))
            .expect("supports trap-free");
        assert!(ok, "supports({tag:?}) should be true under Phase 5");
    }
}
