//! Wasmtime smoke test for the reference
//! `tegmentum:i18n-datetime@0.1.0` component.
//!
//! Verifies WIT-i18n Phase 4's componentised WASM build
//! (`docs/design/wit-i18n.md` § 8.4). The test drives the
//! component the same way any external caller would: builds it
//! under `wasm32-wasip1 --features wit-component`, componentises
//! it via `wasm-tools`, then loads the componentised `.wasm` into
//! an in-process wasmtime `Engine` and calls each of the WIT
//! exports through typed bindings generated by
//! `wasmtime::component::bindgen!` from the shipped WIT file.
//!
//! # Prerequisites
//!
//! Requires `cargo` with `wasm32-wasip1` installed plus
//! `wasm-tools` on `$PATH`, and one WASI preview1 → preview2
//! adapter file discoverable via [`find_wasi_adapter`]. Missing
//! prerequisites soft-skip the test.

#![cfg(not(target_family = "wasm"))]
#![allow(unsafe_code)]

use std::path::PathBuf;
use std::process::Command;
use std::sync::OnceLock;

use wasmtime::component::{Component, Linker, ResourceTable};
use wasmtime::{Engine, Store};
use wasmtime_wasi::{WasiCtx, WasiCtxBuilder, WasiView};

// Typed bindings generated from the shipped WIT contract.
#[allow(missing_docs, clippy::pedantic, clippy::nursery)]
mod bindgen {
    wasmtime::component::bindgen!({
        world: "datetime-world",
        path: "../../component/wit/datetime",
    });
}

use bindgen::DatetimeWorld;
use bindgen::exports::tegmentum::i18n_datetime::types::{
    DateLength as WitDateLength, DatetimeError as WitError, TimeLength as WitTimeLength,
};

struct HostState {
    table: ResourceTable,
    wasi: WasiCtx,
}

impl WasiView for HostState {
    fn ctx(&mut self) -> &mut WasiCtx {
        &mut self.wasi
    }
    fn table(&mut self) -> &mut ResourceTable {
        &mut self.table
    }
}

struct SmokeHarness {
    engine: Engine,
    component: Component,
    linker: Linker<HostState>,
}

/// See the collation-component smoke test for the shared-once
/// concurrency rationale.
static SHARED_COMPONENT: OnceLock<Option<PathBuf>> = OnceLock::new();

impl SmokeHarness {
    fn build_or_skip() -> Option<Self> {
        let component_wasm = SHARED_COMPONENT
            .get_or_init(Self::build_shared_once)
            .clone()?;

        let engine = Engine::default();
        let component = match Component::from_file(&engine, &component_wasm) {
            Ok(c) => c,
            Err(e) => {
                eprintln!(
                    "SKIP: wasmtime failed to load component at {}: {e}",
                    component_wasm.display()
                );
                return None;
            }
        };
        let mut linker: Linker<HostState> = Linker::new(&engine);
        if let Err(e) = wasmtime_wasi::add_to_linker_sync(&mut linker) {
            eprintln!("SKIP: could not add WASI to linker: {e}");
            return None;
        }
        Some(Self {
            engine,
            component,
            linker,
        })
    }

    fn build_shared_once() -> Option<PathBuf> {
        if !has_tool("cargo") {
            eprintln!("SKIP: cargo not on PATH");
            return None;
        }
        if !has_tool("wasm-tools") {
            eprintln!(
                "SKIP: wasm-tools not on PATH — install from https://github.com/bytecodealliance/wasm-tools"
            );
            return None;
        }
        if !target_installed("wasm32-wasip1") {
            eprintln!(
                "SKIP: wasm32-wasip1 target not installed — `rustup target add wasm32-wasip1`"
            );
            return None;
        }

        let workspace_root = workspace_root();
        let build = Command::new("cargo")
            .current_dir(&workspace_root)
            .args([
                "build",
                "-p",
                "stringcheese-icu-datetime-component",
                "--target",
                "wasm32-wasip1",
                "--features",
                "wit-component",
                "--release",
            ])
            .status()
            .expect("cargo build must launch");
        assert!(
            build.success(),
            "cargo build for wasm32-wasip1 must succeed",
        );

        let module_wasm = workspace_root
            .join("target/wasm32-wasip1/release/stringcheese_icu_datetime_component.wasm");
        assert!(
            module_wasm.exists(),
            "expected wasm at {} after cargo build",
            module_wasm.display(),
        );

        let Some(adapter) = find_wasi_adapter() else {
            eprintln!(
                "SKIP: no wasi_snapshot_preview1.reactor.wasm adapter found on the search path"
            );
            return None;
        };

        let component_wasm = std::env::temp_dir().join("stringcheese_icu_datetime_component.wasm");
        let componentize = Command::new("wasm-tools")
            .args([
                "component",
                "new",
                module_wasm.to_str().expect("path is utf8"),
                "--adapt",
                adapter.to_str().expect("adapter path is utf8"),
                "-o",
                component_wasm.to_str().expect("output path is utf8"),
            ])
            .status()
            .expect("wasm-tools must launch");
        assert!(
            componentize.success(),
            "wasm-tools component new must succeed",
        );
        assert!(
            component_wasm.exists(),
            "expected component at {}",
            component_wasm.display(),
        );
        Some(component_wasm)
    }

    fn instantiate(&self) -> (Store<HostState>, DatetimeWorld) {
        let mut store = Store::new(
            &self.engine,
            HostState {
                table: ResourceTable::new(),
                wasi: WasiCtxBuilder::new().build(),
            },
        );
        let bindings = DatetimeWorld::instantiate(&mut store, &self.component, &self.linker)
            .expect("component must instantiate against the wasmtime-wasi linker");
        (store, bindings)
    }
}

fn has_tool(name: &str) -> bool {
    Command::new(name)
        .arg("--version")
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status()
        .is_ok_and(|s| s.success())
}

fn target_installed(triple: &str) -> bool {
    let out = Command::new("rustup")
        .args(["target", "list", "--installed"])
        .output();
    match out {
        Ok(o) if o.status.success() => String::from_utf8_lossy(&o.stdout)
            .lines()
            .any(|l| l.trim() == triple),
        _ => true,
    }
}

fn workspace_root() -> PathBuf {
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    manifest
        .parent()
        .and_then(|p| p.parent())
        .expect("workspace root is two levels above crate manifest")
        .to_path_buf()
}

fn find_wasi_adapter() -> Option<PathBuf> {
    if let Ok(p) = std::env::var("STRINGCHEESE_WASI_ADAPTER") {
        let path = PathBuf::from(p);
        if path.exists() {
            return Some(path);
        }
    }
    let home = std::env::var_os("HOME").map(PathBuf::from)?;
    let cache =
        home.join(".cache/stringcheese-tokenizer-component/wasi_snapshot_preview1.reactor.wasm");
    if cache.exists() {
        return Some(cache);
    }
    walk_for_adapter(&home.join(".cargo/registry/src")).next()
}

fn walk_for_adapter(root: &std::path::Path) -> impl Iterator<Item = PathBuf> {
    let mut out = Vec::new();
    if let Ok(entries) = std::fs::read_dir(root) {
        for entry in entries.flatten() {
            let path = entry.path();
            let candidate = path.join("cargo-component/wasi_snapshot_preview1.reactor.wasm");
            if candidate.exists() {
                out.push(candidate);
            }
        }
    }
    out.into_iter()
}

fn describe_err(e: &WitError) -> String {
    match e {
        WitError::InvalidLocale(s) => format!("invalid-locale({s:?})"),
        WitError::LocaleUnavailable(s) => format!("locale-unavailable({s:?})"),
        WitError::InvalidInput(s) => format!("invalid-input({s:?})"),
        WitError::OutOfRange(s) => format!("out-of-range({s:?})"),
    }
}

fn loc(tag: &str) -> String {
    tag.to_string()
}

#[test]
fn wasmtime_smoke_format_date_english_medium() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let datetime = bindings.tegmentum_i18n_datetime_datetime();
    let out = datetime
        .call_format_date(&mut store, "2024-09-22", &loc("en"), WitDateLength::Medium)
        .expect("format-date trap-free")
        .unwrap_or_else(|e| panic!("format-date returned error: {}", describe_err(&e)));
    assert_eq!(out, "Sep 22, 2024");
}

#[test]
fn wasmtime_smoke_format_date_german_short() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let datetime = bindings.tegmentum_i18n_datetime_datetime();
    let out = datetime
        .call_format_date(&mut store, "2024-09-22", &loc("de"), WitDateLength::Short)
        .expect("format-date trap-free")
        .unwrap_or_else(|e| panic!("format-date returned error: {}", describe_err(&e)));
    assert_eq!(out, "22.09.2024");
}

#[test]
fn wasmtime_smoke_format_date_french_full_lowercase_weekday() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let datetime = bindings.tegmentum_i18n_datetime_datetime();
    let out = datetime
        .call_format_date(&mut store, "2024-09-22", &loc("fr"), WitDateLength::Full)
        .expect("format-date trap-free")
        .unwrap_or_else(|e| panic!("format-date returned error: {}", describe_err(&e)));
    assert_eq!(out, "dimanche 22 septembre 2024");
}

#[test]
fn wasmtime_smoke_format_time_english_am_pm() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let datetime = bindings.tegmentum_i18n_datetime_datetime();
    let out = datetime
        .call_format_time(&mut store, "17:03:04", &loc("en"), WitTimeLength::Short)
        .expect("format-time trap-free")
        .unwrap_or_else(|e| panic!("format-time returned error: {}", describe_err(&e)));
    assert_eq!(out, "5:03 PM");
}

#[test]
fn wasmtime_smoke_format_datetime_combined() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let datetime = bindings.tegmentum_i18n_datetime_datetime();
    let out = datetime
        .call_format_datetime(
            &mut store,
            "2024-09-22T17:03:04Z",
            &loc("en"),
            WitDateLength::Medium,
            WitTimeLength::Short,
        )
        .expect("format-datetime trap-free")
        .unwrap_or_else(|e| panic!("format-datetime returned error: {}", describe_err(&e)));
    assert_eq!(out, "Sep 22, 2024 5:03 PM");
}

#[test]
fn wasmtime_smoke_supported_locales_lists_bundled_tags() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let caps = bindings.tegmentum_i18n_datetime_capabilities();
    let locales = caps
        .call_supported_locales(&mut store)
        .expect("supported-locales trap-free");
    assert_eq!(
        locales,
        vec!["en".to_string(), "de".to_string(), "fr".to_string()],
    );
}

#[test]
fn wasmtime_smoke_supports_falls_through_bcp47_chain() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let caps = bindings.tegmentum_i18n_datetime_capabilities();
    let ok = caps
        .call_supports(&mut store, &loc("fr-CA"))
        .expect("supports trap-free");
    assert!(ok, "fr-CA should resolve via BCP 47 fallback to fr");
    let missing = caps
        .call_supports(&mut store, &loc("xx"))
        .expect("supports trap-free");
    assert!(!missing, "xx is not in the bundled pack set");
}
