// Generated by `wit-bindgen` 0.60.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod tegmentum {
        pub mod tokenizer {

            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod tokenizer {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() =
                    super::super::super::super::__link_custom_section_describing_imports;

                use super::super::super::super::_rt;
                /// Vocabulary index. `u32` is large enough for every tokenizer the
                /// StringCheese subsystem ships (o200k_base's ~200 000 ids being
                /// the current maximum) and matches the tiktoken / HuggingFace
                /// convention.
                pub type TokenId = u32;
                /// Half-open byte range in the pre-normalization input. `start`
                /// and `end` are both byte offsets; `end` is exclusive. A caller
                /// who wants to highlight or slice the input by the emitted token
                /// span uses these coordinates directly.
                #[repr(C)]
                #[derive(Clone, Copy)]
                pub struct Range {
                    pub start: u32,
                    pub end: u32,
                }
                impl ::core::fmt::Debug for Range {
                    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                        f.debug_struct("Range")
                            .field("start", &self.start)
                            .field("end", &self.end)
                            .finish()
                    }
                }
                /// The full output of an `encode` call.
                ///
                /// Every non-empty per-token array is guaranteed to have the same
                /// length as `ids`. A tokenizer that does not track a particular
                /// axis returns an empty vector for it — the WIT contract is
                /// "either fully populated or absent", never partial.
                ///
                /// * `ids` — the token IDs in emission order.
                /// * `offsets` — half-open byte range in the input per token. Empty
                ///   when the tokenizer does not track offsets.
                /// * `special-mask` — one flag per token; `true` iff the id is one
                ///   of the tokenizer's registered special tokens. Empty when not
                ///   tracked.
                /// * `type-ids` — segment id per token (`0` for the `A` slot of a
                ///   pair, `1` for `B`; always `0` for a single-side encode).
                ///   Empty when not tracked.
                /// * `attention-mask` — `true` for real tokens, `false` for pad
                ///   tokens (populated by `pad-batch` at the caller side). Empty
                ///   when not tracked.
                #[derive(Clone)]
                pub struct Encoding {
                    pub ids: _rt::Vec<TokenId>,
                    pub offsets: _rt::Vec<Range>,
                    pub special_mask: _rt::Vec<bool>,
                    pub type_ids: _rt::Vec<u32>,
                    pub attention_mask: _rt::Vec<bool>,
                }
                impl ::core::fmt::Debug for Encoding {
                    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                        f.debug_struct("Encoding")
                            .field("ids", &self.ids)
                            .field("offsets", &self.offsets)
                            .field("special-mask", &self.special_mask)
                            .field("type-ids", &self.type_ids)
                            .field("attention-mask", &self.attention_mask)
                            .finish()
                    }
                }
                /// Typed failure modes. Narrow rather than open so a caller can
                /// decide at source level how to react to each variant. Mirrors
                /// the shape of `stringcheese_tokenizer::TokenizerError`.
                #[derive(Clone)]
                pub enum TokenizerError {
                    /// The input contained a byte sequence that is not valid UTF-8,
                    /// or the decode side produced bytes that no longer form valid
                    /// UTF-8.
                    InvalidUtf8,
                    /// A surface string (encode) or token id (decode) was not
                    /// present in the vocabulary and no fallback is configured.
                    /// Payload is the offending surface form.
                    UnknownToken(_rt::String),
                    /// The input contained a special-token surface string that the
                    /// caller's policy rejects. Payload is the offending string.
                    DisallowedSpecialToken(_rt::String),
                    /// A merge table, vocabulary, or special-token map is
                    /// internally inconsistent.
                    VocabularyMismatch,
                    /// A domain-specific failure that does not fit the fixed
                    /// variants. Payload carries a short human-readable message.
                    Other(_rt::String),
                }
                impl ::core::fmt::Debug for TokenizerError {
                    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                        match self {
                            TokenizerError::InvalidUtf8 => {
                                f.debug_tuple("TokenizerError::InvalidUtf8").finish()
                            }
                            TokenizerError::UnknownToken(e) => f
                                .debug_tuple("TokenizerError::UnknownToken")
                                .field(e)
                                .finish(),
                            TokenizerError::DisallowedSpecialToken(e) => f
                                .debug_tuple("TokenizerError::DisallowedSpecialToken")
                                .field(e)
                                .finish(),
                            TokenizerError::VocabularyMismatch => {
                                f.debug_tuple("TokenizerError::VocabularyMismatch").finish()
                            }
                            TokenizerError::Other(e) => {
                                f.debug_tuple("TokenizerError::Other").field(e).finish()
                            }
                        }
                    }
                }
                impl ::core::fmt::Display for TokenizerError {
                    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                        write!(f, "{:?}", self)
                    }
                }

                impl ::core::error::Error for TokenizerError {}
                /// Static description of the backend's identity and vocabulary.
                /// Cheap; safe to call once at load time and cache.
                ///
                /// The two boolean fields advertise runtime capabilities the caller
                /// can dispatch on: `has-byte-fallback` says whether OOV inputs
                /// route through `<0xXX>` reserved tokens (Llama / Mistral shape)
                /// rather than surfacing an `unknown-token` error; `has-special-tokens`
                /// says whether the tokenizer has any special-token surface strings
                /// at all (bare BPE trained without them will not).
                #[derive(Clone)]
                pub struct Capabilities {
                    /// Backend identifier — "bpe" | "wordpiece" | "unigram" | "wordlevel".
                    /// Matches the `model.type` field of a HuggingFace tokenizer.json.
                    pub model_type: _rt::String,
                    /// A stable variant identifier — "cl100k_base", "o200k_base",
                    /// "gpt2", "llama-2-7b", …, or the HF config's declared model
                    /// name for tokenizer.json-loaded packs. Empty when the
                    /// backend has no canonical name.
                    pub variant_id: _rt::String,
                    /// Semver of the backend's model / algorithm corpus.
                    pub version: _rt::String,
                    /// Total number of ids in the vocabulary (including special
                    /// tokens).
                    pub vocab_size: u32,
                    /// `true` when OOV inputs are routed through 256 reserved
                    /// `<0xXX>` byte-fallback tokens.
                    pub has_byte_fallback: bool,
                    /// `true` when the tokenizer has one or more special tokens
                    /// registered.
                    pub has_special_tokens: bool,
                }
                impl ::core::fmt::Debug for Capabilities {
                    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                        f.debug_struct("Capabilities")
                            .field("model-type", &self.model_type)
                            .field("variant-id", &self.variant_id)
                            .field("version", &self.version)
                            .field("vocab-size", &self.vocab_size)
                            .field("has-byte-fallback", &self.has_byte_fallback)
                            .field("has-special-tokens", &self.has_special_tokens)
                            .finish()
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_get_capabilities_cabi<T_: Guest>() -> *mut u8 {
                    unsafe {
                        #[cfg(target_arch = "wasm32")]
                        _rt::run_ctors_once();
                        let result0 = { T_::get_capabilities() };
                        let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                        let Capabilities {
                            model_type: model_type2,
                            variant_id: variant_id2,
                            version: version2,
                            vocab_size: vocab_size2,
                            has_byte_fallback: has_byte_fallback2,
                            has_special_tokens: has_special_tokens2,
                        } = result0;
                        let vec3 = (model_type2.into_bytes()).into_boxed_slice();
                        let ptr3 = vec3.as_ptr().cast::<u8>();
                        let len3 = vec3.len();
                        ::core::mem::forget(vec3);
                        *ptr1
                            .add(::core::mem::size_of::<*const u8>())
                            .cast::<usize>() = len3;
                        *ptr1.add(0).cast::<*mut u8>() = ptr3.cast_mut();
                        let vec4 = (variant_id2.into_bytes()).into_boxed_slice();
                        let ptr4 = vec4.as_ptr().cast::<u8>();
                        let len4 = vec4.len();
                        ::core::mem::forget(vec4);
                        *ptr1
                            .add(3 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>() = len4;
                        *ptr1
                            .add(2 * ::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>() = ptr4.cast_mut();
                        let vec5 = (version2.into_bytes()).into_boxed_slice();
                        let ptr5 = vec5.as_ptr().cast::<u8>();
                        let len5 = vec5.len();
                        ::core::mem::forget(vec5);
                        *ptr1
                            .add(5 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>() = len5;
                        *ptr1
                            .add(4 * ::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>() = ptr5.cast_mut();
                        *ptr1
                            .add(6 * ::core::mem::size_of::<*const u8>())
                            .cast::<i32>() = _rt::as_i32(vocab_size2);
                        *ptr1
                            .add(4 + 6 * ::core::mem::size_of::<*const u8>())
                            .cast::<u8>() = (match has_byte_fallback2 {
                            true => 1,
                            false => 0,
                        }) as u8;
                        *ptr1
                            .add(5 + 6 * ::core::mem::size_of::<*const u8>())
                            .cast::<u8>() = (match has_special_tokens2 {
                            true => 1,
                            false => 0,
                        }) as u8;
                        ptr1
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_get_capabilities<T_: Guest>(arg0: *mut u8) {
                    unsafe {
                        let l0 = *arg0.add(0).cast::<*mut u8>();
                        let l1 = *arg0
                            .add(::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        _rt::cabi_dealloc(l0, l1, 1);
                        let l2 = *arg0
                            .add(2 * ::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>();
                        let l3 = *arg0
                            .add(3 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        _rt::cabi_dealloc(l2, l3, 1);
                        let l4 = *arg0
                            .add(4 * ::core::mem::size_of::<*const u8>())
                            .cast::<*mut u8>();
                        let l5 = *arg0
                            .add(5 * ::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        _rt::cabi_dealloc(l4, l5, 1);
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_encode_cabi<T_: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) -> *mut u8 {
                    unsafe {
                        #[cfg(target_arch = "wasm32")]
                        _rt::run_ctors_once();
                        let result1 = {
                            let len0 = arg1;
                            let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                            T_::encode(_rt::string_lift(bytes0))
                        };
                        let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                        match result1 {
                            Ok(e) => {
                                *ptr2.add(0).cast::<u8>() = (0i32) as u8;
                                let Encoding {
                                    ids: ids3,
                                    offsets: offsets3,
                                    special_mask: special_mask3,
                                    type_ids: type_ids3,
                                    attention_mask: attention_mask3,
                                } = e;
                                let vec4 = <_ as Into<_rt::Vec<_>>>::into(ids3).into_boxed_slice();
                                let ptr4 = vec4.as_ptr().cast::<u8>();
                                let len4 = vec4.len();
                                ::core::mem::forget(vec4);
                                *ptr2
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>() = len4;
                                *ptr2
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>() = ptr4.cast_mut();
                                let vec5 =
                                    <_ as Into<_rt::Vec<_>>>::into(offsets3).into_boxed_slice();
                                let ptr5 = vec5.as_ptr().cast::<u8>();
                                let len5 = vec5.len();
                                ::core::mem::forget(vec5);
                                *ptr2
                                    .add(4 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>() = len5;
                                *ptr2
                                    .add(3 * ::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>() = ptr5.cast_mut();
                                let vec6 = special_mask3;
                                let len6 = vec6.len();
                                let layout6 =
                                    _rt::alloc::Layout::from_size_align(vec6.len() * 1, 1).unwrap();
                                let (result6, _cleanup6) = wit_bindgen_rt::Cleanup::new(layout6);
                                if let Some(cleanup) = _cleanup6 {
                                    cleanup.forget();
                                }
                                for (i, e) in vec6.into_iter().enumerate() {
                                    let base = result6.add(i * 1);
                                    {
                                        *base.add(0).cast::<u8>() = (match e {
                                            true => 1,
                                            false => 0,
                                        })
                                            as u8;
                                    }
                                }
                                *ptr2
                                    .add(6 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>() = len6;
                                *ptr2
                                    .add(5 * ::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>() = result6;
                                let vec7 =
                                    <_ as Into<_rt::Vec<_>>>::into(type_ids3).into_boxed_slice();
                                let ptr7 = vec7.as_ptr().cast::<u8>();
                                let len7 = vec7.len();
                                ::core::mem::forget(vec7);
                                *ptr2
                                    .add(8 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>() = len7;
                                *ptr2
                                    .add(7 * ::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>() = ptr7.cast_mut();
                                let vec8 = attention_mask3;
                                let len8 = vec8.len();
                                let layout8 =
                                    _rt::alloc::Layout::from_size_align(vec8.len() * 1, 1).unwrap();
                                let (result8, _cleanup8) = wit_bindgen_rt::Cleanup::new(layout8);
                                if let Some(cleanup) = _cleanup8 {
                                    cleanup.forget();
                                }
                                for (i, e) in vec8.into_iter().enumerate() {
                                    let base = result8.add(i * 1);
                                    {
                                        *base.add(0).cast::<u8>() = (match e {
                                            true => 1,
                                            false => 0,
                                        })
                                            as u8;
                                    }
                                }
                                *ptr2
                                    .add(10 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>() = len8;
                                *ptr2
                                    .add(9 * ::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>() = result8;
                            }
                            Err(e) => {
                                *ptr2.add(0).cast::<u8>() = (1i32) as u8;
                                match e {
                                    TokenizerError::InvalidUtf8 => {
                                        *ptr2
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<u8>() = (0i32) as u8;
                                    }
                                    TokenizerError::UnknownToken(e) => {
                                        *ptr2
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<u8>() = (1i32) as u8;
                                        let vec9 = (e.into_bytes()).into_boxed_slice();
                                        let ptr9 = vec9.as_ptr().cast::<u8>();
                                        let len9 = vec9.len();
                                        ::core::mem::forget(vec9);
                                        *ptr2
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>() = len9;
                                        *ptr2
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>() = ptr9.cast_mut();
                                    }
                                    TokenizerError::DisallowedSpecialToken(e) => {
                                        *ptr2
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<u8>() = (2i32) as u8;
                                        let vec10 = (e.into_bytes()).into_boxed_slice();
                                        let ptr10 = vec10.as_ptr().cast::<u8>();
                                        let len10 = vec10.len();
                                        ::core::mem::forget(vec10);
                                        *ptr2
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>() = len10;
                                        *ptr2
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>() = ptr10.cast_mut();
                                    }
                                    TokenizerError::VocabularyMismatch => {
                                        *ptr2
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<u8>() = (3i32) as u8;
                                    }
                                    TokenizerError::Other(e) => {
                                        *ptr2
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<u8>() = (4i32) as u8;
                                        let vec11 = (e.into_bytes()).into_boxed_slice();
                                        let ptr11 = vec11.as_ptr().cast::<u8>();
                                        let len11 = vec11.len();
                                        ::core::mem::forget(vec11);
                                        *ptr2
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>() = len11;
                                        *ptr2
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>() = ptr11.cast_mut();
                                    }
                                }
                            }
                        };
                        ptr2
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_encode<T_: Guest>(arg0: *mut u8) {
                    unsafe {
                        let l0 = i32::from(*arg0.add(0).cast::<u8>());
                        match l0 {
                            0 => {
                                let l1 = *arg0
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l2 = *arg0
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let base3 = l1;
                                let len3 = l2;
                                _rt::cabi_dealloc(base3, len3 * 4, 4);
                                let l4 = *arg0
                                    .add(3 * ::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l5 = *arg0
                                    .add(4 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let base6 = l4;
                                let len6 = l5;
                                _rt::cabi_dealloc(base6, len6 * 8, 4);
                                let l7 = *arg0
                                    .add(5 * ::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l8 = *arg0
                                    .add(6 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let base9 = l7;
                                let len9 = l8;
                                _rt::cabi_dealloc(base9, len9 * 1, 1);
                                let l10 = *arg0
                                    .add(7 * ::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l11 = *arg0
                                    .add(8 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let base12 = l10;
                                let len12 = l11;
                                _rt::cabi_dealloc(base12, len12 * 4, 4);
                                let l13 = *arg0
                                    .add(9 * ::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l14 = *arg0
                                    .add(10 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let base15 = l13;
                                let len15 = l14;
                                _rt::cabi_dealloc(base15, len15 * 1, 1);
                            }
                            _ => {
                                let l16 = i32::from(
                                    *arg0.add(::core::mem::size_of::<*const u8>()).cast::<u8>(),
                                );
                                match l16 {
                                    0 => (),
                                    1 => {
                                        let l17 = *arg0
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l18 = *arg0
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        _rt::cabi_dealloc(l17, l18, 1);
                                    }
                                    2 => {
                                        let l19 = *arg0
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l20 = *arg0
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        _rt::cabi_dealloc(l19, l20, 1);
                                    }
                                    3 => (),
                                    _ => {
                                        let l21 = *arg0
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l22 = *arg0
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        _rt::cabi_dealloc(l21, l22, 1);
                                    }
                                }
                            }
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_decode_cabi<T_: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) -> *mut u8 {
                    unsafe {
                        #[cfg(target_arch = "wasm32")]
                        _rt::run_ctors_once();
                        let result1 =
                            {
                                let len0 = arg1;
                                T_::decode(<_ as From<_rt::Vec<_>>>::from(
                                    _rt::Vec::from_raw_parts(arg0.cast(), len0, len0),
                                ))
                            };
                        let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                        match result1 {
                            Ok(e) => {
                                *ptr2.add(0).cast::<u8>() = (0i32) as u8;
                                let vec3 = (e.into_bytes()).into_boxed_slice();
                                let ptr3 = vec3.as_ptr().cast::<u8>();
                                let len3 = vec3.len();
                                ::core::mem::forget(vec3);
                                *ptr2
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>() = len3;
                                *ptr2
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>() = ptr3.cast_mut();
                            }
                            Err(e) => {
                                *ptr2.add(0).cast::<u8>() = (1i32) as u8;
                                match e {
                                    TokenizerError::InvalidUtf8 => {
                                        *ptr2
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<u8>() = (0i32) as u8;
                                    }
                                    TokenizerError::UnknownToken(e) => {
                                        *ptr2
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<u8>() = (1i32) as u8;
                                        let vec4 = (e.into_bytes()).into_boxed_slice();
                                        let ptr4 = vec4.as_ptr().cast::<u8>();
                                        let len4 = vec4.len();
                                        ::core::mem::forget(vec4);
                                        *ptr2
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>() = len4;
                                        *ptr2
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>() = ptr4.cast_mut();
                                    }
                                    TokenizerError::DisallowedSpecialToken(e) => {
                                        *ptr2
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<u8>() = (2i32) as u8;
                                        let vec5 = (e.into_bytes()).into_boxed_slice();
                                        let ptr5 = vec5.as_ptr().cast::<u8>();
                                        let len5 = vec5.len();
                                        ::core::mem::forget(vec5);
                                        *ptr2
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>() = len5;
                                        *ptr2
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>() = ptr5.cast_mut();
                                    }
                                    TokenizerError::VocabularyMismatch => {
                                        *ptr2
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<u8>() = (3i32) as u8;
                                    }
                                    TokenizerError::Other(e) => {
                                        *ptr2
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<u8>() = (4i32) as u8;
                                        let vec6 = (e.into_bytes()).into_boxed_slice();
                                        let ptr6 = vec6.as_ptr().cast::<u8>();
                                        let len6 = vec6.len();
                                        ::core::mem::forget(vec6);
                                        *ptr2
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>() = len6;
                                        *ptr2
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>() = ptr6.cast_mut();
                                    }
                                }
                            }
                        };
                        ptr2
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_decode<T_: Guest>(arg0: *mut u8) {
                    unsafe {
                        let l0 = i32::from(*arg0.add(0).cast::<u8>());
                        match l0 {
                            0 => {
                                let l1 = *arg0
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l2 = *arg0
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                _rt::cabi_dealloc(l1, l2, 1);
                            }
                            _ => {
                                let l3 = i32::from(
                                    *arg0.add(::core::mem::size_of::<*const u8>()).cast::<u8>(),
                                );
                                match l3 {
                                    0 => (),
                                    1 => {
                                        let l4 = *arg0
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l5 = *arg0
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        _rt::cabi_dealloc(l4, l5, 1);
                                    }
                                    2 => {
                                        let l6 = *arg0
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l7 = *arg0
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        _rt::cabi_dealloc(l6, l7, 1);
                                    }
                                    3 => (),
                                    _ => {
                                        let l8 = *arg0
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l9 = *arg0
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        _rt::cabi_dealloc(l8, l9, 1);
                                    }
                                }
                            }
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_count_cabi<T_: Guest>(arg0: *mut u8, arg1: usize) -> *mut u8 {
                    unsafe {
                        #[cfg(target_arch = "wasm32")]
                        _rt::run_ctors_once();
                        let result1 = {
                            let len0 = arg1;
                            let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                            T_::count(_rt::string_lift(bytes0))
                        };
                        let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                        match result1 {
                            Ok(e) => {
                                *ptr2.add(0).cast::<u8>() = (0i32) as u8;
                                *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<i32>() =
                                    _rt::as_i32(e);
                            }
                            Err(e) => {
                                *ptr2.add(0).cast::<u8>() = (1i32) as u8;
                                match e {
                                    TokenizerError::InvalidUtf8 => {
                                        *ptr2
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<u8>() = (0i32) as u8;
                                    }
                                    TokenizerError::UnknownToken(e) => {
                                        *ptr2
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<u8>() = (1i32) as u8;
                                        let vec3 = (e.into_bytes()).into_boxed_slice();
                                        let ptr3 = vec3.as_ptr().cast::<u8>();
                                        let len3 = vec3.len();
                                        ::core::mem::forget(vec3);
                                        *ptr2
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>() = len3;
                                        *ptr2
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>() = ptr3.cast_mut();
                                    }
                                    TokenizerError::DisallowedSpecialToken(e) => {
                                        *ptr2
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<u8>() = (2i32) as u8;
                                        let vec4 = (e.into_bytes()).into_boxed_slice();
                                        let ptr4 = vec4.as_ptr().cast::<u8>();
                                        let len4 = vec4.len();
                                        ::core::mem::forget(vec4);
                                        *ptr2
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>() = len4;
                                        *ptr2
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>() = ptr4.cast_mut();
                                    }
                                    TokenizerError::VocabularyMismatch => {
                                        *ptr2
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<u8>() = (3i32) as u8;
                                    }
                                    TokenizerError::Other(e) => {
                                        *ptr2
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<u8>() = (4i32) as u8;
                                        let vec5 = (e.into_bytes()).into_boxed_slice();
                                        let ptr5 = vec5.as_ptr().cast::<u8>();
                                        let len5 = vec5.len();
                                        ::core::mem::forget(vec5);
                                        *ptr2
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>() = len5;
                                        *ptr2
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>() = ptr5.cast_mut();
                                    }
                                }
                            }
                        };
                        ptr2
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_count<T_: Guest>(arg0: *mut u8) {
                    unsafe {
                        let l0 = i32::from(*arg0.add(0).cast::<u8>());
                        match l0 {
                            0 => (),
                            _ => {
                                let l1 = i32::from(
                                    *arg0.add(::core::mem::size_of::<*const u8>()).cast::<u8>(),
                                );
                                match l1 {
                                    0 => (),
                                    1 => {
                                        let l2 = *arg0
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l3 = *arg0
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        _rt::cabi_dealloc(l2, l3, 1);
                                    }
                                    2 => {
                                        let l4 = *arg0
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l5 = *arg0
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        _rt::cabi_dealloc(l4, l5, 1);
                                    }
                                    3 => (),
                                    _ => {
                                        let l6 = *arg0
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l7 = *arg0
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        _rt::cabi_dealloc(l6, l7, 1);
                                    }
                                }
                            }
                        }
                    }
                }
                pub trait Guest {
                    /// Backend metadata. Callers cache this at load time.
                    /// WIT keeps type names and function names in the same namespace,
                    /// so the accessor cannot share the `capabilities` name with the
                    /// record type. `get-capabilities` is the WIT convention for
                    /// "no-arg getter that returns a record of the same-ish name" and
                    /// matches the tegmentum:lang-detect precedent verbatim.
                    #[allow(async_fn_in_trait)]
                    fn get_capabilities() -> Capabilities;
                    /// Encode `text` into a full `encoding`. Every populated per-token
                    /// array on the returned value has the same length as `ids`.
                    #[allow(async_fn_in_trait)]
                    fn encode(text: _rt::String) -> Result<Encoding, TokenizerError>;
                    /// Decode a sequence of ids back into a string. Given
                    /// `encode(text)?.ids` as input, must return the original text
                    /// modulo the tokenizer's documented lossy exceptions
                    /// (normalization, unknown-byte replacement, truncation).
                    #[allow(async_fn_in_trait)]
                    fn decode(ids: _rt::Vec<TokenId>) -> Result<_rt::String, TokenizerError>;
                    /// Count the tokens `encode(text)` would produce, without
                    /// materialising the full encoding. Runtimes with a cheaper count
                    /// fast path (subword tokenizers skipping offset tracking) route
                    /// through it here; the default is `encode(text)?.ids.len()`.
                    #[allow(async_fn_in_trait)]
                    fn count(text: _rt::String) -> Result<u32, TokenizerError>;
                }
                #[doc(hidden)]

                macro_rules! __export_tegmentum_tokenizer_tokenizer_0_1_0_cabi{
  ($ty:ident with_types_in $($path_to_types:tt)*) => (const _: () = {

    #[unsafe(export_name = "tegmentum:tokenizer/tokenizer@0.1.0#get-capabilities")]
    unsafe extern "C" fn export_get_capabilities() -> *mut u8 {
      unsafe { $($path_to_types)*::_export_get_capabilities_cabi::<$ty>() }
    }
    #[unsafe(export_name = "cabi_post_tegmentum:tokenizer/tokenizer@0.1.0#get-capabilities")]
    unsafe extern "C" fn _post_return_get_capabilities(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_get_capabilities::<$ty>(arg0) }
    }
    #[unsafe(export_name = "tegmentum:tokenizer/tokenizer@0.1.0#encode")]
    unsafe extern "C" fn export_encode(arg0: *mut u8,arg1: usize,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_encode_cabi::<$ty>(arg0, arg1) }
    }
    #[unsafe(export_name = "cabi_post_tegmentum:tokenizer/tokenizer@0.1.0#encode")]
    unsafe extern "C" fn _post_return_encode(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_encode::<$ty>(arg0) }
    }
    #[unsafe(export_name = "tegmentum:tokenizer/tokenizer@0.1.0#decode")]
    unsafe extern "C" fn export_decode(arg0: *mut u8,arg1: usize,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_decode_cabi::<$ty>(arg0, arg1) }
    }
    #[unsafe(export_name = "cabi_post_tegmentum:tokenizer/tokenizer@0.1.0#decode")]
    unsafe extern "C" fn _post_return_decode(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_decode::<$ty>(arg0) }
    }
    #[unsafe(export_name = "tegmentum:tokenizer/tokenizer@0.1.0#count")]
    unsafe extern "C" fn export_count(arg0: *mut u8,arg1: usize,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_count_cabi::<$ty>(arg0, arg1) }
    }
    #[unsafe(export_name = "cabi_post_tegmentum:tokenizer/tokenizer@0.1.0#count")]
    unsafe extern "C" fn _post_return_count(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_count::<$ty>(arg0) }
    }
  };);
}
                #[doc(hidden)]
                pub(crate) use __export_tegmentum_tokenizer_tokenizer_0_1_0_cabi;

                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<u8>; 11 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 11 * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
mod _rt {
    #![allow(dead_code, unused_imports, clippy::all)]
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;

    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }

    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }

    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }

    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }

    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }

    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }

    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }

    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }

    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }

    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }

    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }

    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        unsafe {
            let layout = alloc::Layout::from_size_align_unchecked(size, align);
            alloc::dealloc(ptr, layout);
        }
    }
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            unsafe { String::from_utf8_unchecked(bytes) }
        }
    }
    pub use alloc_crate::alloc;
    extern crate alloc as alloc_crate;
}

/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]

macro_rules! __export_tokenizer_provider_impl {
  ($ty:ident) => (self::export!($ty with_types_in self););
  ($ty:ident with_types_in $($path_to_types_root:tt)*) => (
  $($path_to_types_root)*::exports::tegmentum::tokenizer::tokenizer::__export_tegmentum_tokenizer_tokenizer_0_1_0_cabi!($ty with_types_in $($path_to_types_root)*::exports::tegmentum::tokenizer::tokenizer);
  )
}
#[doc(inline)]
pub(crate) use __export_tokenizer_provider_impl as export;

#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.60.0:tegmentum:tokenizer@0.1.0:tokenizer-provider:encoded world")]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 688] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xa7\x04\x01A\x02\x01\
A\x02\x01B\x19\x01y\x04\0\x08token-id\x03\0\0\x01r\x02\x05starty\x03endy\x04\0\x05\
range\x03\0\x02\x01p\x01\x01p\x03\x01p\x7f\x01py\x01r\x05\x03ids\x04\x07offsets\x05\
\x0cspecial-mask\x06\x08type-ids\x07\x0eattention-mask\x06\x04\0\x08encoding\x03\
\0\x08\x01q\x05\x0cinvalid-utf8\0\0\x0dunknown-token\x01s\0\x18disallowed-specia\
l-token\x01s\0\x13vocabulary-mismatch\0\0\x05other\x01s\0\x04\0\x0ftokenizer-err\
or\x03\0\x0a\x01r\x06\x0amodel-types\x0avariant-ids\x07versions\x0avocab-sizey\x11\
has-byte-fallback\x7f\x12has-special-tokens\x7f\x04\0\x0ccapabilities\x03\0\x0c\x01\
@\0\0\x0d\x04\0\x10get-capabilities\x01\x0e\x01j\x01\x09\x01\x0b\x01@\x01\x04tex\
ts\0\x0f\x04\0\x06encode\x01\x10\x01j\x01s\x01\x0b\x01@\x01\x03ids\x04\0\x11\x04\
\0\x06decode\x01\x12\x01j\x01y\x01\x0b\x01@\x01\x04texts\0\x13\x04\0\x05count\x01\
\x14\x04\0#tegmentum:tokenizer/tokenizer@0.1.0\x05\0\x04\0,tegmentum:tokenizer/t\
okenizer-provider@0.1.0\x04\0\x0b\x18\x01\0\x12tokenizer-provider\x03\0\0\0G\x09\
producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.254.0\x10wit-bindgen-rus\
t\x060.60.0";

#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
