//! Wasmtime smoke test for the reference
//! `tegmentum:i18n-linebreak@0.1.0` component.
//!
//! Verifies WIT-i18n Phase 5's line-break follow-up
//! (`docs/design/wit-i18n.md` § 8.7). The test drives the
//! component the same way any external caller would: builds it
//! under `wasm32-wasip1 --features wit-component`, componentises
//! it via `wasm-tools`, then loads the componentised `.wasm` into
//! an in-process wasmtime `Engine` and calls each of the WIT
//! exports through typed bindings generated by
//! `wasmtime::component::bindgen!` from the shipped WIT file.
//!
//! # Prerequisites
//!
//! Requires `cargo` with `wasm32-wasip1` installed plus
//! `wasm-tools` on `$PATH`, and one WASI preview1 → preview2
//! adapter file discoverable via [`find_wasi_adapter`]. Missing
//! prerequisites soft-skip the test.

#![cfg(not(target_family = "wasm"))]
#![allow(unsafe_code)]

use std::path::PathBuf;
use std::process::Command;
use std::sync::OnceLock;

use wasmtime::component::{Component, Linker, ResourceTable};
use wasmtime::{Engine, Store};
use wasmtime_wasi::{WasiCtx, WasiCtxBuilder, WasiView};

// Typed bindings generated from the shipped WIT contract. Wrapping
// in a module lets us scope a single `#[allow(missing_docs)]`
// around the generated code.
#[allow(missing_docs, clippy::pedantic, clippy::nursery)]
mod bindgen {
    wasmtime::component::bindgen!({
        world: "linebreak-world",
        path: "../../component/wit/linebreak",
    });
}

use bindgen::LinebreakWorld;
use bindgen::exports::tegmentum::i18n_linebreak::linebreak::LineBreakStrictness as WitStrictness;
use bindgen::exports::tegmentum::i18n_linebreak::types::BreakKind as WitBreakKind;

/// Host state carried in the `Store<T>`. Holds the WASI preview2
/// context and a `ResourceTable`.
struct HostState {
    table: ResourceTable,
    wasi: WasiCtx,
}

impl WasiView for HostState {
    fn ctx(&mut self) -> &mut WasiCtx {
        &mut self.wasi
    }
    fn table(&mut self) -> &mut ResourceTable {
        &mut self.table
    }
}

/// One end-to-end build-and-load, cached on the shared `OnceLock`.
struct SmokeHarness {
    engine: Engine,
    component: Component,
    linker: Linker<HostState>,
}

/// See the sibling icu-*-component smoke tests for the shared-once
/// concurrency rationale.
static SHARED_COMPONENT: OnceLock<Option<PathBuf>> = OnceLock::new();

impl SmokeHarness {
    fn build_or_skip() -> Option<Self> {
        let component_wasm = SHARED_COMPONENT
            .get_or_init(Self::build_shared_once)
            .clone()?;

        let engine = Engine::default();
        let component = match Component::from_file(&engine, &component_wasm) {
            Ok(c) => c,
            Err(e) => {
                eprintln!(
                    "SKIP: wasmtime failed to load component at {}: {e}",
                    component_wasm.display()
                );
                return None;
            }
        };
        let mut linker: Linker<HostState> = Linker::new(&engine);
        if let Err(e) = wasmtime_wasi::add_to_linker_sync(&mut linker) {
            eprintln!("SKIP: could not add WASI to linker: {e}");
            return None;
        }
        Some(Self {
            engine,
            component,
            linker,
        })
    }

    fn build_shared_once() -> Option<PathBuf> {
        if !has_tool("cargo") {
            eprintln!("SKIP: cargo not on PATH");
            return None;
        }
        if !has_tool("wasm-tools") {
            eprintln!(
                "SKIP: wasm-tools not on PATH — install from https://github.com/bytecodealliance/wasm-tools"
            );
            return None;
        }
        if !target_installed("wasm32-wasip1") {
            eprintln!(
                "SKIP: wasm32-wasip1 target not installed — `rustup target add wasm32-wasip1`"
            );
            return None;
        }

        let workspace_root = workspace_root();
        let build = Command::new("cargo")
            .current_dir(&workspace_root)
            .args([
                "build",
                "-p",
                "stringcheese-icu-linebreak-component",
                "--target",
                "wasm32-wasip1",
                "--features",
                "wit-component",
                "--release",
            ])
            .status()
            .expect("cargo build must launch");
        assert!(
            build.success(),
            "cargo build for wasm32-wasip1 must succeed",
        );

        let module_wasm = workspace_root
            .join("target/wasm32-wasip1/release/stringcheese_icu_linebreak_component.wasm");
        assert!(
            module_wasm.exists(),
            "expected wasm at {} after cargo build",
            module_wasm.display(),
        );

        let Some(adapter) = find_wasi_adapter() else {
            eprintln!(
                "SKIP: no wasi_snapshot_preview1.reactor.wasm adapter found on the search path"
            );
            return None;
        };

        let component_wasm = std::env::temp_dir().join("stringcheese_icu_linebreak_component.wasm");
        let componentize = Command::new("wasm-tools")
            .args([
                "component",
                "new",
                module_wasm.to_str().expect("path is utf8"),
                "--adapt",
                adapter.to_str().expect("adapter path is utf8"),
                "-o",
                component_wasm.to_str().expect("output path is utf8"),
            ])
            .status()
            .expect("wasm-tools must launch");
        assert!(
            componentize.success(),
            "wasm-tools component new must succeed",
        );
        assert!(
            component_wasm.exists(),
            "expected component at {}",
            component_wasm.display(),
        );
        Some(component_wasm)
    }

    fn instantiate(&self) -> (Store<HostState>, LinebreakWorld) {
        let mut store = Store::new(
            &self.engine,
            HostState {
                table: ResourceTable::new(),
                wasi: WasiCtxBuilder::new().build(),
            },
        );
        let bindings = LinebreakWorld::instantiate(&mut store, &self.component, &self.linker)
            .expect("component must instantiate against the wasmtime-wasi linker");
        (store, bindings)
    }
}

fn has_tool(name: &str) -> bool {
    Command::new(name)
        .arg("--version")
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status()
        .is_ok_and(|s| s.success())
}

fn target_installed(triple: &str) -> bool {
    let out = Command::new("rustup")
        .args(["target", "list", "--installed"])
        .output();
    match out {
        Ok(o) if o.status.success() => String::from_utf8_lossy(&o.stdout)
            .lines()
            .any(|l| l.trim() == triple),
        _ => true,
    }
}

fn workspace_root() -> PathBuf {
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    manifest
        .parent()
        .and_then(|p| p.parent())
        .expect("workspace root is two levels above crate manifest")
        .to_path_buf()
}

fn find_wasi_adapter() -> Option<PathBuf> {
    if let Ok(p) = std::env::var("STRINGCHEESE_WASI_ADAPTER") {
        let path = PathBuf::from(p);
        if path.exists() {
            return Some(path);
        }
    }
    let home = std::env::var_os("HOME").map(PathBuf::from)?;
    let cache =
        home.join(".cache/stringcheese-tokenizer-component/wasi_snapshot_preview1.reactor.wasm");
    if cache.exists() {
        return Some(cache);
    }
    walk_for_adapter(&home.join(".cargo/registry/src")).next()
}

fn walk_for_adapter(root: &std::path::Path) -> impl Iterator<Item = PathBuf> {
    let mut out = Vec::new();
    if let Ok(entries) = std::fs::read_dir(root) {
        for entry in entries.flatten() {
            let path = entry.path();
            let candidate = path.join("cargo-component/wasi_snapshot_preview1.reactor.wasm");
            if candidate.exists() {
                out.push(candidate);
            }
        }
    }
    out.into_iter()
}

// -----------------------------------------------------------------------
// Line-break smoke tests.
// -----------------------------------------------------------------------

#[test]
fn wasmtime_smoke_find_breaks_hard_break_at_lf() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let linebreak = bindings.tegmentum_i18n_linebreak_linebreak();
    let opps = linebreak
        .call_find_breaks(&mut store, "a\nb")
        .expect("find-breaks trap-free");
    // Expect at least one mandatory break after the LF.
    assert!(
        opps.iter()
            .any(|o| matches!(o.kind, WitBreakKind::Mandatory)),
        "expected a mandatory break: {opps:?}",
    );
    // The last opportunity is always at eot.
    assert_eq!(opps.last().map(|o| o.offset), Some(3));
}

#[test]
fn wasmtime_smoke_find_breaks_crlf_single_mandatory() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let linebreak = bindings.tegmentum_i18n_linebreak_linebreak();
    let opps = linebreak
        .call_find_breaks(&mut store, "a\r\nb")
        .expect("find-breaks trap-free");
    let mandatories: Vec<_> = opps
        .iter()
        .filter(|o| matches!(o.kind, WitBreakKind::Mandatory))
        .collect();
    assert_eq!(
        mandatories.len(),
        1,
        "LB5 CRLF should produce one mandatory break: {opps:?}"
    );
    assert_eq!(mandatories[0].offset, 3, "mandatory break sits after CRLF");
}

#[test]
fn wasmtime_smoke_find_breaks_nel_is_mandatory() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let linebreak = bindings.tegmentum_i18n_linebreak_linebreak();
    let opps = linebreak
        .call_find_breaks(&mut store, "a\u{0085}b")
        .expect("find-breaks trap-free");
    assert!(
        opps.iter()
            .any(|o| matches!(o.kind, WitBreakKind::Mandatory))
    );
}

#[test]
fn wasmtime_smoke_find_breaks_soft_break_after_space() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let linebreak = bindings.tegmentum_i18n_linebreak_linebreak();
    let opps = linebreak
        .call_find_breaks(&mut store, "hi there")
        .expect("find-breaks trap-free");
    // Allowed break after the space at byte offset 3.
    assert!(
        opps.iter()
            .any(|o| o.offset == 3 && matches!(o.kind, WitBreakKind::Allowed)),
        "expect allowed break after SP: {opps:?}",
    );
}

#[test]
fn wasmtime_smoke_find_breaks_soft_break_after_hyphen() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let linebreak = bindings.tegmentum_i18n_linebreak_linebreak();
    let opps = linebreak
        .call_find_breaks(&mut store, "co-op")
        .expect("find-breaks trap-free");
    // LB21 forbids break BEFORE HY; LB31 default allows break AFTER
    // HY. So a break at byte 3 (right after the hyphen).
    assert!(
        opps.iter().any(|o| o.offset == 3),
        "expect break after HY: {opps:?}",
    );
}

#[test]
fn wasmtime_smoke_find_breaks_no_break_across_space_between_digits() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let linebreak = bindings.tegmentum_i18n_linebreak_linebreak();
    let opps = linebreak
        .call_find_breaks(&mut store, "12")
        .expect("find-breaks trap-free");
    // "12" — LB25 keeps the numeric run together; only eot break.
    assert_eq!(opps.len(), 1);
    assert_eq!(opps[0].offset, 2);
}

#[test]
fn wasmtime_smoke_find_breaks_empty_input() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let linebreak = bindings.tegmentum_i18n_linebreak_linebreak();
    let opps = linebreak
        .call_find_breaks(&mut store, "")
        .expect("find-breaks trap-free");
    assert!(
        opps.is_empty(),
        "empty input yields no opportunities: {opps:?}"
    );
}

#[test]
fn wasmtime_smoke_find_breaks_with_strictness_variants_all_return_something() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let linebreak = bindings.tegmentum_i18n_linebreak_linebreak();
    for s in [
        WitStrictness::Loose,
        WitStrictness::Normal,
        WitStrictness::Strict,
    ] {
        let opps = linebreak
            .call_find_breaks_with_strictness(&mut store, "hello world", s)
            .expect("find-breaks-with-strictness trap-free");
        // All strictness modes produce at least the trailing eot
        // opportunity + a soft break after the space.
        assert!(opps.len() >= 2, "strictness {s:?}: {opps:?}");
    }
}

// -----------------------------------------------------------------------
// Capabilities smoke tests.
// -----------------------------------------------------------------------

#[test]
fn wasmtime_smoke_supported_locales_lists_root_marker() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let caps = bindings.tegmentum_i18n_linebreak_capabilities();
    let locales = caps
        .call_supported_locales(&mut store)
        .expect("supported-locales trap-free");
    assert_eq!(locales, vec![String::new()]);
}

#[test]
fn wasmtime_smoke_supports_returns_true_for_every_locale() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let caps = bindings.tegmentum_i18n_linebreak_capabilities();
    for tag in ["", "en", "ja", "zh-Hans", "de-CH"] {
        let ok = caps
            .call_supports(&mut store, &tag.to_string())
            .expect("supports trap-free");
        assert!(ok, "supports({tag:?}) should be true under Phase 5");
    }
}
