// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod tegmentum {
        pub mod lang_detect {
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod detector {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                /// Static description of what this backend can do. Cheap; safe to
                /// call once at load time and cache.
                #[derive(Clone)]
                pub struct Capabilities {
                    /// Backend identifier — "whatlang" | "lingua" | "script" | ...
                    pub backend: _rt::String,
                    /// Semver of the backend's model / algorithm corpus.
                    pub version: _rt::String,
                    /// ISO 639-3 codes this backend can distinguish. Empty means
                    /// "any language in the backend's model" (whatlang); non-empty
                    /// means the exact enabled set (lingua per-language builds).
                    pub supports: _rt::Vec<_rt::String>,
                    /// True when `detect-ranked` returns more than a single-element
                    /// list. Whatlang supports this; script-detect does not.
                    pub can_rank: bool,
                    /// True when `detect-from` filters against the caller-supplied
                    /// allowlist. Whatlang and lingua support this; script-detect
                    /// does not.
                    pub can_constrain: bool,
                    /// True when `detect-mixed` returns real spans instead of
                    /// `none`. Only lingua supports this today.
                    pub can_segment: bool,
                }
                impl ::core::fmt::Debug for Capabilities {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("Capabilities")
                            .field("backend", &self.backend)
                            .field("version", &self.version)
                            .field("supports", &self.supports)
                            .field("can-rank", &self.can_rank)
                            .field("can-constrain", &self.can_constrain)
                            .field("can-segment", &self.can_segment)
                            .finish()
                    }
                }
                /// Baseline single-best-guess detection result.
                #[derive(Clone)]
                pub struct Detection {
                    /// ISO 639-3 language code, e.g. "eng". Empty when the backend
                    /// only classifies script (script-detect returns `""` here).
                    pub lang: _rt::String,
                    /// English name of the language, e.g. "English". May be empty
                    /// when `lang` is empty.
                    pub lang_name: _rt::String,
                    /// ISO 15924 script code, e.g. "Latn", "Cyrl", "Jpan".
                    pub script: _rt::String,
                    /// Detection confidence in [0.0, 1.0]. Exact semantics are
                    /// backend-specific; callers threshold against their own
                    /// tolerance rather than treating it as a probability.
                    pub confidence: f64,
                    /// The backend's own opinion about whether the prediction is
                    /// trustworthy. Backends without a reliability signal set
                    /// this to `false` when they can't vouch for the result.
                    pub reliable: bool,
                }
                impl ::core::fmt::Debug for Detection {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("Detection")
                            .field("lang", &self.lang)
                            .field("lang-name", &self.lang_name)
                            .field("script", &self.script)
                            .field("confidence", &self.confidence)
                            .field("reliable", &self.reliable)
                            .finish()
                    }
                }
                /// One entry of a ranked-candidates distribution.
                #[derive(Clone)]
                pub struct RankedDetection {
                    pub lang: _rt::String,
                    pub confidence: f64,
                }
                impl ::core::fmt::Debug for RankedDetection {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("RankedDetection")
                            .field("lang", &self.lang)
                            .field("confidence", &self.confidence)
                            .finish()
                    }
                }
                /// One segment of mixed-language text.
                #[derive(Clone)]
                pub struct SpanDetection {
                    /// Byte offset into the input text.
                    pub start: u32,
                    /// Byte offset (exclusive) into the input text.
                    pub end: u32,
                    pub lang: _rt::String,
                    pub confidence: f64,
                }
                impl ::core::fmt::Debug for SpanDetection {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("SpanDetection")
                            .field("start", &self.start)
                            .field("end", &self.end)
                            .field("lang", &self.lang)
                            .field("confidence", &self.confidence)
                            .finish()
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_get_capabilities_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::get_capabilities();
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let Capabilities {
                        backend: backend2,
                        version: version2,
                        supports: supports2,
                        can_rank: can_rank2,
                        can_constrain: can_constrain2,
                        can_segment: can_segment2,
                    } = result0;
                    let vec3 = (backend2.into_bytes()).into_boxed_slice();
                    let ptr3 = vec3.as_ptr().cast::<u8>();
                    let len3 = vec3.len();
                    ::core::mem::forget(vec3);
                    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
                    *ptr1.add(0).cast::<*mut u8>() = ptr3.cast_mut();
                    let vec4 = (version2.into_bytes()).into_boxed_slice();
                    let ptr4 = vec4.as_ptr().cast::<u8>();
                    let len4 = vec4.len();
                    ::core::mem::forget(vec4);
                    *ptr1.add(3 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
                    *ptr1
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr4.cast_mut();
                    let vec6 = supports2;
                    let len6 = vec6.len();
                    let layout6 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec6.len() * (2 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result6 = if layout6.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout6).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout6);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec6.into_iter().enumerate() {
                        let base = result6
                            .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                        {
                            let vec5 = (e.into_bytes()).into_boxed_slice();
                            let ptr5 = vec5.as_ptr().cast::<u8>();
                            let len5 = vec5.len();
                            ::core::mem::forget(vec5);
                            *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len5;
                            *base.add(0).cast::<*mut u8>() = ptr5.cast_mut();
                        }
                    }
                    *ptr1.add(5 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len6;
                    *ptr1
                        .add(4 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = result6;
                    *ptr1.add(6 * ::core::mem::size_of::<*const u8>()).cast::<u8>() = (match can_rank2 {
                        true => 1,
                        false => 0,
                    }) as u8;
                    *ptr1
                        .add(1 + 6 * ::core::mem::size_of::<*const u8>())
                        .cast::<u8>() = (match can_constrain2 {
                        true => 1,
                        false => 0,
                    }) as u8;
                    *ptr1
                        .add(2 + 6 * ::core::mem::size_of::<*const u8>())
                        .cast::<u8>() = (match can_segment2 {
                        true => 1,
                        false => 0,
                    }) as u8;
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_get_capabilities<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l0, l1, 1);
                    let l2 = *arg0
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l3 = *arg0
                        .add(3 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l2, l3, 1);
                    let l4 = *arg0
                        .add(4 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l5 = *arg0
                        .add(5 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base8 = l4;
                    let len8 = l5;
                    for i in 0..len8 {
                        let base = base8
                            .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                        {
                            let l6 = *base.add(0).cast::<*mut u8>();
                            let l7 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l6, l7, 1);
                        }
                    }
                    _rt::cabi_dealloc(
                        base8,
                        len8 * (2 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_detect_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let result1 = T::detect(_rt::string_lift(bytes0));
                    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result1 {
                        Some(e) => {
                            *ptr2.add(0).cast::<u8>() = (1i32) as u8;
                            let Detection {
                                lang: lang3,
                                lang_name: lang_name3,
                                script: script3,
                                confidence: confidence3,
                                reliable: reliable3,
                            } = e;
                            let vec4 = (lang3.into_bytes()).into_boxed_slice();
                            let ptr4 = vec4.as_ptr().cast::<u8>();
                            let len4 = vec4.len();
                            ::core::mem::forget(vec4);
                            *ptr2
                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len4;
                            *ptr2.add(8).cast::<*mut u8>() = ptr4.cast_mut();
                            let vec5 = (lang_name3.into_bytes()).into_boxed_slice();
                            let ptr5 = vec5.as_ptr().cast::<u8>();
                            let len5 = vec5.len();
                            ::core::mem::forget(vec5);
                            *ptr2
                                .add(8 + 3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len5;
                            *ptr2
                                .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr5.cast_mut();
                            let vec6 = (script3.into_bytes()).into_boxed_slice();
                            let ptr6 = vec6.as_ptr().cast::<u8>();
                            let len6 = vec6.len();
                            ::core::mem::forget(vec6);
                            *ptr2
                                .add(8 + 5 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len6;
                            *ptr2
                                .add(8 + 4 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr6.cast_mut();
                            *ptr2
                                .add(8 + 6 * ::core::mem::size_of::<*const u8>())
                                .cast::<f64>() = _rt::as_f64(confidence3);
                            *ptr2
                                .add(16 + 6 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (match reliable3 {
                                true => 1,
                                false => 0,
                            }) as u8;
                        }
                        None => {
                            *ptr2.add(0).cast::<u8>() = (0i32) as u8;
                        }
                    };
                    ptr2
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_detect<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {}
                        _ => {
                            let l1 = *arg0.add(8).cast::<*mut u8>();
                            let l2 = *arg0
                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                            let l3 = *arg0
                                .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l4 = *arg0
                                .add(8 + 3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l3, l4, 1);
                            let l5 = *arg0
                                .add(8 + 4 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l6 = *arg0
                                .add(8 + 5 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l5, l6, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_detect_ranked_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let result1 = T::detect_ranked(_rt::string_lift(bytes0));
                    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec5 = result1;
                    let len5 = vec5.len();
                    let layout5 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec5.len() * (8 + 2 * ::core::mem::size_of::<*const u8>()),
                        8,
                    );
                    let result5 = if layout5.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout5).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout5);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec5.into_iter().enumerate() {
                        let base = result5
                            .add(i * (8 + 2 * ::core::mem::size_of::<*const u8>()));
                        {
                            let RankedDetection {
                                lang: lang3,
                                confidence: confidence3,
                            } = e;
                            let vec4 = (lang3.into_bytes()).into_boxed_slice();
                            let ptr4 = vec4.as_ptr().cast::<u8>();
                            let len4 = vec4.len();
                            ::core::mem::forget(vec4);
                            *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len4;
                            *base.add(0).cast::<*mut u8>() = ptr4.cast_mut();
                            *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<f64>() = _rt::as_f64(confidence3);
                        }
                    }
                    *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len5;
                    *ptr2.add(0).cast::<*mut u8>() = result5;
                    ptr2
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_detect_ranked<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base4 = l0;
                    let len4 = l1;
                    for i in 0..len4 {
                        let base = base4
                            .add(i * (8 + 2 * ::core::mem::size_of::<*const u8>()));
                        {
                            let l2 = *base.add(0).cast::<*mut u8>();
                            let l3 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l2, l3, 1);
                        }
                    }
                    _rt::cabi_dealloc(
                        base4,
                        len4 * (8 + 2 * ::core::mem::size_of::<*const u8>()),
                        8,
                    );
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_detect_from_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let base4 = arg2;
                    let len4 = arg3;
                    let mut result4 = _rt::Vec::with_capacity(len4);
                    for i in 0..len4 {
                        let base = base4
                            .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                        let e4 = {
                            let l1 = *base.add(0).cast::<*mut u8>();
                            let l2 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len3 = l2;
                            let bytes3 = _rt::Vec::from_raw_parts(l1.cast(), len3, len3);
                            _rt::string_lift(bytes3)
                        };
                        result4.push(e4);
                    }
                    _rt::cabi_dealloc(
                        base4,
                        len4 * (2 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result5 = T::detect_from(_rt::string_lift(bytes0), result4);
                    let ptr6 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result5 {
                        Some(e) => {
                            *ptr6.add(0).cast::<u8>() = (1i32) as u8;
                            let Detection {
                                lang: lang7,
                                lang_name: lang_name7,
                                script: script7,
                                confidence: confidence7,
                                reliable: reliable7,
                            } = e;
                            let vec8 = (lang7.into_bytes()).into_boxed_slice();
                            let ptr8 = vec8.as_ptr().cast::<u8>();
                            let len8 = vec8.len();
                            ::core::mem::forget(vec8);
                            *ptr6
                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len8;
                            *ptr6.add(8).cast::<*mut u8>() = ptr8.cast_mut();
                            let vec9 = (lang_name7.into_bytes()).into_boxed_slice();
                            let ptr9 = vec9.as_ptr().cast::<u8>();
                            let len9 = vec9.len();
                            ::core::mem::forget(vec9);
                            *ptr6
                                .add(8 + 3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len9;
                            *ptr6
                                .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr9.cast_mut();
                            let vec10 = (script7.into_bytes()).into_boxed_slice();
                            let ptr10 = vec10.as_ptr().cast::<u8>();
                            let len10 = vec10.len();
                            ::core::mem::forget(vec10);
                            *ptr6
                                .add(8 + 5 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len10;
                            *ptr6
                                .add(8 + 4 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr10.cast_mut();
                            *ptr6
                                .add(8 + 6 * ::core::mem::size_of::<*const u8>())
                                .cast::<f64>() = _rt::as_f64(confidence7);
                            *ptr6
                                .add(16 + 6 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (match reliable7 {
                                true => 1,
                                false => 0,
                            }) as u8;
                        }
                        None => {
                            *ptr6.add(0).cast::<u8>() = (0i32) as u8;
                        }
                    };
                    ptr6
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_detect_from<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {}
                        _ => {
                            let l1 = *arg0.add(8).cast::<*mut u8>();
                            let l2 = *arg0
                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                            let l3 = *arg0
                                .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l4 = *arg0
                                .add(8 + 3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l3, l4, 1);
                            let l5 = *arg0
                                .add(8 + 4 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l6 = *arg0
                                .add(8 + 5 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l5, l6, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_detect_mixed_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let result1 = T::detect_mixed(_rt::string_lift(bytes0));
                    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result1 {
                        Some(e) => {
                            *ptr2.add(0).cast::<u8>() = (1i32) as u8;
                            let vec5 = e;
                            let len5 = vec5.len();
                            let layout5 = _rt::alloc::Layout::from_size_align_unchecked(
                                vec5.len() * (16 + 2 * ::core::mem::size_of::<*const u8>()),
                                8,
                            );
                            let result5 = if layout5.size() != 0 {
                                let ptr = _rt::alloc::alloc(layout5).cast::<u8>();
                                if ptr.is_null() {
                                    _rt::alloc::handle_alloc_error(layout5);
                                }
                                ptr
                            } else {
                                ::core::ptr::null_mut()
                            };
                            for (i, e) in vec5.into_iter().enumerate() {
                                let base = result5
                                    .add(i * (16 + 2 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let SpanDetection {
                                        start: start3,
                                        end: end3,
                                        lang: lang3,
                                        confidence: confidence3,
                                    } = e;
                                    *base.add(0).cast::<i32>() = _rt::as_i32(start3);
                                    *base.add(4).cast::<i32>() = _rt::as_i32(end3);
                                    let vec4 = (lang3.into_bytes()).into_boxed_slice();
                                    let ptr4 = vec4.as_ptr().cast::<u8>();
                                    let len4 = vec4.len();
                                    ::core::mem::forget(vec4);
                                    *base
                                        .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len4;
                                    *base.add(8).cast::<*mut u8>() = ptr4.cast_mut();
                                    *base
                                        .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<f64>() = _rt::as_f64(confidence3);
                                }
                            }
                            *ptr2
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len5;
                            *ptr2
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = result5;
                        }
                        None => {
                            *ptr2.add(0).cast::<u8>() = (0i32) as u8;
                        }
                    };
                    ptr2
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_detect_mixed<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {}
                        _ => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base5 = l1;
                            let len5 = l2;
                            for i in 0..len5 {
                                let base = base5
                                    .add(i * (16 + 2 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let l3 = *base.add(8).cast::<*mut u8>();
                                    let l4 = *base
                                        .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l3, l4, 1);
                                }
                            }
                            _rt::cabi_dealloc(
                                base5,
                                len5 * (16 + 2 * ::core::mem::size_of::<*const u8>()),
                                8,
                            );
                        }
                    }
                }
                pub trait Guest {
                    /// Backend metadata. Callers cache this at load time.
                    /// WIT keeps type names and function names in the same namespace,
                    /// so the accessor can't share the `capabilities` name with the
                    /// record type. `get-capabilities` is the WIT convention for
                    /// "no-arg getter that returns a record of the same-ish name".
                    fn get_capabilities() -> Capabilities;
                    /// Single best guess. Every backend implements this. Returns
                    /// `none` when the input carries no reliable signal (too short,
                    /// digit-only, mixed-script the backend refuses to classify).
                    fn detect(text: _rt::String) -> Option<Detection>;
                    /// Ranked distribution across the backend's enabled languages.
                    /// Backends without `can-rank` return a one-element list carrying
                    /// the same value `detect` would return.
                    fn detect_ranked(text: _rt::String) -> _rt::Vec<RankedDetection>;
                    /// Constrained detection — consider only ISO 639-3 codes in
                    /// `langs`. Backends without `can-constrain` ignore the filter
                    /// and return their unconstrained best guess; callers should
                    /// check `capabilities.can-constrain` before relying on the
                    /// filter.
                    fn detect_from(
                        text: _rt::String,
                        langs: _rt::Vec<_rt::String>,
                    ) -> Option<Detection>;
                    /// Mixed-language segmentation. Backends without `can-segment`
                    /// return `none`.
                    fn detect_mixed(
                        text: _rt::String,
                    ) -> Option<_rt::Vec<SpanDetection>>;
                }
                #[doc(hidden)]
                macro_rules! __export_tegmentum_lang_detect_detector_0_2_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "tegmentum:lang-detect/detector@0.2.0#get-capabilities")] unsafe
                        extern "C" fn export_get_capabilities() -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_get_capabilities_cabi::<$ty > () } }
                        #[unsafe (export_name =
                        "cabi_post_tegmentum:lang-detect/detector@0.2.0#get-capabilities")]
                        unsafe extern "C" fn _post_return_get_capabilities(arg0 : * mut
                        u8,) { unsafe { $($path_to_types)*::
                        __post_return_get_capabilities::<$ty > (arg0) } } #[unsafe
                        (export_name = "tegmentum:lang-detect/detector@0.2.0#detect")]
                        unsafe extern "C" fn export_detect(arg0 : * mut u8, arg1 :
                        usize,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_detect_cabi::<$ty > (arg0, arg1) } } #[unsafe
                        (export_name =
                        "cabi_post_tegmentum:lang-detect/detector@0.2.0#detect")] unsafe
                        extern "C" fn _post_return_detect(arg0 : * mut u8,) { unsafe {
                        $($path_to_types)*:: __post_return_detect::<$ty > (arg0) } }
                        #[unsafe (export_name =
                        "tegmentum:lang-detect/detector@0.2.0#detect-ranked")] unsafe
                        extern "C" fn export_detect_ranked(arg0 : * mut u8, arg1 :
                        usize,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_detect_ranked_cabi::<$ty > (arg0, arg1) } } #[unsafe
                        (export_name =
                        "cabi_post_tegmentum:lang-detect/detector@0.2.0#detect-ranked")]
                        unsafe extern "C" fn _post_return_detect_ranked(arg0 : * mut u8,)
                        { unsafe { $($path_to_types)*:: __post_return_detect_ranked::<$ty
                        > (arg0) } } #[unsafe (export_name =
                        "tegmentum:lang-detect/detector@0.2.0#detect-from")] unsafe
                        extern "C" fn export_detect_from(arg0 : * mut u8, arg1 : usize,
                        arg2 : * mut u8, arg3 : usize,) -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_detect_from_cabi::<$ty > (arg0,
                        arg1, arg2, arg3) } } #[unsafe (export_name =
                        "cabi_post_tegmentum:lang-detect/detector@0.2.0#detect-from")]
                        unsafe extern "C" fn _post_return_detect_from(arg0 : * mut u8,) {
                        unsafe { $($path_to_types)*:: __post_return_detect_from::<$ty >
                        (arg0) } } #[unsafe (export_name =
                        "tegmentum:lang-detect/detector@0.2.0#detect-mixed")] unsafe
                        extern "C" fn export_detect_mixed(arg0 : * mut u8, arg1 : usize,)
                        -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_detect_mixed_cabi::<$ty > (arg0, arg1) } } #[unsafe
                        (export_name =
                        "cabi_post_tegmentum:lang-detect/detector@0.2.0#detect-mixed")]
                        unsafe extern "C" fn _post_return_detect_mixed(arg0 : * mut u8,)
                        { unsafe { $($path_to_types)*:: __post_return_detect_mixed::<$ty
                        > (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_tegmentum_lang_detect_detector_0_2_0_cabi;
                #[repr(align(8))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 24 + 6 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 24
                        + 6 * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub use alloc_crate::alloc;
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub fn as_f64<T: AsF64>(t: T) -> f64 {
        t.as_f64()
    }
    pub trait AsF64 {
        fn as_f64(self) -> f64;
    }
    impl<'a, T: Copy + AsF64> AsF64 for &'a T {
        fn as_f64(self) -> f64 {
            (*self).as_f64()
        }
    }
    impl AsF64 for f64 {
        #[inline]
        fn as_f64(self) -> f64 {
            self as f64
        }
    }
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_lang_detect_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::tegmentum::lang_detect::detector::__export_tegmentum_lang_detect_detector_0_2_0_cabi!($ty
        with_types_in $($path_to_types_root)*::
        exports::tegmentum::lang_detect::detector);
    };
}
#[doc(inline)]
pub(crate) use __export_lang_detect_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.41.0:tegmentum:lang-detect@0.2.0:lang-detect:encoded world")]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 626] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xf0\x03\x01A\x02\x01\
A\x02\x01B\x17\x01ps\x01r\x06\x07backends\x07versions\x08supports\0\x08can-rank\x7f\
\x0dcan-constrain\x7f\x0bcan-segment\x7f\x04\0\x0ccapabilities\x03\0\x01\x01r\x05\
\x04langs\x09lang-names\x06scripts\x0aconfidenceu\x08reliable\x7f\x04\0\x09detec\
tion\x03\0\x03\x01r\x02\x04langs\x0aconfidenceu\x04\0\x10ranked-detection\x03\0\x05\
\x01r\x04\x05starty\x03endy\x04langs\x0aconfidenceu\x04\0\x0espan-detection\x03\0\
\x07\x01@\0\0\x02\x04\0\x10get-capabilities\x01\x09\x01k\x04\x01@\x01\x04texts\0\
\x0a\x04\0\x06detect\x01\x0b\x01p\x06\x01@\x01\x04texts\0\x0c\x04\0\x0ddetect-ra\
nked\x01\x0d\x01@\x02\x04texts\x05langs\0\0\x0a\x04\0\x0bdetect-from\x01\x0e\x01\
p\x08\x01k\x0f\x01@\x01\x04texts\0\x10\x04\0\x0cdetect-mixed\x01\x11\x04\0$tegme\
ntum:lang-detect/detector@0.2.0\x05\0\x04\0'tegmentum:lang-detect/lang-detect@0.\
2.0\x04\0\x0b\x11\x01\0\x0blang-detect\x03\0\0\0G\x09producers\x01\x0cprocessed-\
by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
