// Generated by `wit-bindgen` 0.60.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod tegmentum {
        pub mod i18n_datetime {
            /// Shared types. Split into its own interface so the `datetime`
            /// and `capabilities` interfaces can `use` the same definitions.
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod types {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() =
                    super::super::super::super::__link_custom_section_describing_imports;

                use super::super::super::super::_rt;
                /// BCP 47 locale tag: "en", "de", "fr", "pt-BR".
                /// The empty string denotes the CLDR root locale.
                pub type Locale = _rt::String;
                /// The four CLDR-standard length classes shared by dates and
                /// times. Maps to the `dateFormats` and `timeFormats` length
                /// keys in CLDR's `gregorian.json`.
                #[repr(u8)]
                #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
                pub enum DateLength {
                    /// Shortest form (e.g. `"9/22/24"` en / `"22.09.24"` de).
                    Short,
                    /// Default "medium" form (e.g. `"Sep 22, 2024"`).
                    Medium,
                    /// Verbose form (e.g. `"September 22, 2024"`).
                    Long,
                    /// Most verbose form (e.g. `"Sunday, September 22, 2024"`).
                    Full,
                }
                impl ::core::fmt::Debug for DateLength {
                    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                        match self {
                            DateLength::Short => f.debug_tuple("DateLength::Short").finish(),
                            DateLength::Medium => f.debug_tuple("DateLength::Medium").finish(),
                            DateLength::Long => f.debug_tuple("DateLength::Long").finish(),
                            DateLength::Full => f.debug_tuple("DateLength::Full").finish(),
                        }
                    }
                }

                impl DateLength {
                    #[doc(hidden)]
                    pub unsafe fn _lift(val: u8) -> DateLength {
                        if !cfg!(debug_assertions) {
                            return unsafe { ::core::mem::transmute(val) };
                        }

                        match val {
                            0 => DateLength::Short,
                            1 => DateLength::Medium,
                            2 => DateLength::Long,
                            3 => DateLength::Full,

                            _ => panic!("invalid enum discriminant"),
                        }
                    }
                }

                /// Same length classes reused for the time component.
                /// Semantically equal to `date-length`; declared separately so a
                /// caller cannot pass the wrong axis to the wrong parameter.
                #[repr(u8)]
                #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
                pub enum TimeLength {
                    /// e.g. `"5:03 PM"` / `"17:03"`.
                    Short,
                    /// e.g. `"5:03:04 PM"` / `"17:03:04"`.
                    Medium,
                    /// e.g. `"5:03:04 PM"` (English CLDR treats medium and long
                    /// identically in the shipped Phase 4 pack).
                    Long,
                    /// e.g. `"5:03:04 PM"`.
                    Full,
                }
                impl ::core::fmt::Debug for TimeLength {
                    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                        match self {
                            TimeLength::Short => f.debug_tuple("TimeLength::Short").finish(),
                            TimeLength::Medium => f.debug_tuple("TimeLength::Medium").finish(),
                            TimeLength::Long => f.debug_tuple("TimeLength::Long").finish(),
                            TimeLength::Full => f.debug_tuple("TimeLength::Full").finish(),
                        }
                    }
                }

                impl TimeLength {
                    #[doc(hidden)]
                    pub unsafe fn _lift(val: u8) -> TimeLength {
                        if !cfg!(debug_assertions) {
                            return unsafe { ::core::mem::transmute(val) };
                        }

                        match val {
                            0 => TimeLength::Short,
                            1 => TimeLength::Medium,
                            2 => TimeLength::Long,
                            3 => TimeLength::Full,

                            _ => panic!("invalid enum discriminant"),
                        }
                    }
                }

                /// Errors surfaced by the date/time interface. Date/time
                /// formatting is total on valid ISO-8601 input; failure modes
                /// are structural or reflect a malformed input string.
                #[derive(Clone)]
                pub enum DatetimeError {
                    /// The locale tag was not a well-formed BCP 47 tag.
                    InvalidLocale(_rt::String),
                    /// No pack was loaded for the requested locale and no
                    /// fallback in the CLDR chain resolved.
                    LocaleUnavailable(_rt::String),
                    /// The `iso-date`, `iso-time`, or `iso-datetime` input was
                    /// not a well-formed ISO-8601 string. Payload carries the
                    /// offending input for diagnostic surfacing.
                    InvalidInput(_rt::String),
                    /// The parsed input represented an out-of-range value
                    /// (e.g. `2024-02-30`, `25:00:00`). Payload names the
                    /// specific field.
                    OutOfRange(_rt::String),
                }
                impl ::core::fmt::Debug for DatetimeError {
                    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                        match self {
                            DatetimeError::InvalidLocale(e) => f
                                .debug_tuple("DatetimeError::InvalidLocale")
                                .field(e)
                                .finish(),
                            DatetimeError::LocaleUnavailable(e) => f
                                .debug_tuple("DatetimeError::LocaleUnavailable")
                                .field(e)
                                .finish(),
                            DatetimeError::InvalidInput(e) => f
                                .debug_tuple("DatetimeError::InvalidInput")
                                .field(e)
                                .finish(),
                            DatetimeError::OutOfRange(e) => {
                                f.debug_tuple("DatetimeError::OutOfRange").field(e).finish()
                            }
                        }
                    }
                }
                impl ::core::fmt::Display for DatetimeError {
                    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                        write!(f, "{:?}", self)
                    }
                }

                impl ::core::error::Error for DatetimeError {}
                #[doc(hidden)]

                macro_rules! __export_tegmentum_i18n_datetime_types_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _: () = {};
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_tegmentum_i18n_datetime_types_0_1_0_cabi;
            }

            /// The core date/time-formatting surface.
            ///
            /// Every function takes an ISO-8601 input string plus a locale
            /// tag and a length class, and returns the CLDR-pattern-driven
            /// rendering. The functions are time-zone-naive: whatever offset
            /// (or lack thereof) the input carries is preserved literally.
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod datetime {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() =
                    super::super::super::super::__link_custom_section_describing_imports;

                use super::super::super::super::_rt;
                pub type Locale =
                    super::super::super::super::exports::tegmentum::i18n_datetime::types::Locale;
                pub type DateLength = super::super::super::super::exports::tegmentum::i18n_datetime::types::DateLength;
                pub type TimeLength = super::super::super::super::exports::tegmentum::i18n_datetime::types::TimeLength;
                pub type DatetimeError = super::super::super::super::exports::tegmentum::i18n_datetime::types::DatetimeError;
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_format_date_cabi<T_: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                    arg4: i32,
                ) -> *mut u8 {
                    unsafe {
                        #[cfg(target_arch = "wasm32")]
                        _rt::run_ctors_once();
                        let result2 = {
                            let len0 = arg1;
                            let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                            let len1 = arg3;
                            let bytes1 = _rt::Vec::from_raw_parts(arg2.cast(), len1, len1);
                            T_::format_date(_rt::string_lift(bytes0), _rt::string_lift(bytes1), super::super::super::super::exports::tegmentum::i18n_datetime::types::DateLength::_lift(arg4 as u8))
                        };
                        let ptr3 = (&raw mut _RET_AREA.0).cast::<u8>();
                        match result2 {
                            Ok(e) => {
                                *ptr3.add(0).cast::<u8>() = (0i32) as u8;
                                let vec4 = (e.into_bytes()).into_boxed_slice();
                                let ptr4 = vec4.as_ptr().cast::<u8>();
                                let len4 = vec4.len();
                                ::core::mem::forget(vec4);
                                *ptr3
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>() = len4;
                                *ptr3
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>() = ptr4.cast_mut();
                            }
                            Err(e) => {
                                *ptr3.add(0).cast::<u8>() = (1i32) as u8;
                                use super::super::super::super::exports::tegmentum::i18n_datetime::types::DatetimeError as V9;
                                match e {
                                    V9::InvalidLocale(e) => {
                                        *ptr3
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<u8>() = (0i32) as u8;
                                        let vec5 = (e.into_bytes()).into_boxed_slice();
                                        let ptr5 = vec5.as_ptr().cast::<u8>();
                                        let len5 = vec5.len();
                                        ::core::mem::forget(vec5);
                                        *ptr3
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>() = len5;
                                        *ptr3
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>() = ptr5.cast_mut();
                                    }
                                    V9::LocaleUnavailable(e) => {
                                        *ptr3
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<u8>() = (1i32) as u8;
                                        let vec6 = (e.into_bytes()).into_boxed_slice();
                                        let ptr6 = vec6.as_ptr().cast::<u8>();
                                        let len6 = vec6.len();
                                        ::core::mem::forget(vec6);
                                        *ptr3
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>() = len6;
                                        *ptr3
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>() = ptr6.cast_mut();
                                    }
                                    V9::InvalidInput(e) => {
                                        *ptr3
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<u8>() = (2i32) as u8;
                                        let vec7 = (e.into_bytes()).into_boxed_slice();
                                        let ptr7 = vec7.as_ptr().cast::<u8>();
                                        let len7 = vec7.len();
                                        ::core::mem::forget(vec7);
                                        *ptr3
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>() = len7;
                                        *ptr3
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>() = ptr7.cast_mut();
                                    }
                                    V9::OutOfRange(e) => {
                                        *ptr3
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<u8>() = (3i32) as u8;
                                        let vec8 = (e.into_bytes()).into_boxed_slice();
                                        let ptr8 = vec8.as_ptr().cast::<u8>();
                                        let len8 = vec8.len();
                                        ::core::mem::forget(vec8);
                                        *ptr3
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>() = len8;
                                        *ptr3
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>() = ptr8.cast_mut();
                                    }
                                }
                            }
                        };
                        ptr3
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_format_date<T_: Guest>(arg0: *mut u8) {
                    unsafe {
                        let l0 = i32::from(*arg0.add(0).cast::<u8>());
                        match l0 {
                            0 => {
                                let l1 = *arg0
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l2 = *arg0
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                _rt::cabi_dealloc(l1, l2, 1);
                            }
                            _ => {
                                let l3 = i32::from(
                                    *arg0.add(::core::mem::size_of::<*const u8>()).cast::<u8>(),
                                );
                                match l3 {
                                    0 => {
                                        let l4 = *arg0
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l5 = *arg0
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        _rt::cabi_dealloc(l4, l5, 1);
                                    }
                                    1 => {
                                        let l6 = *arg0
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l7 = *arg0
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        _rt::cabi_dealloc(l6, l7, 1);
                                    }
                                    2 => {
                                        let l8 = *arg0
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l9 = *arg0
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        _rt::cabi_dealloc(l8, l9, 1);
                                    }
                                    _ => {
                                        let l10 = *arg0
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l11 = *arg0
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        _rt::cabi_dealloc(l10, l11, 1);
                                    }
                                }
                            }
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_format_time_cabi<T_: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                    arg4: i32,
                ) -> *mut u8 {
                    unsafe {
                        #[cfg(target_arch = "wasm32")]
                        _rt::run_ctors_once();
                        let result2 = {
                            let len0 = arg1;
                            let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                            let len1 = arg3;
                            let bytes1 = _rt::Vec::from_raw_parts(arg2.cast(), len1, len1);
                            T_::format_time(_rt::string_lift(bytes0), _rt::string_lift(bytes1), super::super::super::super::exports::tegmentum::i18n_datetime::types::TimeLength::_lift(arg4 as u8))
                        };
                        let ptr3 = (&raw mut _RET_AREA.0).cast::<u8>();
                        match result2 {
                            Ok(e) => {
                                *ptr3.add(0).cast::<u8>() = (0i32) as u8;
                                let vec4 = (e.into_bytes()).into_boxed_slice();
                                let ptr4 = vec4.as_ptr().cast::<u8>();
                                let len4 = vec4.len();
                                ::core::mem::forget(vec4);
                                *ptr3
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>() = len4;
                                *ptr3
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>() = ptr4.cast_mut();
                            }
                            Err(e) => {
                                *ptr3.add(0).cast::<u8>() = (1i32) as u8;
                                use super::super::super::super::exports::tegmentum::i18n_datetime::types::DatetimeError as V9;
                                match e {
                                    V9::InvalidLocale(e) => {
                                        *ptr3
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<u8>() = (0i32) as u8;
                                        let vec5 = (e.into_bytes()).into_boxed_slice();
                                        let ptr5 = vec5.as_ptr().cast::<u8>();
                                        let len5 = vec5.len();
                                        ::core::mem::forget(vec5);
                                        *ptr3
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>() = len5;
                                        *ptr3
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>() = ptr5.cast_mut();
                                    }
                                    V9::LocaleUnavailable(e) => {
                                        *ptr3
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<u8>() = (1i32) as u8;
                                        let vec6 = (e.into_bytes()).into_boxed_slice();
                                        let ptr6 = vec6.as_ptr().cast::<u8>();
                                        let len6 = vec6.len();
                                        ::core::mem::forget(vec6);
                                        *ptr3
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>() = len6;
                                        *ptr3
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>() = ptr6.cast_mut();
                                    }
                                    V9::InvalidInput(e) => {
                                        *ptr3
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<u8>() = (2i32) as u8;
                                        let vec7 = (e.into_bytes()).into_boxed_slice();
                                        let ptr7 = vec7.as_ptr().cast::<u8>();
                                        let len7 = vec7.len();
                                        ::core::mem::forget(vec7);
                                        *ptr3
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>() = len7;
                                        *ptr3
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>() = ptr7.cast_mut();
                                    }
                                    V9::OutOfRange(e) => {
                                        *ptr3
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<u8>() = (3i32) as u8;
                                        let vec8 = (e.into_bytes()).into_boxed_slice();
                                        let ptr8 = vec8.as_ptr().cast::<u8>();
                                        let len8 = vec8.len();
                                        ::core::mem::forget(vec8);
                                        *ptr3
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>() = len8;
                                        *ptr3
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>() = ptr8.cast_mut();
                                    }
                                }
                            }
                        };
                        ptr3
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_format_time<T_: Guest>(arg0: *mut u8) {
                    unsafe {
                        let l0 = i32::from(*arg0.add(0).cast::<u8>());
                        match l0 {
                            0 => {
                                let l1 = *arg0
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l2 = *arg0
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                _rt::cabi_dealloc(l1, l2, 1);
                            }
                            _ => {
                                let l3 = i32::from(
                                    *arg0.add(::core::mem::size_of::<*const u8>()).cast::<u8>(),
                                );
                                match l3 {
                                    0 => {
                                        let l4 = *arg0
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l5 = *arg0
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        _rt::cabi_dealloc(l4, l5, 1);
                                    }
                                    1 => {
                                        let l6 = *arg0
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l7 = *arg0
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        _rt::cabi_dealloc(l6, l7, 1);
                                    }
                                    2 => {
                                        let l8 = *arg0
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l9 = *arg0
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        _rt::cabi_dealloc(l8, l9, 1);
                                    }
                                    _ => {
                                        let l10 = *arg0
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l11 = *arg0
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        _rt::cabi_dealloc(l10, l11, 1);
                                    }
                                }
                            }
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_format_datetime_cabi<T_: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                    arg4: i32,
                    arg5: i32,
                ) -> *mut u8 {
                    unsafe {
                        #[cfg(target_arch = "wasm32")]
                        _rt::run_ctors_once();
                        let result2 = {
                            let len0 = arg1;
                            let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                            let len1 = arg3;
                            let bytes1 = _rt::Vec::from_raw_parts(arg2.cast(), len1, len1);
                            T_::format_datetime(_rt::string_lift(bytes0), _rt::string_lift(bytes1), super::super::super::super::exports::tegmentum::i18n_datetime::types::DateLength::_lift(arg4 as u8), super::super::super::super::exports::tegmentum::i18n_datetime::types::TimeLength::_lift(arg5 as u8))
                        };
                        let ptr3 = (&raw mut _RET_AREA.0).cast::<u8>();
                        match result2 {
                            Ok(e) => {
                                *ptr3.add(0).cast::<u8>() = (0i32) as u8;
                                let vec4 = (e.into_bytes()).into_boxed_slice();
                                let ptr4 = vec4.as_ptr().cast::<u8>();
                                let len4 = vec4.len();
                                ::core::mem::forget(vec4);
                                *ptr3
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>() = len4;
                                *ptr3
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>() = ptr4.cast_mut();
                            }
                            Err(e) => {
                                *ptr3.add(0).cast::<u8>() = (1i32) as u8;
                                use super::super::super::super::exports::tegmentum::i18n_datetime::types::DatetimeError as V9;
                                match e {
                                    V9::InvalidLocale(e) => {
                                        *ptr3
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<u8>() = (0i32) as u8;
                                        let vec5 = (e.into_bytes()).into_boxed_slice();
                                        let ptr5 = vec5.as_ptr().cast::<u8>();
                                        let len5 = vec5.len();
                                        ::core::mem::forget(vec5);
                                        *ptr3
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>() = len5;
                                        *ptr3
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>() = ptr5.cast_mut();
                                    }
                                    V9::LocaleUnavailable(e) => {
                                        *ptr3
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<u8>() = (1i32) as u8;
                                        let vec6 = (e.into_bytes()).into_boxed_slice();
                                        let ptr6 = vec6.as_ptr().cast::<u8>();
                                        let len6 = vec6.len();
                                        ::core::mem::forget(vec6);
                                        *ptr3
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>() = len6;
                                        *ptr3
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>() = ptr6.cast_mut();
                                    }
                                    V9::InvalidInput(e) => {
                                        *ptr3
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<u8>() = (2i32) as u8;
                                        let vec7 = (e.into_bytes()).into_boxed_slice();
                                        let ptr7 = vec7.as_ptr().cast::<u8>();
                                        let len7 = vec7.len();
                                        ::core::mem::forget(vec7);
                                        *ptr3
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>() = len7;
                                        *ptr3
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>() = ptr7.cast_mut();
                                    }
                                    V9::OutOfRange(e) => {
                                        *ptr3
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<u8>() = (3i32) as u8;
                                        let vec8 = (e.into_bytes()).into_boxed_slice();
                                        let ptr8 = vec8.as_ptr().cast::<u8>();
                                        let len8 = vec8.len();
                                        ::core::mem::forget(vec8);
                                        *ptr3
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>() = len8;
                                        *ptr3
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>() = ptr8.cast_mut();
                                    }
                                }
                            }
                        };
                        ptr3
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_format_datetime<T_: Guest>(arg0: *mut u8) {
                    unsafe {
                        let l0 = i32::from(*arg0.add(0).cast::<u8>());
                        match l0 {
                            0 => {
                                let l1 = *arg0
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l2 = *arg0
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                _rt::cabi_dealloc(l1, l2, 1);
                            }
                            _ => {
                                let l3 = i32::from(
                                    *arg0.add(::core::mem::size_of::<*const u8>()).cast::<u8>(),
                                );
                                match l3 {
                                    0 => {
                                        let l4 = *arg0
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l5 = *arg0
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        _rt::cabi_dealloc(l4, l5, 1);
                                    }
                                    1 => {
                                        let l6 = *arg0
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l7 = *arg0
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        _rt::cabi_dealloc(l6, l7, 1);
                                    }
                                    2 => {
                                        let l8 = *arg0
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l9 = *arg0
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        _rt::cabi_dealloc(l8, l9, 1);
                                    }
                                    _ => {
                                        let l10 = *arg0
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l11 = *arg0
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        _rt::cabi_dealloc(l10, l11, 1);
                                    }
                                }
                            }
                        }
                    }
                }
                pub trait Guest {
                    /// Format an ISO-8601 date-only string (`"YYYY-MM-DD"`).
                    ///
                    /// Returns a string rendered against the locale's date pattern
                    /// at the requested length. See the CLDR pattern reference for
                    /// the exact tokens each pack ships:
                    /// <https://cldr.unicode.org/translation/date-time-1/date-time-patterns>.
                    #[allow(async_fn_in_trait)]
                    fn format_date(
                        iso_date: _rt::String,
                        locale: Locale,
                        length: DateLength,
                    ) -> Result<_rt::String, DatetimeError>;
                    /// Format an ISO-8601 time-of-day string
                    /// (`"HH:MM:SS"` or `"HH:MM:SS.sss"`).
                    ///
                    /// Returns a string rendered against the locale's time pattern
                    /// at the requested length. Milliseconds in the input are
                    /// discarded — Phase 4 does not render sub-second precision.
                    #[allow(async_fn_in_trait)]
                    fn format_time(
                        iso_time: _rt::String,
                        locale: Locale,
                        length: TimeLength,
                    ) -> Result<_rt::String, DatetimeError>;
                    /// Format a combined ISO-8601 date-time string
                    /// (`"YYYY-MM-DDTHH:MM:SS"`, optionally with `Z` or `±HH:MM`).
                    ///
                    /// Returns `"<date> <time>"` concatenation using the two
                    /// selected length classes. Timezone information carried by
                    /// the input is discarded — the shipped Phase 4 pack has no
                    /// timezone-aware behaviour.
                    #[allow(async_fn_in_trait)]
                    fn format_datetime(
                        iso_datetime: _rt::String,
                        locale: Locale,
                        date_length: DateLength,
                        time_length: TimeLength,
                    ) -> Result<_rt::String, DatetimeError>;
                }
                #[doc(hidden)]

                macro_rules! __export_tegmentum_i18n_datetime_datetime_0_1_0_cabi{
    ($ty:ident with_types_in $($path_to_types:tt)*) => (const _: () = {

      #[unsafe(export_name = "tegmentum:i18n-datetime/datetime@0.1.0#format-date")]
      unsafe extern "C" fn export_format_date(arg0: *mut u8,arg1: usize,arg2: *mut u8,arg3: usize,arg4: i32,) -> *mut u8 {
        unsafe { $($path_to_types)*::_export_format_date_cabi::<$ty>(arg0, arg1, arg2, arg3, arg4) }
      }
      #[unsafe(export_name = "cabi_post_tegmentum:i18n-datetime/datetime@0.1.0#format-date")]
      unsafe extern "C" fn _post_return_format_date(arg0: *mut u8,) {
        unsafe { $($path_to_types)*::__post_return_format_date::<$ty>(arg0) }
      }
      #[unsafe(export_name = "tegmentum:i18n-datetime/datetime@0.1.0#format-time")]
      unsafe extern "C" fn export_format_time(arg0: *mut u8,arg1: usize,arg2: *mut u8,arg3: usize,arg4: i32,) -> *mut u8 {
        unsafe { $($path_to_types)*::_export_format_time_cabi::<$ty>(arg0, arg1, arg2, arg3, arg4) }
      }
      #[unsafe(export_name = "cabi_post_tegmentum:i18n-datetime/datetime@0.1.0#format-time")]
      unsafe extern "C" fn _post_return_format_time(arg0: *mut u8,) {
        unsafe { $($path_to_types)*::__post_return_format_time::<$ty>(arg0) }
      }
      #[unsafe(export_name = "tegmentum:i18n-datetime/datetime@0.1.0#format-datetime")]
      unsafe extern "C" fn export_format_datetime(arg0: *mut u8,arg1: usize,arg2: *mut u8,arg3: usize,arg4: i32,arg5: i32,) -> *mut u8 {
        unsafe { $($path_to_types)*::_export_format_datetime_cabi::<$ty>(arg0, arg1, arg2, arg3, arg4, arg5) }
      }
      #[unsafe(export_name = "cabi_post_tegmentum:i18n-datetime/datetime@0.1.0#format-datetime")]
      unsafe extern "C" fn _post_return_format_datetime(arg0: *mut u8,) {
        unsafe { $($path_to_types)*::__post_return_format_datetime::<$ty>(arg0) }
      }
    };);
  }
                #[doc(hidden)]
                pub(crate) use __export_tegmentum_i18n_datetime_datetime_0_1_0_cabi;

                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<u8>; 4 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 4 * ::core::mem::size_of::<*const u8>()],
                );
            }

            /// Introspection: which locales does the linked component actually
            /// cover?
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod capabilities {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() =
                    super::super::super::super::__link_custom_section_describing_imports;

                use super::super::super::super::_rt;
                pub type Locale =
                    super::super::super::super::exports::tegmentum::i18n_datetime::types::Locale;
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_supported_locales_cabi<T_: Guest>() -> *mut u8 {
                    unsafe {
                        #[cfg(target_arch = "wasm32")]
                        _rt::run_ctors_once();
                        let result0 = { T_::supported_locales() };
                        let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                        let vec3 = result0;
                        let len3 = vec3.len();
                        let layout3 = _rt::alloc::Layout::from_size_align(
                            vec3.len() * (2 * ::core::mem::size_of::<*const u8>()),
                            ::core::mem::size_of::<*const u8>(),
                        )
                        .unwrap();
                        let (result3, _cleanup3) = wit_bindgen_rt::Cleanup::new(layout3);
                        if let Some(cleanup) = _cleanup3 {
                            cleanup.forget();
                        }
                        for (i, e) in vec3.into_iter().enumerate() {
                            let base = result3.add(i * (2 * ::core::mem::size_of::<*const u8>()));
                            {
                                let vec2 = (e.into_bytes()).into_boxed_slice();
                                let ptr2 = vec2.as_ptr().cast::<u8>();
                                let len2 = vec2.len();
                                ::core::mem::forget(vec2);
                                *base
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<usize>() = len2;
                                *base.add(0).cast::<*mut u8>() = ptr2.cast_mut();
                            }
                        }
                        *ptr1
                            .add(::core::mem::size_of::<*const u8>())
                            .cast::<usize>() = len3;
                        *ptr1.add(0).cast::<*mut u8>() = result3;
                        ptr1
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_supported_locales<T_: Guest>(arg0: *mut u8) {
                    unsafe {
                        let l0 = *arg0.add(0).cast::<*mut u8>();
                        let l1 = *arg0
                            .add(::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let base4 = l0;
                        let len4 = l1;
                        for i in 0..len4 {
                            let base = base4.add(i * (2 * ::core::mem::size_of::<*const u8>()));
                            {
                                let l2 = *base.add(0).cast::<*mut u8>();
                                let l3 = *base
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                _rt::cabi_dealloc(l2, l3, 1);
                            }
                        }
                        _rt::cabi_dealloc(
                            base4,
                            len4 * (2 * ::core::mem::size_of::<*const u8>()),
                            ::core::mem::size_of::<*const u8>(),
                        );
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_supports_cabi<T_: Guest>(arg0: *mut u8, arg1: usize) -> i32 {
                    unsafe {
                        #[cfg(target_arch = "wasm32")]
                        _rt::run_ctors_once();
                        let result1 = {
                            let len0 = arg1;
                            let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                            T_::supports(_rt::string_lift(bytes0))
                        };
                        match result1 {
                            true => 1,
                            false => 0,
                        }
                    }
                }
                pub trait Guest {
                    /// Every BCP 47 tag this component's linked packs cover.
                    #[allow(async_fn_in_trait)]
                    fn supported_locales() -> _rt::Vec<Locale>;
                    /// True iff a query in the given locale would use a pack
                    /// (rather than falling through to root).
                    #[allow(async_fn_in_trait)]
                    fn supports(loc: Locale) -> bool;
                }
                #[doc(hidden)]

                macro_rules! __export_tegmentum_i18n_datetime_capabilities_0_1_0_cabi{
  ($ty:ident with_types_in $($path_to_types:tt)*) => (const _: () = {

    #[unsafe(export_name = "tegmentum:i18n-datetime/capabilities@0.1.0#supported-locales")]
    unsafe extern "C" fn export_supported_locales() -> *mut u8 {
      unsafe { $($path_to_types)*::_export_supported_locales_cabi::<$ty>() }
    }
    #[unsafe(export_name = "cabi_post_tegmentum:i18n-datetime/capabilities@0.1.0#supported-locales")]
    unsafe extern "C" fn _post_return_supported_locales(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_supported_locales::<$ty>(arg0) }
    }
    #[unsafe(export_name = "tegmentum:i18n-datetime/capabilities@0.1.0#supports")]
    unsafe extern "C" fn export_supports(arg0: *mut u8,arg1: usize,) -> i32 {
      unsafe { $($path_to_types)*::_export_supports_cabi::<$ty>(arg0, arg1) }
    }
  };);
}
                #[doc(hidden)]
                pub(crate) use __export_tegmentum_i18n_datetime_capabilities_0_1_0_cabi;

                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<u8>; 2 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 2 * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
mod _rt {
    #![allow(dead_code, unused_imports, clippy::all)]
    pub use alloc_crate::string::String;

    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub use alloc_crate::vec::Vec;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            unsafe { String::from_utf8_unchecked(bytes) }
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        unsafe {
            let layout = alloc::Layout::from_size_align_unchecked(size, align);
            alloc::dealloc(ptr, layout);
        }
    }
    pub use alloc_crate::alloc;
    extern crate alloc as alloc_crate;
}

/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]

macro_rules! __export_datetime_world_impl {
  ($ty:ident) => (self::export!($ty with_types_in self););
  ($ty:ident with_types_in $($path_to_types_root:tt)*) => (
  $($path_to_types_root)*::exports::tegmentum::i18n_datetime::types::__export_tegmentum_i18n_datetime_types_0_1_0_cabi!($ty with_types_in $($path_to_types_root)*::exports::tegmentum::i18n_datetime::types);
  $($path_to_types_root)*::exports::tegmentum::i18n_datetime::datetime::__export_tegmentum_i18n_datetime_datetime_0_1_0_cabi!($ty with_types_in $($path_to_types_root)*::exports::tegmentum::i18n_datetime::datetime);
  $($path_to_types_root)*::exports::tegmentum::i18n_datetime::capabilities::__export_tegmentum_i18n_datetime_capabilities_0_1_0_cabi!($ty with_types_in $($path_to_types_root)*::exports::tegmentum::i18n_datetime::capabilities);
  )
}
#[doc(inline)]
pub(crate) use __export_datetime_world_impl as export;

#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.60.0:tegmentum:i18n-datetime@0.1.0:datetime-world:encoded world")]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 914] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\x8d\x06\x01A\x02\x01\
A\x0a\x01B\x08\x01s\x04\0\x06locale\x03\0\0\x01m\x04\x05short\x06medium\x04long\x04\
full\x04\0\x0bdate-length\x03\0\x02\x01m\x04\x05short\x06medium\x04long\x04full\x04\
\0\x0btime-length\x03\0\x04\x01q\x04\x0einvalid-locale\x01s\0\x12locale-unavaila\
ble\x01s\0\x0dinvalid-input\x01s\0\x0cout-of-range\x01s\0\x04\0\x0edatetime-erro\
r\x03\0\x06\x04\0#tegmentum:i18n-datetime/types@0.1.0\x05\0\x02\x03\0\0\x06local\
e\x02\x03\0\0\x0bdate-length\x02\x03\0\0\x0btime-length\x02\x03\0\0\x0edatetime-\
error\x01B\x0f\x02\x03\x02\x01\x01\x04\0\x06locale\x03\0\0\x02\x03\x02\x01\x02\x04\
\0\x0bdate-length\x03\0\x02\x02\x03\x02\x01\x03\x04\0\x0btime-length\x03\0\x04\x02\
\x03\x02\x01\x04\x04\0\x0edatetime-error\x03\0\x06\x01j\x01s\x01\x07\x01@\x03\x08\
iso-dates\x06locale\x01\x06length\x03\0\x08\x04\0\x0bformat-date\x01\x09\x01@\x03\
\x08iso-times\x06locale\x01\x06length\x05\0\x08\x04\0\x0bformat-time\x01\x0a\x01\
@\x04\x0ciso-datetimes\x06locale\x01\x0bdate-length\x03\x0btime-length\x05\0\x08\
\x04\0\x0fformat-datetime\x01\x0b\x04\0&tegmentum:i18n-datetime/datetime@0.1.0\x05\
\x05\x01B\x07\x02\x03\x02\x01\x01\x04\0\x06locale\x03\0\0\x01p\x01\x01@\0\0\x02\x04\
\0\x11supported-locales\x01\x03\x01@\x01\x03loc\x01\0\x7f\x04\0\x08supports\x01\x04\
\x04\0*tegmentum:i18n-datetime/capabilities@0.1.0\x05\x06\x04\0,tegmentum:i18n-d\
atetime/datetime-world@0.1.0\x04\0\x0b\x14\x01\0\x0edatetime-world\x03\0\0\0G\x09\
producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.254.0\x10wit-bindgen-rus\
t\x060.60.0";

#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
