//! Wasmtime smoke test for the reference `stringcheese:icu-case@0.1.0`
//! component.
//!
//! Verifies WIT-i18n Phase 1's deferred "componentised WASM build"
//! bit (`docs/design/wit-i18n.md` § 8.1). The test drives the
//! component the same way any external caller would: builds it
//! under `wasm32-wasip1 --features wit-component`, componentises
//! it via `wasm-tools`, then loads the componentised `.wasm` into
//! an in-process wasmtime `Engine` and calls each of the WIT
//! exports (`to-lower`, `to-upper`, `to-title`, `fold`,
//! `supported-locales`, `supports`) through typed bindings
//! generated by `wasmtime::component::bindgen!` from the shipped
//! WIT file. Assertions are on the returned Rust values.
//!
//! # Prerequisites
//!
//! Requires two tools on `$PATH`:
//!
//! * `cargo` with the `wasm32-wasip1` target installed
//! * `wasm-tools` (Bytecode Alliance) — used only for
//!   `component new` to produce the component encoding from the
//!   plain wasm module.
//!
//! Plus one file on disk — the WASI preview1 → preview2 reactor
//! adapter — discoverable via the search order documented in
//! [`find_wasi_adapter`]. The adapter version must match the
//! wasmtime crate version (both 26.x on CI); a version mismatch
//! surfaces as an import-mismatch panic at `Linker::instantiate`
//! time.
//!
//! When any of these prerequisites is missing the test soft-skips
//! with a diagnostic — matching the "conformance runner"
//! convention used by `stringcheese-tokenizer-hf`'s real-vocab
//! tests. This keeps host `cargo test` green on developer
//! machines that haven't installed the wasm toolchain; CI
//! installs both tools and downloads the version-matched adapter
//! explicitly (see the `wasm-i18n-case-component` job).
//!
//! # Why the wasmtime crate instead of `wasmtime run --invoke`
//!
//! Same rationale as `stringcheese-tokenizer-component`'s
//! smoke: wasmtime 20+ removed `--invoke` for components (only
//! core modules retain it). The rewrite embeds wasmtime as a
//! dev-dep and calls the exports through the typed bindings the
//! `bindgen!` macro produces from
//! `component/wit/icu-case/stringcheese-icu-case.wit`.

#![cfg(not(target_family = "wasm"))]
#![allow(unsafe_code)]

use std::path::PathBuf;
use std::process::Command;
use std::sync::OnceLock;

use wasmtime::component::{Component, Linker, ResourceTable};
use wasmtime::{Engine, Store};
use wasmtime_wasi::{WasiCtx, WasiCtxBuilder, WasiView};

// Typed bindings generated from the shipped WIT contract. The
// macro mirrors the `case` world the guest crate exports, but
// from the host side — the generated `Case` struct is what we
// instantiate against a linker below, and its
// `stringcheese_icu_case_*()` accessors return typed handles to
// the exported interfaces. The macro expansion emits several
// items without doc comments; wrapping in a module lets us scope
// a single `#[allow(missing_docs)]` around the generated code.
#[allow(missing_docs, clippy::pedantic, clippy::nursery)]
mod bindgen {
    wasmtime::component::bindgen!({
        world: "case",
        path: "../../component/wit/icu-case",
    });
}

use bindgen::Case;
use bindgen::exports::stringcheese::icu_case::mapping::TitleOptions as WitTitleOptions;
use bindgen::exports::stringcheese::icu_case::types::CaseError as WitCaseError;
use bindgen::exports::stringcheese::icu_case::types::FoldMode as WitFoldMode;
use bindgen::exports::stringcheese::icu_case::types::TitleBoundary as WitTitleBoundary;

/// Host state carried in the `Store<T>`. Holds the WASI preview2
/// context and a `ResourceTable` for any WASI resources
/// instantiated during a call. The case component never touches
/// either — it performs no I/O — but a `WasiView` impl is still
/// required so the linker can wire the imported `wasi:*`
/// interfaces exposed by the wasip1 → wasip2 adapter.
struct HostState {
    table: ResourceTable,
    wasi: WasiCtx,
}

impl WasiView for HostState {
    fn ctx(&mut self) -> &mut WasiCtx {
        &mut self.wasi
    }
    fn table(&mut self) -> &mut ResourceTable {
        &mut self.table
    }
}

/// One end-to-end build-and-load: shell out to `cargo build` +
/// `wasm-tools component new` once, load the resulting `.wasm`
/// into a wasmtime `Engine`, and cache the immutable
/// engine/component/linker on the shared `OnceLock` so every test
/// instantiates cheaply.
struct SmokeHarness {
    engine: Engine,
    component: Component,
    linker: Linker<HostState>,
}

/// The smoke tests run concurrently under `cargo test`'s default
/// thread pool. Each calls `SmokeHarness::build_or_skip`; without
/// a guard the threads would race on the same
/// `target/wasm32-wasip1/release/` directory and `wasm-tools`
/// output path, producing spurious failures when one test's
/// componentise step reads a wasm the other is still writing.
/// This `OnceLock<Option<PathBuf>>` serialises the build-once,
/// componentise-once step across every caller — subsequent
/// invocations get back the cached component path (or the cached
/// skip decision) without re-invoking cargo / wasm-tools.
static SHARED_COMPONENT: OnceLock<Option<PathBuf>> = OnceLock::new();

impl SmokeHarness {
    fn build_or_skip() -> Option<Self> {
        let component_wasm = SHARED_COMPONENT
            .get_or_init(Self::build_shared_once)
            .clone()?;

        let engine = Engine::default();
        let component = match Component::from_file(&engine, &component_wasm) {
            Ok(c) => c,
            Err(e) => {
                eprintln!(
                    "SKIP: wasmtime failed to load component at {}: {e}",
                    component_wasm.display()
                );
                return None;
            }
        };
        let mut linker: Linker<HostState> = Linker::new(&engine);
        if let Err(e) = wasmtime_wasi::add_to_linker_sync(&mut linker) {
            eprintln!("SKIP: could not add WASI to linker: {e}");
            return None;
        }
        Some(Self {
            engine,
            component,
            linker,
        })
    }

    fn build_shared_once() -> Option<PathBuf> {
        if !has_tool("cargo") {
            eprintln!("SKIP: cargo not on PATH");
            return None;
        }
        if !has_tool("wasm-tools") {
            eprintln!(
                "SKIP: wasm-tools not on PATH — install from https://github.com/bytecodealliance/wasm-tools"
            );
            return None;
        }
        if !target_installed("wasm32-wasip1") {
            eprintln!(
                "SKIP: wasm32-wasip1 target not installed — `rustup target add wasm32-wasip1`"
            );
            return None;
        }

        let workspace_root = workspace_root();
        let build = Command::new("cargo")
            .current_dir(&workspace_root)
            .args([
                "build",
                "-p",
                "stringcheese-icu-case-component",
                "--target",
                "wasm32-wasip1",
                "--features",
                "wit-component",
                "--release",
            ])
            .status()
            .expect("cargo build must launch");
        assert!(
            build.success(),
            "cargo build for wasm32-wasip1 must succeed",
        );

        let module_wasm = workspace_root
            .join("target/wasm32-wasip1/release/stringcheese_icu_case_component.wasm");
        assert!(
            module_wasm.exists(),
            "expected wasm at {} after cargo build",
            module_wasm.display(),
        );

        let Some(adapter) = find_wasi_adapter() else {
            eprintln!(
                "SKIP: no wasi_snapshot_preview1.reactor.wasm adapter found on the search path"
            );
            return None;
        };

        // Componentize.
        let component_wasm = std::env::temp_dir().join("stringcheese_icu_case_component.wasm");
        let componentize = Command::new("wasm-tools")
            .args([
                "component",
                "new",
                module_wasm.to_str().expect("path is utf8"),
                "--adapt",
                adapter.to_str().expect("adapter path is utf8"),
                "-o",
                component_wasm.to_str().expect("output path is utf8"),
            ])
            .status()
            .expect("wasm-tools must launch");
        assert!(
            componentize.success(),
            "wasm-tools component new must succeed",
        );
        assert!(
            component_wasm.exists(),
            "expected component at {}",
            component_wasm.display(),
        );
        Some(component_wasm)
    }

    /// Instantiate the component in a fresh `Store`. Each test
    /// owns its own store; instantiation is cheap once the
    /// component is compiled and the linker is populated.
    fn instantiate(&self) -> (Store<HostState>, Case) {
        let mut store = Store::new(
            &self.engine,
            HostState {
                table: ResourceTable::new(),
                wasi: WasiCtxBuilder::new().build(),
            },
        );
        let bindings = Case::instantiate(&mut store, &self.component, &self.linker)
            .expect("component must instantiate against the wasmtime-wasi linker");
        (store, bindings)
    }
}

fn has_tool(name: &str) -> bool {
    Command::new(name)
        .arg("--version")
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status()
        .is_ok_and(|s| s.success())
}

fn target_installed(triple: &str) -> bool {
    let out = Command::new("rustup")
        .args(["target", "list", "--installed"])
        .output();
    match out {
        Ok(o) if o.status.success() => String::from_utf8_lossy(&o.stdout)
            .lines()
            .any(|l| l.trim() == triple),
        _ => true,
    }
}

fn workspace_root() -> PathBuf {
    // CARGO_MANIFEST_DIR is `crates/stringcheese-icu-case-component`;
    // walk up two levels to reach the workspace root.
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    manifest
        .parent()
        .and_then(|p| p.parent())
        .expect("workspace root is two levels above crate manifest")
        .to_path_buf()
}

fn find_wasi_adapter() -> Option<PathBuf> {
    // Search order mirrors `stringcheese-tokenizer-component`'s.
    //   1. `STRINGCHEESE_WASI_ADAPTER` environment variable — the
    //      CI job sets this to the adapter it downloads into
    //      `$RUNNER_TEMP`.
    //   2. `~/.cache/stringcheese-tokenizer-component/wasi_snapshot_preview1.reactor.wasm`
    //      — a shared developer cache (reused across the two
    //      component crates so the one-time download does not
    //      need to be repeated).
    //   3. Any `wasi_snapshot_preview1.reactor.wasm` under
    //      `~/.cargo/registry/src/*/cargo-component/`.
    if let Ok(p) = std::env::var("STRINGCHEESE_WASI_ADAPTER") {
        let path = PathBuf::from(p);
        if path.exists() {
            return Some(path);
        }
    }
    let home = std::env::var_os("HOME").map(PathBuf::from)?;
    let cache =
        home.join(".cache/stringcheese-tokenizer-component/wasi_snapshot_preview1.reactor.wasm");
    if cache.exists() {
        return Some(cache);
    }
    walk_for_adapter(&home.join(".cargo/registry/src")).next()
}

fn walk_for_adapter(root: &std::path::Path) -> impl Iterator<Item = PathBuf> {
    let mut out = Vec::new();
    if let Ok(entries) = std::fs::read_dir(root) {
        for entry in entries.flatten() {
            let path = entry.path();
            let candidate = path.join("cargo-component/wasi_snapshot_preview1.reactor.wasm");
            if candidate.exists() {
                out.push(candidate);
            }
        }
    }
    out.into_iter()
}

/// Format the WIT-side `case-error` variant for a compact panic
/// message when a `Result` returned by an export unexpectedly
/// carries an error. The generated `WitCaseError` type has no
/// stable `Display` impl; the per-arm rendering here keeps the
/// failure message readable when a regression flips a happy-path
/// call into the error tail.
fn describe_err(e: &WitCaseError) -> String {
    match e {
        WitCaseError::InvalidLocale(s) => format!("invalid-locale({s:?})"),
        WitCaseError::LocaleUnavailable(s) => format!("locale-unavailable({s:?})"),
        WitCaseError::UnsupportedTitleMode(s) => format!("unsupported-title-mode({s:?})"),
    }
}

/// Helper — the WIT `type locale = string` alias is rendered as
/// an owned `String` by `wasmtime::component::bindgen!` (aliased
/// primitive types cross the ABI boundary as their concrete
/// Rust type, not `&str`), so every call-site that names a
/// locale needs an owned `String`. Centralising the small
/// allocation keeps the individual tests readable.
fn loc(tag: &str) -> String {
    tag.to_string()
}

#[test]
fn wasmtime_smoke_to_upper_english_ascii() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let mapping = bindings.stringcheese_icu_case_mapping();
    let out = mapping
        .call_to_upper(&mut store, "hello", &loc("en"))
        .expect("to-upper trap-free")
        .unwrap_or_else(|e| panic!("to-upper returned error: {}", describe_err(&e)));
    assert_eq!(out, "HELLO");
}

#[test]
fn wasmtime_smoke_to_upper_turkish_dotted_i() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let mapping = bindings.stringcheese_icu_case_mapping();
    let out = mapping
        .call_to_upper(&mut store, "i", &loc("tr"))
        .expect("to-upper trap-free")
        .unwrap_or_else(|e| panic!("to-upper returned error: {}", describe_err(&e)));
    assert_eq!(out, "\u{0130}", "Turkish `i` upper must yield U+0130 İ");
}

#[test]
fn wasmtime_smoke_to_lower_turkish_dotless_i() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let mapping = bindings.stringcheese_icu_case_mapping();
    let out = mapping
        .call_to_lower(&mut store, "ISTANBUL", &loc("tr"))
        .expect("to-lower trap-free")
        .unwrap_or_else(|e| panic!("to-lower returned error: {}", describe_err(&e)));
    assert_eq!(
        out, "\u{0131}stanbul",
        "Turkish `I` lower must yield U+0131 (dotless ı)",
    );
}

#[test]
fn wasmtime_smoke_to_lower_english_default() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let mapping = bindings.stringcheese_icu_case_mapping();
    let out = mapping
        .call_to_lower(&mut store, "ISTANBUL", &loc("en"))
        .expect("to-lower trap-free")
        .unwrap_or_else(|e| panic!("to-lower returned error: {}", describe_err(&e)));
    assert_eq!(out, "istanbul");
}

#[test]
fn wasmtime_smoke_to_title_ascii_words() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let mapping = bindings.stringcheese_icu_case_mapping();
    let out = mapping
        .call_to_title(
            &mut store,
            "hello world",
            &loc("en"),
            WitTitleOptions {
                boundary: WitTitleBoundary::Words,
                lowercase_tail: true,
            },
        )
        .expect("to-title trap-free")
        .unwrap_or_else(|e| panic!("to-title returned error: {}", describe_err(&e)));
    assert_eq!(out, "Hello World");
}

#[test]
fn wasmtime_smoke_fold_sharp_s_expands_under_full() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let mapping = bindings.stringcheese_icu_case_mapping();
    let out = mapping
        .call_fold(&mut store, "Straße", WitFoldMode::Full)
        .expect("fold trap-free");
    assert_eq!(out, "strasse", "German ß full-fold expands to ss");
}

#[test]
fn wasmtime_smoke_supported_locales_lists_bundled_tags() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let caps = bindings.stringcheese_icu_case_capabilities();
    let locales = caps
        .call_supported_locales(&mut store)
        .expect("supported-locales trap-free");
    assert_eq!(
        locales,
        vec![
            "en".to_string(),
            "de".to_string(),
            "fr".to_string(),
            "tr".to_string(),
            "ru".to_string(),
            "zh".to_string(),
        ]
    );
}

// -----------------------------------------------------------------------
// Phase 6: per-locale smoke tests for the four new packs (de, fr,
// ru, zh) plus one Turkish smoke that re-asserts the tr pack still
// works after the roster expanded.
// -----------------------------------------------------------------------

#[test]
fn wasmtime_smoke_to_upper_german_sharp_s_expands() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let mapping = bindings.stringcheese_icu_case_mapping();
    let out = mapping
        .call_to_upper(&mut store, "straße", &loc("de"))
        .expect("to-upper trap-free")
        .unwrap_or_else(|e| panic!("to-upper returned error: {}", describe_err(&e)));
    assert_eq!(out, "STRASSE");
}

#[test]
fn wasmtime_smoke_to_lower_german_umlaut() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let mapping = bindings.stringcheese_icu_case_mapping();
    let out = mapping
        .call_to_lower(&mut store, "MÄDCHEN", &loc("de"))
        .expect("to-lower trap-free")
        .unwrap_or_else(|e| panic!("to-lower returned error: {}", describe_err(&e)));
    assert_eq!(out, "mädchen");
}

#[test]
fn wasmtime_smoke_to_upper_french_word() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let mapping = bindings.stringcheese_icu_case_mapping();
    let out = mapping
        .call_to_upper(&mut store, "bonjour", &loc("fr"))
        .expect("to-upper trap-free")
        .unwrap_or_else(|e| panic!("to-upper returned error: {}", describe_err(&e)));
    assert_eq!(out, "BONJOUR");
}

#[test]
fn wasmtime_smoke_to_lower_french_oe_ligature() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let mapping = bindings.stringcheese_icu_case_mapping();
    let out = mapping
        .call_to_lower(&mut store, "ŒUVRE", &loc("fr"))
        .expect("to-lower trap-free")
        .unwrap_or_else(|e| panic!("to-lower returned error: {}", describe_err(&e)));
    assert_eq!(out, "œuvre");
}

#[test]
fn wasmtime_smoke_to_upper_russian_word() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let mapping = bindings.stringcheese_icu_case_mapping();
    let out = mapping
        .call_to_upper(&mut store, "привет", &loc("ru"))
        .expect("to-upper trap-free")
        .unwrap_or_else(|e| panic!("to-upper returned error: {}", describe_err(&e)));
    assert_eq!(out, "ПРИВЕТ");
}

#[test]
fn wasmtime_smoke_to_lower_russian_word() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let mapping = bindings.stringcheese_icu_case_mapping();
    let out = mapping
        .call_to_lower(&mut store, "МОСКВА", &loc("ru"))
        .expect("to-lower trap-free")
        .unwrap_or_else(|e| panic!("to-lower returned error: {}", describe_err(&e)));
    assert_eq!(out, "москва");
}

#[test]
fn wasmtime_smoke_to_upper_chinese_han_is_neutral() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let mapping = bindings.stringcheese_icu_case_mapping();
    // Han script has no case; uppercase / lowercase are identity.
    let out = mapping
        .call_to_upper(&mut store, "你好世界", &loc("zh"))
        .expect("to-upper trap-free")
        .unwrap_or_else(|e| panic!("to-upper returned error: {}", describe_err(&e)));
    assert_eq!(out, "你好世界");
}

#[test]
fn wasmtime_smoke_to_upper_chinese_ambient_ascii() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let mapping = bindings.stringcheese_icu_case_mapping();
    // The Chinese pack ships ambient ASCII tables so mixed-script
    // input still works under the zh locale.
    let out = mapping
        .call_to_upper(&mut store, "hello 你好", &loc("zh"))
        .expect("to-upper trap-free")
        .unwrap_or_else(|e| panic!("to-upper returned error: {}", describe_err(&e)));
    assert_eq!(out, "HELLO 你好");
}

#[test]
fn wasmtime_smoke_az_locale_alias_pack_hits_turkish() {
    // Phase 6 algorithm change: Azerbaijani queries pack-hit via the
    // Turkish pack thanks to the `case_locale_alias` table shared
    // across the CaseEngine.
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let mapping = bindings.stringcheese_icu_case_mapping();
    let out = mapping
        .call_to_upper(&mut store, "i", &loc("az"))
        .expect("to-upper trap-free")
        .unwrap_or_else(|e| panic!("to-upper returned error: {}", describe_err(&e)));
    assert_eq!(out, "\u{0130}", "az `i` upper must yield İ via tr alias");
}

#[test]
fn wasmtime_smoke_supports_falls_through_bcp47_chain() {
    let Some(h) = SmokeHarness::build_or_skip() else {
        return;
    };
    let (mut store, bindings) = h.instantiate();
    let caps = bindings.stringcheese_icu_case_capabilities();
    // `en-US` is not registered directly, but falls back to `en`.
    let ok = caps
        .call_supports(&mut store, &loc("en-US"))
        .expect("supports trap-free");
    assert!(ok, "en-US should resolve via BCP 47 fallback to en");
    // `ko` is not registered at all.
    let missing = caps
        .call_supports(&mut store, &loc("ko"))
        .expect("supports trap-free");
    assert!(!missing, "ko is not in the bundled pack set");
}
